import { assertSandboxCampaign } from "@/src/lib/sandbox/engine";

export const blackwaterCreekSandbox = assertSandboxCampaign({
  title: "黑水溪",
  englishTitle: "Blackwater Creek",
  year: "1926",
  place: "马萨诸塞州 · 密斯卡托尼克谷地",
  premise: "一位失踪的考古学家、一批好得反常的私酿威士忌，以及一条重新开始流淌的黑色溪水，把两种截然不同的调查队带进同一个山谷。",
  contentWarnings: ["身体异变与疾病意象", "邪教与精神控制", "枪械、死亡与囚禁", "酒精与犯罪活动", "家庭关系中的恐怖意象"],
  origins: [
    {
      id: "university",
      title: "密斯卡托尼克大学搜救队",
      subtitle: "一封语气反常的来信，是亨利与阿比盖尔留下的最后消息。",
      briefing: "考古系请你们前往黑水溪，确认罗德斯夫妇的安全，并把他们带回阿卡姆。离队学生只记得争执、炸药和一场不肯醒来的梦。",
      objective: "找到罗德斯夫妇，厘清凯德栖所的考古发现。",
      startingLocationIds: ["town", "jarvey-farm", "rhodes-camp"],
      startingItemIds: ["introduction-letter", "field-kit"],
      startingClueIds: ["rhodes-missing"],
      trait: "学院凭证：面对文献、营地和大学关系时拥有更直接的入口。",
    },
    {
      id: "bootlegger",
      title: "波士顿私酒贩小队",
      subtitle: "竞争对手的新酒卖得太好；你们受命接管它的源头。",
      briefing: "德克兰·麦克布莱德付钱让你们找到卡莫迪兄弟，换掉他们的买家。任务可以靠钱、威胁或枪完成——至少出发时看起来如此。",
      objective: "控制卡莫迪农场的威士忌供货，并查清它为何突然变得如此抢手。",
      startingLocationIds: ["town", "carmody-farm"],
      startingItemIds: ["cash-envelope", "revolver", "motorcar"],
      startingClueIds: ["whiskey-boom"],
      trait: "地下门路：面对走私、恐吓和交易时拥有更直接的入口。",
    },
  ],
  clues: [
    { id: "rhodes-missing", title: "失联的罗德斯夫妇", category: "testimony", summary: "考古队已返校，领队夫妇却在黑水溪失去消息。", detail: "最后一封信只说需要休养；熟悉夫妇的人会发现代笔者和语气都不对。", relatedIds: ["unfinished-letter", "field-notes", "abigail-source"] },
    { id: "whiskey-boom", title: "反常走俏的玉米威士忌", category: "substance", summary: "卡莫迪家的新酒让饮用者精神焕发，也让订单暴涨。", detail: "它的甜味里带着腐熟水果的气息；每一批酒都把山谷里的变化运向波士顿。", relatedIds: ["irrigation-line", "distribution-ledger", "living-water"] },
    { id: "animal-sickness", title: "不肯死去的畸形幼畜", category: "testimony", summary: "兽医见过腐坏、攻击性增强且显得过分聪明的牲畜。", detail: "症状沿溪流与饲料扩散，远离灌溉渠的农场受到影响更迟。", relatedIds: ["living-water", "shared-senses"] },
    { id: "sprouston-cult", title: "警长的山中母亲", category: "testimony", summary: "自封警长斯普劳尔斯顿宣讲一位住在山中的“母亲”。", detail: "他既想借调查员除掉卡莫迪兄弟，又会阻止任何人真正伤害山中的存在。", relatedIds: ["cave-sanctuary", "maternal-call"] },
    { id: "unfinished-letter", title: "未写完的求援信", category: "document", summary: "罗德斯曾试图承认洞穴中的发现已经超出考古。", detail: "信停在解释阿比盖尔遭遇之前，纸页边缘留有仓促收拾的痕迹。", relatedIds: ["rhodes-missing", "blast-scar", "field-notes"] },
    { id: "jarvey-boundary", title: "灌溉线外的安全边界", category: "place", summary: "贾维农场离引水渠更远，因此仍保留着相对正常的土地。", detail: "边界另一侧的玉米高得不合季节，说明污染不是疾病自然扩散，而是沿人工水路移动。", relatedIds: ["irrigation-line", "whiskey-boom"] },
    { id: "maternal-call", title: "借用母亲声音的呼唤", category: "contradiction", summary: "离开山谷的人仍梦见一个并非自己母亲的“母亲”。", detail: "呼唤会把受影响者引向溪源；它知道倾听者记忆里最容易相信的声音。", relatedIds: ["sprouston-cult", "abigail-source", "gift-stages"] },
    { id: "camp-ransacked", title: "被翻毁的考古营地", category: "place", summary: "营地不是匆忙撤离，而是遭到有目的的搜查与破坏。", detail: "有人想找走笔记，却遗漏了散在帐篷夹层中的资料。", relatedIds: ["field-notes", "carmody-captivity"] },
    { id: "cave-sanctuary", title: "被掩埋的山中圣地", category: "document", summary: "早期记载把洞穴描述成不可接近的孕育之所。", detail: "定居者曾用爆破封住山谷秘密，罗德斯又沿着同一条传说把入口打开。", relatedIds: ["settlement-record", "blast-scar", "abigail-source"] },
    { id: "living-water", title: "仍在蠕动的黑水", category: "substance", summary: "溪水携带会活动的白色碎片，并让接触者伤口迅速愈合。", detail: "它并非普通污染物；水本身像某个更大生命的循环液。", relatedIds: ["gift-stages", "abigail-source", "irrigation-line"] },
    { id: "irrigation-line", title: "水坝与玉米地", category: "place", summary: "卡莫迪兄弟把新生溪水全部引进玉米地。", detail: "庄稼、牲畜、威士忌和饮用者因此连成同一条传播链。", relatedIds: ["whiskey-boom", "jarvey-boundary", "distribution-ledger"] },
    { id: "shared-senses", title: "害虫共享的视线", category: "contradiction", summary: "农场周围的鼠、蛇和昆虫像由同一个意志指挥。", detail: "布伦丹不必走出屋门就能知道闯入者的位置；腐化让生命之间的边界变薄。", relatedIds: ["gift-stages", "carmody-captivity"] },
    { id: "blast-scar", title: "两次爆破留下的伤口", category: "place", summary: "古老封洞与罗德斯的炸药在同一片山体留下不同年代的痕迹。", detail: "最近的木箱碎片证明洞口附近可能仍有可用炸药。", relatedIds: ["cave-sanctuary", "dynamite-cache"] },
    { id: "settlement-record", title: "凯德栖所的忏悔记录", category: "document", summary: "早期定居者承认他们发现的并非安居之地，而是一处会改变人的圣地。", detail: "幸存者焚烧聚落、封闭洞穴，却没能让山谷真正遗忘。", relatedIds: ["cave-sanctuary", "abigail-source"] },
    { id: "distribution-ledger", title: "每周驶向波士顿的货单", category: "document", summary: "威士忌已经形成稳定运输链，下一车货即将离开。", detail: "只摧毁洞穴而不截断库存，污染仍会沿客户名单继续扩散。", relatedIds: ["whiskey-boom", "irrigation-line"] },
    { id: "carmody-captivity", title: "地窖里的教授", category: "testimony", summary: "亨利·罗德斯被关在农场地下，身体和认知都已严重改变。", detail: "他仍想回到阿比盖尔身边，却无法可靠地区分妻子、母亲和山中存在。", relatedIds: ["field-notes", "abigail-source", "gift-stages"] },
    { id: "field-notes", title: "罗德斯的野外笔记", category: "document", summary: "笔记记录了洞穴、溪水、阿比盖尔事故与教授逐步失控的判断。", detail: "越到后面，“妻子”越常被写成“母亲”；但关于洞口和水源的观测仍可交叉验证。", relatedIds: ["rhodes-missing", "carmody-captivity", "abigail-source"] },
    { id: "gift-stages", title: "赠礼的七次改写", category: "substance", summary: "愈合与年轻只是污染最初的礼貌。", detail: "继续暴露会带来共感、呼唤、身体异变，最后抹去个人意志。", relatedIds: ["living-water", "shared-senses", "maternal-call"] },
    { id: "dynamite-cache", title: "洞口残留的炸药", category: "place", summary: "罗德斯遗下的炸药受潮但并未全部失效。", detail: "它足以封口，也可能摧毁洞内源头；两者的后果完全不同。", relatedIds: ["blast-scar", "abigail-source"] },
    { id: "abigail-source", title: "阿比盖尔与溪源", category: "contradiction", summary: "失踪者不是被藏在洞穴里；她已经成为洞穴与溪水的一部分。", detail: "阿比盖尔残留的意识请求解脱，孕育她的存在却把来客视为新材料。", relatedIds: ["living-water", "field-notes", "maternal-call"] },
  ],
  handouts: [
    { id: "handout-1", number: 1, title: "罗德斯寄给系主任的最后一封信", source: "密斯卡托尼克大学考古系", summary: "语气刻意平静，却回避归期与阿比盖尔的近况。", archiveText: ["工作比预想更棘手，我们还需暂留。", "请不必派人，也不要让学生回来。", "这封信的措辞不像平日负责通信的阿比盖尔。"] },
    { id: "handout-2", number: 2, title: "农舍里未写完的信", source: "贾维农场客房", summary: "一封没有寄出的求援草稿，在解释洞穴发现时中断。", archiveText: ["这里的传说并非象征。", "我们打开了不应再被打开的地方。", "阿比盖尔——后文只剩一道划破纸面的笔痕。"] },
    { id: "handout-3", number: 3, title: "考古帐篷中的部落摘记", source: "罗德斯营地", summary: "摘记把山洞称作诞生与吞没发生在同一处的圣地。", archiveText: ["溪流停下并不等于源头死去。", "进入者会带着比自己更多的生命回来。", "记录最后标着一个朝北的洞穴记号。"] },
    { id: "handout-4", number: 4, title: "旧马萨诸塞神话索引", source: "罗德斯营地", summary: "地方传说反复出现黑土、母亲和无法自然死亡的定居者。", archiveText: ["民俗索引将故事归为集体中毒。", "边注却写着：所有版本都提到同一种脉搏。", "索引页夹着一小片发黑的河泥。"] },
    { id: "handout-5", number: 5, title: "罗德斯的野外笔记", source: "卡莫迪农场地窖", summary: "从考古观察逐渐滑向私人恳求的一册笔记。", archiveText: ["溪水从阿比盖尔所在的位置重新出现。", "水会修复断裂的组织，也会重新决定组织属于谁。", "若我忘记她是谁，请把她从洞里带出来——或让洞不再存在。"] },
    { id: "handout-6", number: 6, title: "伊齐基尔·凯德忏悔录摘编", source: "地方史资料与挖掘现场", summary: "殖民者承认他们曾毁掉聚落并封山，以阻止山中力量继续扩散。", archiveText: ["我们把贪婪称作启示。", "火焚尽屋舍，爆破封住圣所。", "我仍听见大地每隔一段时间替我们心跳。"] },
  ],
  items: [
    { id: "introduction-letter", name: "大学介绍信", description: "能让旧学生、农户和地方资料室愿意多说几句。" },
    { id: "field-kit", name: "考古野外包", description: "手电、绳索、样本瓶和能辨认地层的基本工具。" },
    { id: "cash-envelope", name: "一万美元信封", description: "麦克布莱德给出的谈判资本，也是一份危险的委托证明。" },
    { id: "revolver", name: "短管左轮", description: "它能改变谈判语气，却不能解释山谷。" },
    { id: "motorcar", name: "波士顿牌照汽车", description: "仍可发动时，它是离开黑水溪最快的办法。" },
    { id: "water-sample", name: "密封黑水样本", description: "瓶中白点会逆着摇晃方向缓慢移动。" },
    { id: "cellar-key", name: "农场地窖钥匙", description: "从酒棚账桌暗格中找到，沾着甜腻发黑的液体。" },
    { id: "distribution-book", name: "威士忌货单", description: "记录下一车酒、买家与波士顿交货点。" },
    { id: "dynamite", name: "受潮炸药", description: "仍可能点燃；足够封住洞口，也足够把洞穴变成坟墓。" },
    { id: "jarvey-provisions", name: "贾维家的补给", description: "干净水、食物与一张避开玉米地的小路图。" },
    { id: "cave-map", name: "溪源路线图", description: "把干河床、旧爆破点和洞口连成一条可走的路径。" },
  ],
  npcs: [
    { id: "henry-rhodes", name: "亨利·罗德斯", role: "失踪的考古学教授", faction: "考古队", publicFace: "热情而偏执的地方史学者。", privateDrive: "无论付出什么都想再次见到阿比盖尔。" },
    { id: "abigail-rhodes", name: "阿比盖尔·罗德斯", role: "溪源中残留的意识", faction: "洞穴", publicFace: "失踪的合著者与探险伙伴。", privateDrive: "她请求被终结；与她融合的存在则希望继续孕育。" },
    { id: "damien-carmody", name: "达米恩·卡莫迪", role: "私酒生意的经营者", faction: "卡莫迪农场", publicFace: "务实、善谈、从不让枪离手。", privateDrive: "把酒卖得越远越好，并让外来者相信这只是生意。" },
    { id: "brendan-carmody", name: "布伦丹·卡莫迪", role: "农场中共享感官的异变者", faction: "卡莫迪农场", publicFace: "很久没有在镇上露面。", privateDrive: "通过害虫和牲畜守住农场与水渠。" },
    { id: "dick-sprouston", name: "迪克·斯普劳尔斯顿", role: "自封警长与牧师", faction: "山中会众", publicFace: "愿意帮助陌生人的地方权威。", privateDrive: "借外来者除掉卡莫迪兄弟，再独占“母亲”的眷顾。" },
    { id: "malcolm-jarvey", name: "马尔科姆·贾维", role: "仍愿意接待外人的农夫", faction: "贾维一家", publicFace: "谨慎、疲惫但讲道理。", privateDrive: "保护家人与未被污染的土地。" },
    { id: "edith-jarvey", name: "伊迪丝·贾维", role: "农舍主人", faction: "贾维一家", publicFace: "以食物和规矩维持家的样子。", privateDrive: "她已感到身体变化，却不敢让家人知道程度。" },
    { id: "declan-mcbride", name: "德克兰·麦克布莱德", role: "波士顿委托人", faction: "私酒贩", publicFace: "出手大方的生意人。", privateDrive: "只关心货源和市场，不会主动相信超自然解释。" },
    { id: "ernest-mactavish", name: "欧内斯特·麦克塔维什", role: "大学委托人", faction: "密斯卡托尼克大学", publicFace: "关心同僚安危的系主任。", privateDrive: "希望把罗德斯夫妇带回，也害怕学院声誉受损。" },
    { id: "john-merritt", name: "约翰·梅里特", role: "巡回兽医", faction: "谷地外缘", publicFace: "愿意给陌生人指路的老人。", privateDrive: "让感染止步于黑水溪。" },
    { id: "hector-winney", name: "赫克托·温尼", role: "猎人兼酒鬼", faction: "谷地外缘", publicFace: "拿消息换酒与零钱。", privateDrive: "害怕卡莫迪家的酒，也害怕斯普劳尔斯顿。" },
    { id: "ezekiel-cade", name: "伊齐基尔·凯德", role: "山谷历史中未完全离去的人", faction: "旧聚落", publicFace: "只存在于忏悔录与传言中。", privateDrive: "他的结局证明封洞从来不是彻底的解决。" },
  ],
  corruptionStages: [
    { stage: 0, name: "未接触", benefit: "身体仍由自己定义。", cost: "你只在远处听见山谷的脉搏。" },
    { stage: 1, name: "温暖", benefit: "疲惫与小伤迅速消退。", cost: "你开始怀念并未真正喝过的溪水。" },
    { stage: 2, name: "焕新", benefit: "旧痛消失，感官变得敏锐。", cost: "镜中的自己年轻得不像记忆里的那个人。" },
    { stage: 3, name: "过熟", benefit: "力量和恢复力继续增长。", cost: "皮肤发亮，低刺激模式下以黑色花纹代替具体病变。" },
    { stage: 4, name: "共感", benefit: "能察觉附近生物的恐惧与方向。", cost: "思绪不再只属于自己，山洞的方向变得异常清楚。" },
    { stage: 5, name: "陌生身体", benefit: "疼痛像发生在别人身上。", cost: "身体边界开始失去意义，母亲的声音更加接近。" },
    { stage: 6, name: "应答", benefit: "你能听懂溪水和虫群的意图。", cost: "新的冲动替你决定姿势、声音与去向。" },
    { stage: 7, name: "归于母神", benefit: "孤独彻底消失。", cost: "个人意志被山谷的共同生命吞没。" },
  ],
  locations: [
    {
      id: "town", order: 1, name: "黑水溪镇", archiveName: "地点 01", subtitle: "一条公路、几间木屋与过分热情的警长。",
      atmosphere: "黄昏压在没有路牌的岔口上。镇民隔着窗看车牌，远处每隔四十秒传来一次更像触觉的脉搏。",
      coordinates: { x: 42, y: 62 },
      actions: [
        { id: "town-vet", title: "拦下离镇的兽医", intent: "先问动物发生了什么。", risk: "quiet", scene: "约翰·梅里特把货车停在路肩，却始终没有熄火。", result: "他描述了死胎、攻击性的牲畜，以及远离溪水的农场更晚出现症状。临走前，他把你们指向贾维一家。", reducedResult: "他描述牲畜出现异常生长和行为变化，并强调问题沿溪流扩散。", effects: { clueIds: ["animal-sickness"], unlockLocationIds: ["jarvey-farm", "creek"], npc: [{ npcId: "john-merritt", state: "helpful" }] } },
        { id: "town-sprouston", title: "接受“警长”的盘问", intent: "让斯普劳尔斯顿先说出他想隐瞒的名字。", risk: "exposed", scene: "斯普劳尔斯顿像欢迎客人一样记录你们的姓名、目的和武器。", result: "他把卡莫迪兄弟说成山谷唯一的麻烦，却在提到山洞时改称那里住着自己的“母亲”。你们离开后，镇上的视线更多了。", effects: { clueIds: ["sprouston-cult"], unlockLocationIds: ["woods"], threat: 1, npc: [{ npcId: "dick-sprouston", state: "wary" }] } },
        { id: "town-store-ledger", title: "翻看杂货店的供货账", intent: "沿糖、瓶子和汽油的数量找出酒厂规模。", risk: "exposed", scene: "账本把一座普通农场写成了足以供应半个波士顿的工厂。", result: "卡莫迪家每周购买成箱酒瓶，并让卡车在同一天进山。货量从溪水恢复后开始猛增。", effects: { clueIds: ["whiskey-boom"], unlockLocationIds: ["carmody-farm"], threat: 1 } },
      ],
    },
    {
      id: "jarvey-farm", order: 2, name: "贾维农场", archiveName: "地点 02", subtitle: "灌溉线外最后一块还像正常土地的农场。",
      atmosphere: "屋里有苹果、咖啡和关紧的窗。地界另一边，玉米在无风时仍缓慢摩擦。",
      coordinates: { x: 66, y: 64 },
      actions: [
        { id: "jarvey-letter", title: "检查罗德斯住过的客房", intent: "寻找离开前没能寄出的东西。", risk: "quiet", scene: "床底的纸篓里留着一封被揉皱又展开的信。", result: "信在解释洞穴里的事故时中断。纸上没有明确求救，却处处是一个理性的人正在失去措辞的痕迹。", effects: { clueIds: ["unfinished-letter"], handoutIds: ["handout-2"], unlockLocationIds: ["rhodes-camp", "dig-site"] } },
        { id: "jarvey-boundary", title: "沿两家农场的边界取样", intent: "比较灌溉线两侧的土地。", risk: "quiet", scene: "栅栏西侧的土壤湿黑，东侧仍有普通蚯蚓和杂草。", result: "变化沿卡莫迪家的人工水渠扩散，而不是从镇中心自然蔓延。贾维给了你们一张避开玉米地的小路图。", effects: { clueIds: ["jarvey-boundary"], itemIds: ["jarvey-provisions"], unlockLocationIds: ["creek", "carmody-farm"], npc: [{ npcId: "malcolm-jarvey", state: "helpful" }, { npcId: "edith-jarvey", state: "wary" }] } },
        { id: "jarvey-dream", title: "守过农舍的第一夜", intent: "记录所有人听见的梦话。", risk: "exposed", scene: "午夜后，屋里每个人都用不同的声音说出同一个词：回来。", result: "呼唤借用了各自记忆里的母亲声音，并始终来自山谷北侧。伊迪丝醒来后手上的旧伤已经消失。", reducedResult: "呼唤借用了熟悉的亲人声音，并始终来自山谷北侧；伊迪丝醒来时旧伤已经异常愈合。", effects: { clueIds: ["maternal-call", "gift-stages"], corruption: 1, unlockLocationIds: ["woods"] } },
      ],
    },
    {
      id: "rhodes-camp", order: 3, name: "罗德斯营地", archiveName: "地点 03", subtitle: "帐篷被翻毁，资料却还在风里一页页醒着。",
      atmosphere: "湿帆布贴着倒下的木杆。没有脚印离开营地，只有拖拽痕迹朝农场方向消失。",
      coordinates: { x: 47, y: 43 },
      actions: [
        { id: "camp-search", title: "重建营地最后一晚", intent: "区分撤离、绑架与野兽破坏。", risk: "quiet", scene: "箱锁被工具撬开，食物却没动；破坏者只找笔记和地图。", result: "罗德斯并非自行休养。有人把他和资料一起带走，并刻意让现场看起来像动物闯入。", effects: { clueIds: ["camp-ransacked", "carmody-captivity"], unlockLocationIds: ["carmody-farm"] } },
        { id: "camp-handouts", title: "整理帐篷夹层里的摘记", intent: "把散页按水渍和页码重新排序。", risk: "quiet", scene: "两份摘记共享同一个朝北的洞穴符号。", result: "原住民圣地与地方神话都把洞穴描述成活着的孕育之所；罗德斯把警告当成了地点线索。", effects: { clueIds: ["cave-sanctuary"], handoutIds: ["handout-3", "handout-4"], unlockLocationIds: ["woods", "dig-site"] } },
        { id: "camp-blast-plan", title: "核对炸药领用单", intent: "找出罗德斯最后一次独自进山的方向。", risk: "quiet", scene: "领用单少了一个木箱，地图上的旧河床被铅笔反复描粗。", result: "他沿干涸支流运走炸药。那条路线通往最早的挖掘现场与更北面的洞穴。", effects: { clueIds: ["blast-scar"], unlockLocationIds: ["dry-riverbed", "dig-site"] } },
      ],
    },
    {
      id: "creek", order: 4, name: "黑水溪", archiveName: "地点 04", subtitle: "水重新流动以后，山谷开始拥有同一个身体。",
      atmosphere: "泥土几乎是黑色的，水面下的白点逆流而上。任何裸露皮肤都觉得溪水比空气更温暖。",
      coordinates: { x: 31, y: 50 },
      actions: [
        { id: "creek-sample", title: "密封一瓶活水", intent: "确认变化究竟在水、泥还是生物里。", risk: "dangerous", scene: "样本瓶封紧后，白色碎片仍在玻璃内寻找上游。", result: "溅到手背的水让一道小伤立刻闭合。你们带走样本，也带走一次无法撤销的接触。", reducedResult: "溅到手背的水让一道小伤异常愈合。你们带走样本，也带走一次无法撤销的接触。", effects: { clueIds: ["living-water", "gift-stages"], itemIds: ["water-sample"], corruption: 1, unlockLocationIds: ["dry-riverbed"] } },
        { id: "creek-dam", title: "测绘水坝与引水渠", intent: "把溪源、农田和酒棚画进同一张图。", risk: "exposed", scene: "所有新水都被导向卡莫迪玉米地，只有溢流继续往镇外走。", result: "传播链已经完整：洞穴、溪水、玉米、威士忌、波士顿。毁掉水坝若不处理源头，只会让污染直接进入大河。", effects: { clueIds: ["irrigation-line"], unlockLocationIds: ["carmody-farm", "dry-riverbed"], threat: 1 } },
        { id: "creek-follow", title: "逆流寻找脉搏最强处", intent: "让溪水自己指出源头。", risk: "dangerous", scene: "越往北，植物越像在为同一次呼吸起伏。", result: "干河床与新溪流在旧爆破点汇合。你们画出最后一段路线，但山中的声音也更清楚地记住了你们。", effects: { clueIds: ["maternal-call"], itemIds: ["cave-map"], unlockLocationIds: ["dry-riverbed", "cave"], corruption: 1, threat: 1 } },
      ],
    },
    {
      id: "woods", order: 5, name: "北坡森林", archiveName: "地点 05", subtitle: "每只眼睛都可能属于同一个没有走出屋门的人。",
      atmosphere: "树皮鼓起缓慢的结，鸟群同时转头。玉米地里的窸窣声一路跟进森林，却看不见追踪者。",
      coordinates: { x: 22, y: 33 },
      actions: [
        { id: "woods-network", title: "观察同时转向的动物", intent: "验证害虫是否共享感官。", risk: "exposed", scene: "一只乌鸦看见你时，远处所有鼠洞同时安静。", result: "农场周围的生物不是受训，而是在替同一个意识看守边界。布伦丹·卡莫迪已经不需要亲自巡视。", effects: { clueIds: ["shared-senses"], threat: 1, npc: [{ npcId: "brendan-carmody", state: "hostile" }] } },
        { id: "woods-old-path", title: "寻找旧聚落留下的山路", intent: "避开现代水渠，沿最早的封山路线前进。", risk: "quiet", scene: "苔藓下的石阶比镇上任何房子都更老，尽头埋着焦黑地基。", result: "凯德栖所不是传说中的繁荣殖民地，而是一处被自己人焚毁的隔离区。", effects: { clueIds: ["settlement-record"], handoutIds: ["handout-6"], unlockLocationIds: ["dig-site", "dry-riverbed"] } },
        { id: "woods-escape-route", title: "标出一条离镇路线", intent: "在车辆失效前准备步行逃离。", risk: "exposed", scene: "北坡有一条不经过镇口的小径，能通往敦威治方向。", result: "路线足够让幸存者撤走，但无法带走被囚者或截住下一车威士忌。斯普劳尔斯顿的人已经注意到路标。", effects: { itemIds: ["cave-map"], threat: 1 } },
      ],
    },
    {
      id: "dig-site", order: 6, name: "挖掘现场", archiveName: "地点 06", subtitle: "考古学把一场旧日封锁误读成等待发掘的历史。",
      atmosphere: "探沟里没有日常器物，只有烧结土、折断工具和被爆风压进地层的木片。",
      coordinates: { x: 39, y: 25 },
      actions: [
        { id: "dig-strata", title: "读取焦土与爆破层", intent: "判断旧聚落如何结束。", risk: "quiet", scene: "火灾层之后立刻是爆破抛出的岩石，没有重建，也没有正常墓葬。", result: "定居者主动烧毁住所并封住北面的山洞。所谓“消失的聚落”其实是一场失败的隔离行动。", effects: { clueIds: ["settlement-record", "blast-scar"], handoutIds: ["handout-6"], unlockLocationIds: ["dry-riverbed"] } },
        { id: "dig-marker", title: "拼合刻着脉搏记号的石片", intent: "把古老路线叠到罗德斯地图上。", risk: "quiet", scene: "石片上的重复短线不是装饰，而是按固定间隔记录的脉搏。", result: "记号从聚落一路指向溪源。罗德斯找到的不是遗址中心，而是旧居民最想远离的地方。", effects: { clueIds: ["cave-sanctuary"], unlockLocationIds: ["cave"] } },
        { id: "dig-cade", title: "追查凯德最后的记录", intent: "确认封洞以后是否真的无人返回。", risk: "exposed", scene: "最新的一行字比其余记录晚了数十年，笔迹却没有衰老。", result: "伊齐基尔·凯德可能在第一次污染中活了下来。长寿不是解脱，而是山谷保留见证人的方式。", effects: { clueIds: ["gift-stages"], threat: 1, npc: [{ npcId: "ezekiel-cade", state: "transformed" }] } },
      ],
    },
    {
      id: "dry-riverbed", order: 7, name: "干河床", archiveName: "地点 07", subtitle: "旧水路记得溪流停下前去往哪里。",
      atmosphere: "干裂河泥下仍有潮湿的黑线，像一条被压住却没有断掉的血管。",
      coordinates: { x: 58, y: 31 },
      actions: [
        { id: "riverbed-trace", title: "沿地下湿线追到悬崖", intent: "在植被彻底封路前确定洞口。", risk: "exposed", scene: "旧河床在悬崖下消失，新水却从二十英尺高处越过石壁。", result: "你们找到了洞穴，也确认它是新生溪流的唯一源头。路线图如今足以在黑夜里带队抵达。", effects: { clueIds: ["living-water"], itemIds: ["cave-map"], unlockLocationIds: ["cave"], threat: 1 } },
        { id: "riverbed-muck", title: "检查泥层里会活动的碎片", intent: "比较溪水停流前后的沉积。", risk: "dangerous", scene: "白色碎片钻进更深的湿土，避开火光。", result: "旧河泥没有这些东西；它们随着阿比盖尔事故后的新水一起出现。一次接触让山中脉搏与你的心跳短暂重合。", reducedResult: "旧河泥没有这些东西；它们随着新水一起出现。一次接触让山中脉搏与你的心跳短暂重合。", effects: { clueIds: ["abigail-source", "gift-stages"], corruption: 1 } },
        { id: "riverbed-blast", title: "找出第二次爆破的运送痕迹", intent: "确认炸药是否全在洞中用完。", risk: "quiet", scene: "木箱拖痕到洞口前中断，碎木数量与领用单不符。", result: "至少还有几支炸药留在洞口落石下。它们受潮，但并非完全失效。", effects: { clueIds: ["dynamite-cache"], unlockLocationIds: ["cave"] } },
      ],
    },
    {
      id: "carmody-farm", order: 8, name: "卡莫迪农场", archiveName: "地点 08", subtitle: "玉米、酒桶和虫群共同守着一间上锁的地窖。",
      atmosphere: "玉米高过汽车，酒棚日夜冒汽。田里没有风，却总有一圈窸窣声绕着来客移动。",
      coordinates: { x: 76, y: 46 },
      actions: [
        { id: "carmody-negotiate", title: "同达米恩谈一笔更大的生意", intent: "让他亲口说明酒要去哪里。", risk: "exposed", scene: "达米恩愿意换买家，也愿意接受任何让出货更多的条件。", result: "他不隐瞒货量，只隐瞒原因。下一车酒将在黎明离开；账桌暗格里藏着地窖钥匙。", effects: { clueIds: ["distribution-ledger"], itemIds: ["cellar-key"], threat: 1, npc: [{ npcId: "damien-carmody", state: "wary" }] } },
        { id: "carmody-ledger", title: "潜入酒棚与账房", intent: "拿到货单，在害虫通风报信前离开。", risk: "dangerous", requirementHint: "需要先知道酒棚的规模，或以私酒贩身份熟悉装运流程。", requires: { anyClueIds: ["whiskey-boom", "irrigation-line"] }, scene: "鼠群沿横梁追着灯光移动，账本却清楚写着每一批酒的去向。", result: "你们拿到货单和地窖钥匙。布伦丹通过墙里的虫群看见了这一切，农场从此不再假装友好。", effects: { clueIds: ["distribution-ledger", "shared-senses"], itemIds: ["distribution-book", "cellar-key"], threat: 2, npc: [{ npcId: "brendan-carmody", state: "hostile" }, { npcId: "damien-carmody", state: "hostile" }] } },
        { id: "carmody-rescue", title: "打开地窖，带走罗德斯", intent: "在教授的呼喊引来守卫前判断他还能否同行。", risk: "dangerous", requirementHint: "需要地窖钥匙。", requires: { allItemIds: ["cellar-key"] }, scene: "罗德斯被锁在渗水的墙边，仍紧抱一本几乎散架的野外笔记。", result: "他已进入严重异变，却还能指出阿比盖尔与溪源的关系。你们带走教授和笔记；他一路请求返回洞穴。", reducedResult: "罗德斯的身体与认知已经严重改变，却还能指出阿比盖尔与溪源的关系。你们带走教授和笔记；他一路请求返回洞穴。", effects: { clueIds: ["carmody-captivity", "field-notes", "abigail-source"], handoutIds: ["handout-5"], threat: 2, npc: [{ npcId: "henry-rhodes", state: "rescued" }] } },
        { id: "carmody-sabotage", title: "焚毁库存并破坏蒸馏器", intent: "先截断流向波士顿的传播链。", risk: "dangerous", requirementHint: "需要货单定位库存，或用大学野外包安全处理酒棚。", requires: { anyClueIds: ["distribution-ledger"], noneActionIds: ["farm-assault"] }, scene: "火沿酒精蒸汽越过棚顶，玉米地里的所有虫声在同一秒拔高。", result: "库存和蒸馏器被毁，下一车货再也不会离开。卡莫迪兄弟与斯普劳尔斯顿都把你们视为必须立刻处理的敌人。", effects: { threat: 3, npc: [{ npcId: "damien-carmody", state: "hostile" }, { npcId: "brendan-carmody", state: "hostile" }, { npcId: "dick-sprouston", state: "hostile" }] } },
        { id: "farm-assault", title: "没有退路地强攻农场", intent: "用正面火力一次解决卡莫迪兄弟。", risk: "terminal", requirementHint: "只有尚未破坏酒棚时，这条最坏的捷径才会出现。", requires: { noneActionIds: ["carmody-sabotage", "carmody-rescue"] }, scene: "第一声枪响后，玉米地、马厩、鼠洞和酒棚像同一只动物那样合拢。", result: "你们打中过看得见的敌人，却没能击败整座农场。最后一页行动记录停在酒棚起火之前，波士顿仍在等待下一车酒。", reducedResult: "你们击退了眼前的守卫，却没能穿过由整座农场组成的包围。行动记录在黎明前中断。", effects: { threat: 6, npc: [{ npcId: "henry-rhodes", state: "lost" }] } },
      ],
    },
    {
      id: "cave", order: 9, name: "溪源洞穴", archiveName: "地点 09", subtitle: "流水、脉搏和阿比盖尔的声音来自同一片黑暗。",
      atmosphere: "洞壁发出淡紫微光，水从脚下流过。越深入，哭声越像每个人最熟悉的那位亲人。",
      coordinates: { x: 68, y: 15 },
      actions: [
        { id: "cave-enter", title: "进入会呼吸的通道", intent: "确认声音属于阿比盖尔还是某种诱饵。", risk: "dangerous", requirementHint: "需要溪源路线图，或至少两条指向洞穴的证据。", requires: { anyClueIds: ["cave-sanctuary", "abigail-source", "living-water"] }, scene: "通道两侧的组织随山谷脉搏收缩，阿比盖尔的声音在更深处请求结束。", result: "她的意识仍在，却已与一个庞大的孕育器官无法分开。溪水正从那里形成，新的东西在半透明的内部移动。", reducedResult: "洞壁随山谷脉搏收缩，阿比盖尔的意识仍在，却已与溪源无法分开。某种新的生命正在其中成形。", effects: { clueIds: ["abigail-source", "gift-stages"], corruption: 1, npc: [{ npcId: "abigail-rhodes", state: "transformed" }] } },
        { id: "cave-dynamite", title: "从洞口落石下取出炸药", intent: "在决定封口或摧毁前，先得到真正的选择。", risk: "dangerous", requirementHint: "需要知道炸药仍有剩余。", requires: { allClueIds: ["dynamite-cache"] }, scene: "五支炸药里有几支引信仍干燥，足够完成一次不可逆的决定。", result: "你们把炸药移到干处。封洞风险较低，却会让源头继续生长；深入布置则可能摧毁它，也可能让所有人来不及逃。", effects: { itemIds: ["dynamite"], threat: 1 } },
        { id: "cave-seal", title: "炸塌洞口，截断来路", intent: "先把山谷与源头隔开。", risk: "dangerous", requirementHint: "需要炸药。", requires: { allItemIds: ["dynamite"], noneActionIds: ["cave-destroy"] }, scene: "爆破把悬崖折进溪源，黑水在碎石后继续寻找缝隙。", result: "洞口被封，短期内无人能进入。源头没有被摧毁；如果水坝仍在，污染会继续进入农场，如果水坝毁坏，它会改道进入大河。", effects: { threat: 1 } },
        { id: "cave-destroy", title: "深入布置炸药，摧毁溪源", intent: "回应阿比盖尔的请求，并让孕育在这里结束。", risk: "dangerous", requirementHint: "需要炸药，以及阿比盖尔与溪源关系的可靠证据。", requires: { allItemIds: ["dynamite"], allClueIds: ["abigail-source"], noneActionIds: ["cave-seal"] }, scene: "引信点燃以后，撤退路线只剩通道、湿滑岩壁和试图挽留你们的触须。", result: "悬崖在身后塌下，溪流先变得滚烫，随后第一次彻底安静。阿比盖尔的声音没有再追出山谷。", reducedResult: "引信点燃以后，你们穿过收缩的通道撤离。悬崖在身后塌下，溪流先变热，随后第一次彻底安静。", effects: { threat: 2, npc: [{ npcId: "abigail-rhodes", state: "lost" }] } },
      ],
    },
  ],
  endings: [
    {
      id: "farm-fall", title: "玉米地合拢", archiveLabel: "行动中断", theme: "以为敌人只有两个人，是黑水溪最昂贵的误判。",
      terminal: true, requires: { allActionIds: ["farm-assault"] },
      result: "农场吞下强攻小队，酒厂只停工了一夜。失踪者被写进地方治安记录，下一辆运酒卡车仍在一周后驶往波士顿。",
      coda: "档案最后附着一只干死的黑色甲虫；它的腹部仍每隔四十秒轻轻起伏。",
    },
    {
      id: "escape", title: "从北坡离开", archiveLabel: "幸存撤离", theme: "活着带走真相，却把问题留在山谷里继续生长。",
      requires: { anyActionIds: ["woods-escape-route", "riverbed-trace"], minThreat: 3 },
      result: "你们沿北坡小径摆脱追踪，把证词和样本带回文明世界。没有人立刻相信；卡莫迪家的酒仍会离开山谷，洞穴里的脉搏也没有停止。",
      coda: "几周后，有人夜里醒来，发现一处旧伤愈合得异常整齐。",
    },
    {
      id: "bargain", title: "接管威士忌生意", archiveLabel: "交易成立", theme: "你们赢得了农场，却把污染变成一份扩张计划。",
      requires: { origins: ["bootlegger"], allActionIds: ["carmody-negotiate"], allClueIds: ["distribution-ledger"], noneActionIds: ["carmody-sabotage", "cave-destroy"] },
      result: "达米恩接受新买家，货单换了名字，酒瓶没有换。波士顿最初只看见奇迹般的恢复力；等顾客开始梦见同一位母亲，生意早已遍布全城。",
      coda: "麦克布莱德举杯庆祝时，你们听见仓库地板下传来一次缓慢的心跳。",
    },
    {
      id: "contain", title: "封洞并烧掉库存", archiveLabel: "暂时封存", theme: "传播链被切断，但源头仍在石头后面呼吸。",
      requires: { allActionIds: ["carmody-sabotage", "cave-seal"], allClueIds: ["distribution-ledger", "abigail-source"] },
      result: "波士顿等不到下一车酒，黑水溪也暂时等不到新的朝圣者。洞口被封，水量渐小，却没有完全停止；这是一场争取到时间的胜利。",
      coda: "冬天结冰前，碎石缝里长出一朵不属于马萨诸塞州的紫色花。",
    },
    {
      id: "destroy", title: "让溪流第一次安静", archiveLabel: "源头摧毁", theme: "摧毁洞穴并不能抹去发生过的一切，但能阻止下一次诞生。",
      requires: { allActionIds: ["cave-destroy"], allClueIds: ["abigail-source", "living-water"] },
      result: "爆破摧毁了溪源，山谷的共同脉搏停下。若库存也被焚毁，污染止步于黑水溪；若货单仍在执行，已经离开的酒会留下漫长而隐秘的余波。",
      coda: "获救者在远离山谷的夜里仍会梦见阿比盖尔，但梦中再没有任何东西借她的声音回答。",
    },
  ],
  presentation: {
    caseNumber: "003",
    caseTypeLabel: "NON-COMMERCIAL PROTOTYPE",
    loadingTitle: "正在展开黑水溪地图",
    entryEyebrow: "1926 · Miskatonic Valley",
    entryCta: "以此身份进入山谷",
    navigationLabel: "黑水溪卷宗导航",
    mapTitle: "密斯卡托尼克谷地",
    mapDescription: "地点可以乱序调查；亮起的卷宗钉代表你已有足够线索前往。",
    mapAriaLabel: "黑水溪地点地图",
    mapCaption: "BLACKWATER CREEK · FIELD SURVEY 1926",
    conditionLabel: "污染",
    conditionAdvanceHint: "进一步接触溪水、受污染食物或洞穴才会推进。",
    threatLabel: "山谷警觉",
    handoffModeLabel: "黑水溪夜班模式",
    sleepEthic: "睡眠质量只改变报告的叙事丰富度，不改变线索、污染、人物状态或结局。",
    nightTitle: "黑水溪夜班进行中",
    nightClosingLine: "山谷没有停止变化；晨报会把结果完整带回来。",
    morningTitle: "黑水溪晨报",
    noNewEvidence: "没有新增卷宗，但行动已经改变山谷的威胁与可用收场。",
    noEndingTitle: "还没有可收束的路线",
    noEndingDescription: "继续调查溪源、卡莫迪农场或北坡逃生路线。至少一条明确退路出现后，卷宗才允许结案。",
    resetTitle: "重新开始《黑水溪》？",
    resetDescription: "这会清除本案的身份、地点、手札、污染和结局进度；其他案件不受影响。",
    endingEyebrow: "BLACKWATER CREEK",
    handoutKicker: "BLACKWATER CREEK",
    handoutFooter: "交互改编摘要 · 非原 PDF 逐字转录",
    briefingHeading: "改编与使用说明",
    creditsHeading: "原作者 Scott Dorward · 译者 埃兰迪斯",
    npcStateLabels: {
      unknown: "尚未接触",
      wary: "戒备",
      helpful: "愿意协助",
      hostile: "敌对",
      rescued: "已救出",
      lost: "已失去",
      transformed: "已异变",
    },
  },
  credits: {
    attribution: "原作者 Scott Dorward · 译者 埃兰迪斯",
    adaptation: "Night Shift 非商业交互原型；基于用户提供的中文模组版本进行重新编排与原创表述。",
    usage: "仅供个人学习与交流；不得商业使用。",
    notice: "保留原作者、译者与许可信息。源 PDF、原插图和完整译文不包含在本项目中。",
  },
});
