import {
  caseCharacterSchema,
  caseSchema,
  cityDistrictSchema,
  cityWatchEchoSchema,
  endingEpilogueSchema,
  evidenceRelationSchema,
  journeyPostcardSchema,
  nightBotanicalSchema,
  routeDirectionSchema,
  wakeEchoSchema,
  type CityWatchId,
  type EndingEpilogue,
  type JourneyPostcard,
  type NightBotanical,
  type RouteDirection,
} from "@/src/lib/game-engine/schema";
import { defineCampaign } from "./types";

export const CHIHAYA_NOA_CAMPAIGN_ID = "case-005";

const chihayaNoaCase = caseSchema.parse({
  id: CHIHAYA_NOA_CAMPAIGN_ID,
  title: "千早诺亚的第十三次旅行",
  englishTitle: "Chihaya Noa's Thirteenth Journey",
  chapters: [
    {
      number: 1,
      title: "明日才抵达的委托人",
      subtitle: "十二份入境记录都是真的，第十三张车票却要到明天才发售。",
      cityAside: "雾灯城允许旅客迟到，但不接受一个人比自己的档案多抵达十二次。",
      question: "千早诺亚为何在没有离境的情况下连续入境十二次？",
      choices: [
        { id: "school", label: "核对寄宿学校的十三张照片", note: "先问同一间宿舍记住了多少种她。" },
        { id: "harbor", label: "沿雾港入境章追查十二次抵达", note: "让日期、行李和指纹自己排队。" },
        { id: "platform", label: "在停用站台等一张明日车票", note: "不替列车决定它究竟来自哪一天。" },
      ],
      clueIds: ["twelve-entry-stamps", "tomorrow-ticket", "thirteen-school-portraits"],
      collectibleIds: ["future-ticket", "harbor-stamp"],
      route: ["夜班事务所", "寄宿学校旧档室", "雾港入境厅", "十三号停用站台"],
      events: [
        "00:43 — 第十二枚入境章在封存簿上重新洇开。",
        "01:18 — 三名学生说出互不相容、却都有细节的诺亚。",
        "02:31 — 明日车票在站钟下提前留下剪票孔。",
        "03:46 — 十三张照片中的人同时偏开视线。",
        "05:02 — 诺亚把一枚纸结留在事务所门缝，没有要求被营救。",
      ],
      journal: "雾港保存着十二份千早诺亚的入境记录，每一份衣着、行李与日期不同，每一枚指纹却都能通过检验。寄宿学校又留下十三张互不相同的入学照片；其中最晚一张把她和事务所的空椅拍在一起。她不是失踪者。她先于委托找上门，只要求我们在第十三次抵达以前证明：矛盾并不自动等于撒谎。",
      contradiction: "如果只有一位诺亚抵达过雾灯城，十二份合法记录和十三段具体记忆从何而来？",
    },
    {
      number: 2,
      title: "两个都记得昨夜的人",
      subtitle: "第十三号列车带来另一位诺亚，她们都能指出对方忘记的街道。",
      cityAside: "城市习惯给同名者追加编号，今晚却找不到哪一个编号应该先写。",
      question: "两位诺亚共享身份，却为什么记得不同版本的昨夜？",
      choices: [
        { id: "knots", label: "跟随墙角的纸结旧路", note: "把每一个折法当作一位旅行者留下的路标。" },
        { id: "map", label: "叠合两张彼此否认的街图", note: "让消失的路从纸背重新穿过来。" },
        { id: "interview", label: "分别听完两份相反证词", note: "不要求任何一位先证明另一位是假货。" },
      ],
      clueIds: ["paper-knot-route", "revised-street-map"],
      collectibleIds: ["paper-knot-spool", "bloodless-cutter"],
      route: ["十三号停用站台", "折返巷", "双版测绘室", "雨棚下的分别问询桌"],
      events: [
        "00:39 — 两枚相同纸结分别指向已经封死与从未存在的巷口。",
        "01:24 — 一张地图在叠合后多出第十三条折返线。",
        "02:16 — 沾血裁纸刀没有留下任何人的伤口记录。",
        "03:53 — 两位诺亚同时说出林渡尚未问出口的问题。",
        "05:07 — 她们各自离开，只约定不把另一位交给警方。",
      ],
      journal: "列车送来的诺亚握着裁纸刀，同行的诺亚先认出了刀柄上的纸结。她们对昨夜的记忆相反，却都能沿自己的折法走出一条完整路线。叠合地图显示，城市至少被局部改写过十二次；旧路没有消失，只是被挤到纸张无法承认的背面。我们没有替她们挑选谁跟随调查。两个人都保留行动权，也都在独立检查我们。",
      contradiction: "如果其中一位只是复制品，她为什么拥有另一位从未经历、却能被地图验证的连续路线？",
    },
    {
      number: 3,
      title: "拱灯学会的假东方",
      subtitle: "终灯会把掠来的器物、错译仪式与一名活人陈列在同一张节目单上。",
      cityAside: "雾灯城最体面的收藏家总能准确记住价格，唯独忘记器物原本的名字。",
      question: "终灯会究竟从千早家的返照仪式里理解了什么？",
      choices: [
        { id: "catalogue", label: "逐条拆穿收藏目录的错译", note: "先把被抹掉的来路还给器物。" },
        { id: "stage", label: "让林渡接过仪式表演的注视", note: "不给学会把诺亚变成解释自身幻想的道具。" },
        { id: "vault", label: "沿无编号展签潜入镜片库", note: "让错误分类替我们打开收藏者没看见的门。" },
      ],
      clueIds: ["mirror-shard-memory", "ritual-mistranslation", "platform-blueprint"],
      collectibleIds: ["returning-mirror-shard", "mislabelled-plaque"],
      route: ["拱灯学会街", "阿卡迪亚陈列厅", "无编号镜片库", "地下线路绘图室"],
      events: [
        "00:47 — 展签把三种互不相干的仪式写成同一场表演。",
        "01:36 — 返照镜碎片映出林渡没有走过的返程路线。",
        "02:28 — 诺亚纠正器物名称时，学会成员先检查她是否在节目单上。",
        "03:41 — 年轻编目员交出一张通往未成线的站台图。",
        "05:11 — 镜片库熄灯，十三个方向的脚步声仍没有停止。",
      ],
      journal: "终灯会没有理解千早家的返镜仪式，只学会把铜镜、时刻表和城市线路叠在一起。他们把被掠器物抹去来路，再让一个日本学生替虚构的“东方神秘”背书。返照镜碎片保存的不是预言，而是一段已经生活过的可能记忆；地下图纸则证明，学会一直把被重置的人送往一条未成线路。错误的知识并未让仪式失效，只让它失去任何伦理边界。",
      contradiction: "一套被严重错译的仪式为什么仍能稳定留下十二段完整人生？",
    },
    {
      number: 4,
      title: "未成线的十二个地址",
      subtitle: "被删除的城市版本里，每一位诺亚都拥有住址、债务和不肯交出的记忆。",
      cityAside: "档案馆称未完成的街区不具备住户；住户们因此把门牌写在梦里。",
      question: "十二位旧诺亚是镜中残影，还是被城市排除的真实居民？",
      choices: [
        { id: "addresses", label: "逐户核对未成线住址", note: "生活的连续性比同一张脸更能证明一个人。" },
        { id: "observer", label: "拆查仪式中央的观察者席", note: "寻找是谁把判断伪装成自然规律。" },
        { id: "zero-key", label: "用零号钥匙打开回程门", note: "只测试出口，不替任何人决定是否离开。" },
      ],
      clueIds: ["unmade-address-book", "observer-chair-log", "zero-key-casting"],
      collectibleIds: ["zero-key", "thirteen-ticket-clasp"],
      route: ["未成线入口", "十二户折返公寓", "观察者席", "零号回程门"],
      events: [
        "00:42 — 十二扇门各自认出一种不同的敲门节奏。",
        "01:33 — 住址簿记录了房租、病假与十二段互不重复的生活。",
        "02:45 — 观察者席的扶手留下历代裁决者按住笔的凹痕。",
        "03:58 — 零号钥匙打开出口，却没有自动选择应该通过的人。",
        "05:13 — 十二位诺亚把各自名字签在同一只黄铜票夹里。",
      ],
      journal: "未成线不是镜子里的仓库。十二位诺亚在这里生活了不同长度的时间：有人修过屋顶，有人欠下图书馆罚款，有人已经成为替后来者标路的调查员。观察者席记录了仪式真正的开关——只要一位被认可的裁决者宣布谁是原本，其余人生就会被现实排除。零号钥匙只负责开门，从不负责选人。选择被写进了椅子，而不是镜子。",
      contradiction: "如果镜子会自动选出唯一真身，终灯会为什么还要为外部观察者保留一张裁决席？",
    },
    {
      number: 5,
      title: "拒绝唯一原本",
      subtitle: "十三位千早诺亚在黎明前签下十三种名字，等待调查者决定是否仍要替她们选择。",
      cityAside: "城市愿意承认十三张车票，却坚持同一个名字只能兑换一份清晨。",
      question: "证据应当公开、封存，还是把名字与去留权交还给十三位当事人？",
      choices: [
        { id: "publish", label: "公开十三份完整证词", note: "阻止秘密裁决，也承担猎奇目光同时抵达的代价。" },
        { id: "shelter", label: "封存返照镜与全部住址", note: "先让十三个人离开终灯会的观察范围。" },
        { id: "return", label: "把签名、出口与沉默权逐一交还", note: "不替任何人宣布谁才有资格继续成为诺亚。" },
      ],
      clueIds: ["thirteen-signed-tickets"],
      collectibleIds: ["thirteen-ticket-clasp"],
      route: ["未成线入口", "十三号站台", "熄灭的返照镜", "夜班事务所归档桌"],
      events: [
        "00:43 — 十三张车票同时在不同日期上完成检票。",
        "01:26 — 终灯会要求林渡坐上观察者席。",
        "02:37 — 十三位诺亚分别写下希望公开、保留或舍弃的名字。",
        "03:49 — 零号门为每一份签名保留独立出口。",
        "05:00 — 镜面失去裁决者，第一次只映出十三个人。",
      ],
      journal: "终灯会需要的从来不是第十三个祭品，而是一位愿意把复杂人生压成单一答案的观察者。十三张签名车票证明，每位诺亚都能独立说明自己的来路、关系与选择。公开可以摧毁终灯会的秘密，封存可以争取安全；但最完整的归还，是让每个人自己决定使用哪个名字、走哪一扇门，以及是否让白昼知道她曾经存在。事务所只应保存她们交出的决定，不应替她们完成决定。",
      contradiction: "当十三个人都能连续证明自己的生活时，调查者还有什么资格指定唯一原本？",
    },
  ],
  clues: [
    ["twelve-entry-stamps", "十二份合法入境章", "同一名旅客连续十二天入境却从未离境", "每枚章的日期、行李申报与纸张老化都真实，指纹也属于千早诺亚。", "雾港管理处称重复抵达属于旅客填写习惯。", "十二次抵达不是同一条记录被复制，而是十二段路线各自留下的行政影子。", "event", 1],
    ["tomorrow-ticket", "明日才发售的车票", "一张尚未进入售票系统的第十三号列车票", "票纸、油墨与剪票孔都来自次日班次，背面却有诺亚今夜留下的指印。", "铁路局认为明天的票今天尚不具备乘车资格。", "它不是预言，是下一次重置已经伸进今晚的边角。", "object", 1],
    ["thirteen-school-portraits", "十三张入学照片", "寄宿学校保存十三种神态与发型不同的诺亚", "底片编号来自不同学期，其中一张甚至拍到尚未与她见面的事务所座位。", "校方愿意承认摄影事故，不愿承认十三段校园生活。", "照片互相矛盾，却都拥有各自的同学签名与磨损。", "person", 1],
    ["paper-knot-route", "十二种纸结路线", "墙角纸结记录了十二次互不相同的封印行程", "每套折法从入境厅开始，在不同地点结束，并准确避开对应版本中不存在的街道。", "市政清洁处把纸结归类为未成年人乱丢的路标。", "每一种折法都只可能来自真正走完那条路的人。", "place", 2],
    ["revised-street-map", "重写十二次的街图", "同一张城市底图保留十二层被覆盖的道路", "纸纤维中的墨线依次变旧，和纸结路线、入境日期逐层对应。", "测绘署称地图可以犯错，城市不应为此负责。", "现实每次都被重写，旧路只是被压到新墨水下面。", "contradiction", 2],
    ["mirror-shard-memory", "保存生活的返照镜片", "碎片映出的不是未来，而是一段完整经历过的可能人生", "镜面细痕与一位旧诺亚的住址、伤口和纸结习惯逐项对应。", "终灯会称可能性不具备居民身份。", "被另一种选择改变的人生，仍然是一段活过的时间。", "object", 3],
    ["ritual-mistranslation", "被拼凑的仪式译注", "终灯会把多种无关传统错写成可供表演的返照仪式", "真正有效的部分只有千早家镜片、铁路时序和城市地图；猎奇服饰与伪造咒文只是权力装饰。", "学会坚持错误只要足够昂贵便可称作综合研究。", "无知没有阻止机器运转，只让使用它的人不再看见当事人。", "contradiction", 3],
    ["platform-blueprint", "未成线站台图", "学会图纸把每次重置后的旧路线导向同一条地下支线", "十二个侧线编号分别对应一份入境记录，末端都标着无人居住。", "铁路档案称未建成线路不能拥有乘客。", "站台不是回收倒影的仓库，而是城市放逐矛盾居民的地址。", "place", 3],
    ["unmade-address-book", "未成线住址簿", "十二位诺亚各自拥有连续生活、关系与债务", "住址簿记录房租、借书、工作与病假，笔迹跨度远超一次仪式表演。", "户籍处称被删除城区的租金不产生法律义务。", "一个人是否真实，不由她的街区有没有被主城承认。", "person", 4],
    ["observer-chair-log", "观察者席裁决记录", "返照仪式必须由外部裁决者指定唯一原本", "历次记录都在宣判后出现十二条线路坍缩；镜子本身从未写下选择。", "终灯会称观察者只是在替自然规律签字。", "所谓自然排除，是有人坐下来把判断伪装成了事实。", "event", 4],
    ["zero-key-casting", "零号钥匙蜡型", "零号钥匙能打开所有返程门，却不决定谁可以通过", "十三处齿位分别响应一份签名，任何一处都没有优先级或真伪标记。", "钥匙管理处认为没有指定持有人的万能钥匙过于民主。", "出口一直足够，稀缺的是别人允许她们使用出口的意愿。", "object", 4],
    ["thirteen-signed-tickets", "十三张独立签名车票", "十三位诺亚分别写下名字、去向与公开边界", "签名笔压、记忆问题与对应路线互相验证，没有一张需要借用另一张的生活。", "城市愿意收下十三份票款，却只肯发放一个身份。", "证据没有选出原本，只证明十三个人都有资格自己回答。", "person", 5],
  ].map(([id, title, summary, detail, cityObjection, marginNote, type, chapter], index, all) => ({
    id,
    title,
    summary,
    detail,
    cityObjection: `${String(cityObjection).replace(/。$/, "，")}并建议先归入“重复旅客”临时卷宗。`,
    marginNote,
    type,
    chapter,
    relatedIds: index ? [String(all[index - 1][0])] : [],
  })),
  collectibles: [
    ["future-ticket", "明日车票", "ⅩⅢ", "collectible.chihaya-noa.future-ticket", "票面日期比现在晚一天，剪票孔却已经磨旧。", "纸纤维保存第十三次抵达的指纹和一条尚未出现的站台折线。", "十三号停用站台", "rare", 1],
    ["harbor-stamp", "雾港黄铜入境章", "⌾", "collectible.chihaya-noa.harbor-stamp", "柄部被十二种握法磨出重叠亮痕。", "印面日期轮曾连续十二夜自行回拨，留下真实而互斥的入境记录。", "雾港入境厅", "unusual", 1],
    ["paper-knot-spool", "纸结线轴", "⌁", "collectible.chihaya-noa.paper-knot-spool", "缠着窄纸带与旧酒红细线的小轴。", "十二种折痕各自对应一条被重置城市删去的安全路线。", "折返巷", "unusual", 2],
    ["bloodless-cutter", "无伤口裁纸刀", "╱", "collectible.chihaya-noa.bloodless-cutter", "刀尖留着暗红氧化痕，档案却找不到伤者。", "所谓血迹来自未成线路的红泥；持刀者用它割开封死地图，并未伤害另一位诺亚。", "十三号停用站台", "rare", 2],
    ["returning-mirror-shard", "返照镜碎片", "◇", "collectible.chihaya-noa.mirror-shard", "铜绿镜面不映面孔，只显出一间陌生房间。", "房间里的账单、纸结和窗外路线属于一位在未成线生活数月的诺亚。", "无编号镜片库", "rare", 3],
    ["mislabelled-plaque", "错译展签", "▤", "collectible.chihaya-noa.mislabelled-plaque", "黄铜牌上叠着多次刮改与无来源编号。", "牌背列出被抹去的原名，证明终灯会故意用虚构神秘主义掩盖器物来路。", "阿卡迪亚陈列厅", "unusual", 3],
    ["zero-key", "零号钥匙", "0", "collectible.chihaya-noa.zero-key", "齿位多得不像为一把锁制造。", "十三处齿位分别响应一位诺亚的签名，没有任何真身优先结构。", "零号回程门", "rare", 4],
    ["thirteen-ticket-clasp", "十三票黄铜夹", "≡", "collectible.chihaya-noa.ticket-clasp", "一只可以展开为十三格的薄黄铜票夹。", "每格保存独立签名、路线与沉默边界；合拢不会让任何一张覆盖另一张。", "观察者席", "rare", 4],
  ].map(([id, title, glyph, assetId, surfaceDescription, revealedDescription, district, rarity, chapter]) => ({
    id,
    title,
    glyph,
    assetId,
    surfaceDescription,
    revealedDescription,
    district,
    rarity,
    chapter,
  })),
});

const routeTemplates = [
  ["misfiled-registry", "market"],
  ["mislaid-consulate", "river"],
  ["afterlight-cartographers", "heights"],
] as const;

const chihayaNoaRoutes: RouteDirection[] = chihayaNoaCase.chapters.flatMap((chapter) =>
  chapter.choices.map((choice, index) => routeDirectionSchema.parse({
    id: `noa-night-${chapter.number}-${choice.id}`,
    chapter: chapter.number,
    choiceId: choice.id,
    dispatchTitle: choice.label,
    departureIntent: choice.note,
    destination: chapter.route[Math.min(index + 1, chapter.route.length - 1)],
    mapVariant: routeTemplates[index][1],
    routeNodes: [
      chapter.route[0],
      chapter.route[Math.min(index + 1, chapter.route.length - 1)],
      chapter.route[Math.min(index + 2, chapter.route.length - 1)],
      chapter.route.at(-1)!,
    ],
    events: chapter.events.map((event, eventIndex) =>
      eventIndex === index ? `${event} 林渡在对应路线旁系了一枚不替任何人编号的纸结。` : event),
    cityEncounter: `${chapter.cityAside} 林渡选择“${choice.label}”以后，沿途的镜面与门牌分别保留了一份措辞不同、人格完整的证词。`,
    returnLetter: `我按“${choice.label}”走完这一夜。${chapter.journal}`,
    societyId: routeTemplates[index][0],
    societyNotice: `你用“${choice.label}”处理了第 ${chapter.number} 夜的返照异议，没有把矛盾证词提前归类为赝品。`,
  })),
);

const chihayaNoaRelations = [
  {
    id: "noa-resets-left-travelers",
    clueIds: ["twelve-entry-stamps", "paper-knot-route"],
    statement: "每次城市重置都留下了一位真实旅行者",
    explanation: "十二份合法入境记录与十二套只能由亲自走过者留下的纸结路线逐层对应，证明旧诺亚不是一次性复制品。",
  },
  {
    id: "noa-unmade-lives-continue",
    clueIds: ["mirror-shard-memory", "unmade-address-book"],
    statement: "未成线中的诺亚仍拥有连续生活",
    explanation: "返照镜片中的房间细节与住址簿里的租住、借书和工作记录互相验证，旧版本在被主城排除后仍作为人生活。",
  },
  {
    id: "noa-observer-performs-erasure",
    clueIds: ["observer-chair-log", "thirteen-signed-tickets"],
    statement: "抹除来自观察者裁决，不来自镜子辨认真伪",
    explanation: "裁决记录显示每次线路坍缩都发生在观察者签字之后，而十三张签名票证明没有任何一位缺少独立人生。",
  },
].map((item) => evidenceRelationSchema.parse(item));

const chihayaNoaEndings: EndingEpilogue[] = [
  {
    id: "public",
    archiveLabel: "CASE CLOSED · THIRTEEN TESTIMONIES",
    title: "公开十三次抵达",
    theme: "让秘密仪式失去黑暗，也让十三个人同时承受白昼的注视。",
    result: "入境记录、返照镜与观察者协议被公开，终灯会失去隐秘裁决权；十三位诺亚却成为报纸、警方与收藏者争相辨认的对象。",
    detectiveLetter: "我们把十三份证词放在同一版晨报上，没有给任何一张加上“原本”或“副本”。终灯会无法再把裁决藏进地下站台，雾港也必须承认每一枚入境章都曾真实落下。公开带来了保护，也带来了成群追问谁最像“真正的千早诺亚”的目光。她们中的几位选择当众回答，几位从后门离开。证据终于属于白昼，但白昼仍需学习不把看见误写成拥有。",
    closingLine: "十三次抵达都被看见了，没有一次因此自动成为原本。",
  },
  {
    id: "protect",
    archiveLabel: "CASE CLOSED · MIRROR ARCHIVE SEALED",
    title: "封存返照档案",
    theme: "先让十三个人离开观察者的视线，再决定真相何时拥有地址。",
    result: "返照镜、住址簿和零号钥匙被分开封存，终灯会无法继续仪式；十三位诺亚获得隐蔽路线，但名字仍由事务所代为保管。",
    detectiveLetter: "我们拆开返照镜，把三块关键镜片分别交给不共享钥匙的人。十三个住址没有进入警局名单，零号门也只在当事人敲门时开启。这样做阻止了下一次裁决，却留下一个不舒服的问题：即使出于保护，档案仍由我们决定何时解封。诺亚接受这段喘息，但要求每封封套都预先写明归还日期。她说安全不能成为另一种没有期限的监护。",
    closingLine: "镜子被遮住了，名字仍在封套里等待回到本人手中。",
  },
  {
    id: "return",
    archiveLabel: "TRUE ENDING · NAMES RETURNED",
    title: "把名字还给十三个人",
    theme: "拒绝唯一原本，让每一段人生自己决定名字、出口与沉默。",
    result: "林渡离开观察者席，十三位诺亚逐一签署自己的名字、去向和公开边界；失去裁决者的仪式无法排除任何人，零号门为十三份决定分别开启。",
    detectiveLetter: "我们没有回答谁才是千早诺亚。十三张车票依次经过桌面：有人保留全名，有人加上自己选择的路线号，也有人只画了一枚纸结。每个人自己标记愿意公开的记忆与不愿交出的住址。观察者席空下来以后，返照镜第一次什么也没有删除。最后离开的诺亚把旅行箱靠在事务所墙边，说她不是谁的助手，只愿意继续与我们交换那些城市不肯承认的路线。",
    closingLine: "十三扇门各自通向清晨，没有一扇需要先证明别人不真实。",
  },
].map((item) => endingEpilogueSchema.parse(item));

const postcardTitles = ["十二次雾港抵达", "双版折返巷", "拱灯镜片库", "未成线住址", "十三扇清晨门"];
const chihayaNoaPostcards: JourneyPostcard[] = chihayaNoaCase.chapters.map((chapter, index) => journeyPostcardSchema.parse({
  id: `noa-postcard-${chapter.number}`,
  chapter: chapter.number,
  assetId: `case.chihaya-noa.postcard.0${chapter.number}`,
  title: postcardTitles[index],
  location: chapter.route.at(-1)!,
  cityRumor: chapter.cityAside,
  message: chapter.journal,
  preparationNotes: {
    "side-lamp": "侧照灯让镜面错位、票纸压痕与旧墨层依次显形，林渡因此没有把较浅的一层误写成赝品。",
    "flower-note": "花笺替一枚纸结保留了雨水气味，天亮后仍能分辨它来自哪一段真实走过的路线。",
    "tram-fare": "旧零钱被分成十三次投入站钟，没有购买优先次序，只替每一位迟到旅客保留开门声。",
  },
}));

const botanicalNames = ["入境叠影草", "折返纸结藤", "返照铜叶兰", "未成门牌蕨", "十三名晨花"];
const botanicalArchiveNames = ["Herba ingressus multiplex", "Vitis nodus reflexa", "Orchis speculum aeris", "Filix domicilium imperfectum", "Flos nomina tredecim"];
const chihayaNoaBotanicals: NightBotanical[] = chihayaNoaCase.chapters.map((chapter, index) => nightBotanicalSchema.parse({
  id: `noa-botanical-${chapter.number}`,
  chapter: chapter.number,
  assetId: `case.chihaya-noa.botanical.0${chapter.number}`,
  name: botanicalNames[index],
  archiveName: botanicalArchiveNames[index],
  district: chapter.route.at(-1)!,
  cityRumor: `据说它只在有人完整记录第 ${chapter.number} 夜、又拒绝删去矛盾版本时发芽；园艺处称同一株植物不应拥有多套经历。`,
  specimenNote: `根与种荚保留着“${chapter.title}”归来时的一层票纸、铜镜细线或纸结折痕。`,
  growthStages: {
    seed: "种核贴在报告纸上，外壳像一面尚未决定映出谁的暗铜镜。",
    sprout: "第一根深蓝嫩芽分成两道并行轮廓，没有一边压住另一边。",
    leaf: "纸结状叶片逐层展开，铜绿叶脉把不同路线保留为同一株的经历。",
    bloom: "十三枚细小暖色花芯围成开放圆环，中央不设置唯一原本的位置。",
  },
  qualityNotes: {
    interrupted: "植株较小但所有分枝完整；提前醒来没有抹去任何线索、名字或主线事实。",
    regular: "根系、纸结叶与铜色花芯稳定成形，保存一份清楚的标准标本。",
    restful: "外层多展开几道城市侧影，让标本更丰盛但不改变裁决资格。",
  },
}));

const watchIds: CityWatchId[] = ["lamplighting", "midnight", "last-watch", "daylight"];
const watchLabels = ["掌灯", "夜半", "末更", "白昼"];
const chihayaNoaWatchEchoes = chihayaNoaCase.chapters.flatMap((chapter) =>
  watchIds.map((watchId, index) => cityWatchEchoSchema.parse({
    chapter: chapter.number,
    watchId,
    scene: `${watchLabels[index]}时分，${chapter.route.at(-1)}把“${chapter.title}”叠成两层轻微错位的街景，每层窗口都有人回应。`,
    encounter: `一名没有编号的年轻旅客在第 ${chapter.number} 夜经过，请林渡别用“真假”替她缩短自我介绍。`,
    fieldNote: `${watchLabels[index]}改变了沿途遇见哪一段城市，却没有改变任何一位诺亚的存在资格；我只记录路线，不替路线挑选主人。`,
  })),
);

const chihayaNoaWakeEchoes = chihayaNoaCase.chapters.map((chapter) => wakeEchoSchema.parse({
  id: `noa-sleep-gap-0${chapter.number}`,
  chapter: chapter.number,
  title: `${chapter.title}之间的一次纸结回声`,
  sound: `你短暂醒来时，窗外传来纸带折叠的细响，十三号站钟从“${chapter.title}”里漏进一声回拨。`,
  glimpse: `林渡在错位街景里回头，看见第 ${chapter.number} 夜的两条路线并行抵达同一扇门，没有一条因此被删去。`,
  fieldNote: "这次醒转没有结束夜班。城市只趁你翻身时，把一段不肯接受编号的旅程夹进报告。",
}));

const chihayaNoaCharacters = [
  {
    id: "chihaya-noa",
    assetId: "case.chihaya-noa.character.noa",
    name: "千早诺亚",
    archiveName: "CHIHAYA NOA · THE THIRTEENTH ARRIVAL",
    role: "日本游学生与返照路线继承人",
    district: "雾港寄宿区",
    encounterChapter: 2,
    publicRumor: "她被报纸写成连续逃课、热衷地下仪式的外国狂信少女。",
    knownFact: "她能以纸结辨认被重置的道路，也保留部分旧版本记忆。",
    withheld: "她主动隐瞒了几段路线，因为不确定事务所是否已经成为终灯会需要的观察者。",
    quote: "请怀疑我，但别把怀疑写成替我决定。",
    revealClueIds: ["paper-knot-route", "mirror-shard-memory"],
  },
  {
    id: "iris-bell",
    assetId: "case.chihaya-noa.character.iris-bell",
    name: "艾瑞丝·贝尔",
    archiveName: "IRIS BELL · BOARDING HOUSE WITNESS",
    role: "寄宿学校学生与十三段记忆的保管人",
    district: "雾港寄宿区",
    encounterChapter: 2,
    publicRumor: "她被校方认为因过度同情同学而混淆了诺亚的入学日期。",
    knownFact: "她能分别说出十三位诺亚在宿舍留下的习惯与承诺。",
    withheld: "其中一位诺亚曾在自己的正式入境日期以前救过她，她因此拒绝协助校方拘束任何版本。",
    quote: "我记错日期的可能性很大，记错十三种道歉方式的可能性很小。",
    revealClueIds: ["thirteen-school-portraits", "twelve-entry-stamps"],
  },
  {
    id: "arthur-vale",
    assetId: "case.chihaya-noa.character.arthur-vale",
    name: "阿瑟·维尔",
    archiveName: "ARTHUR VALE · CURATOR OF FALSE ORIGINS",
    role: "阿卡迪亚东方艺术协会馆长",
    district: "拱灯学会街",
    encounterChapter: 3,
    publicRumor: "他以能把任何文化解释给雾灯城上流社会而闻名。",
    knownFact: "他主持终灯会的公开收藏与返照仪式编目。",
    withheld: "他知道大部分译注是拼凑物，却相信只要仪式有效，器物与人的原意都可以被牺牲。",
    quote: "准确当然值得尊重，但可用性才让收藏继续发光。",
    revealClueIds: ["ritual-mistranslation", "platform-blueprint"],
  },
  {
    id: "sixth-route-noa",
    assetId: "case.chihaya-noa.character.sixth-noa",
    name: "千早诺亚（第六条路线）",
    archiveName: "CHIHAYA NOA · SIXTH ROUTE CARTOGRAPHER",
    role: "未成线测绘员与旧版本住户",
    district: "未成线",
    encounterChapter: 4,
    publicRumor: "终灯会把她登记为返照镜上的一段顽固残影。",
    knownFact: "她在未成线生活数月，替后来抵达的人维护十二户住址和回程纸结。",
    withheld: "她已经不打算争夺“原本”身份，只要求主城承认自己有权选择一个不同名字。",
    quote: "我不需要赢过她，才能证明我付过这里的房租。",
    revealClueIds: ["unmade-address-book", "observer-chair-log"],
  },
].map((item) => caseCharacterSchema.parse(item));

const chihayaNoaDistricts = [
  {
    id: "mist-harbor-boarding-quarter",
    assetId: "case.chihaya-noa.district.mist-harbor",
    name: "雾港寄宿区",
    archiveName: "DISTRICT 01 · MIST-HARBOUR BOARDING QUARTER",
    subtitle: "入境厅、女校与停用站台共享一套不肯对齐的钟",
    introducedChapter: 1,
    publicVersion: "雾港署称外国学生只入境一次，寄宿学校也只保存一份有效学籍。",
    cityRule: "每次抵达都要盖章；若同一个名字再次出现，先检查城市是否仍是昨天那一座。",
    landmarks: ["十三号停用站台", "寄宿学校旧档室", "雾港入境厅"],
  },
  {
    id: "archlight-society-row",
    assetId: "case.chihaya-noa.district.archlight-row",
    name: "拱灯学会街",
    archiveName: "DISTRICT 02 · ARCHLIGHT SOCIETY ROW",
    subtitle: "收藏馆把来路刮去以后，仍要求器物表演一种方便理解的神秘",
    introducedChapter: 3,
    publicVersion: "学会街自称只从事合法研究、舞台教育与跨文化收藏。",
    cityRule: "任何没有来源的展签都能打开一扇库门，也会在门后留下一个被抹掉的人。",
    landmarks: ["阿卡迪亚陈列厅", "无编号镜片库", "地下线路绘图室"],
  },
  {
    id: "unmade-line",
    assetId: "case.chihaya-noa.district.unmade-line",
    name: "未成线",
    archiveName: "DISTRICT 03 · THE UNMADE LINE",
    subtitle: "被重置的城市版本在铁路尽头继续收取房租",
    introducedChapter: 4,
    publicVersion: "铁路档案称这条支线从未建成，因此不可能存在站台、住户或返程门。",
    cityRule: "门牌不等待主城承认；有人持续敲门、借书与修屋顶的地方就已经形成地址。",
    landmarks: ["十二户折返公寓", "观察者席", "零号回程门"],
  },
].map((item) => cityDistrictSchema.parse(item));

export const chihayaNoaCampaign = defineCampaign({
  id: CHIHAYA_NOA_CAMPAIGN_ID,
  version: 1,
  case: chihayaNoaCase,
  routes: chihayaNoaRoutes,
  relations: chihayaNoaRelations,
  endings: chihayaNoaEndings,
  postcards: chihayaNoaPostcards,
  botanicals: chihayaNoaBotanicals,
  watchEchoes: chihayaNoaWatchEchoes,
  wakeEchoes: chihayaNoaWakeEchoes,
  characters: chihayaNoaCharacters,
  districts: chihayaNoaDistricts,
  rules: {
    trueEndingId: "return",
    requiredClueCount: chihayaNoaCase.clues.length,
    requiredCollectibleCount: 7,
    requiredRelationCount: chihayaNoaRelations.length,
  },
  presentation: {
    archiveNumber: "004",
    teaser: "同一名少女连续十二天抵达雾灯城，第十三张车票却要到明天才发售。",
    description: "沿入境章、纸结与返照镜走进被删除的城市，把十三段人生的命名权还给本人。",
    cityName: "雾灯城",
    detectiveName: "林渡",
    heroAssetId: "case.chihaya-noa.header.handoff",
    nightAssetId: "case.chihaya-noa.header.night",
    morningAssetId: "case.chihaya-noa.header.morning",
    endingAssetId: "case.chihaya-noa.ending.tableau",
    nightSealAssetIds: chihayaNoaCase.chapters.map((chapter) => `case.chihaya-noa.night-seal.0${chapter.number}`),
    endingQuestion: "十三段人生都能自证以后，谁还有资格指定唯一原本？",
    endingPrompt: "入境记录、未成线住址与观察者协议都已查明。最后要决定的是公开、保护，还是把名字、出口与沉默权逐一交还。",
    closingRefrain: "天已经亮了，十三扇门仍分别通向自己的清晨。",
  },
});
