import {
  caseCharacterSchema,
  caseSchema,
  cityDistrictSchema,
  cityWatchEchoSchema,
  endingEpilogueSchema,
  evidenceSynthesisSchema,
  journeyPostcardSchema,
  nightBotanicalSchema,
  routeDirectionSchema,
  wakeEchoSchema,
  type CityWatchId,
  type EndingEpilogue,
  type JourneyPostcard,
  type NightBotanical,
  type RouteDirection,
} from "@/src/lib/game-engine/schema";
import { defineCampaign } from "./types";

export const FOG_WITHOUT_WOLVES_CAMPAIGN_ID = "case-006";

const fogWithoutWolvesCase = caseSchema.parse({
  id: FOG_WITHOUT_WOLVES_CAMPAIGN_ID,
  title: "雾中无狼",
  englishTitle: "No Wolves in the Fog",
  chapters: [
    {
      number: 1,
      title: "没有尸体的谋杀现场",
      subtitle: "两封相反遗书拥有同一笔迹，一具尸体却在空房间里投出两道影子。",
      cityAside: "白钟区的钟都停在 23:43，巡警坚持那只是整条街同时忘记上弦。",
      question: "谁在一间没有尸体的房间里，同时杀死了两个版本的人？",
      choices: [
        { id: "room", label: "复原白钟区双影房间", note: "先让灯位、血迹和空墙各自作证。" },
        { id: "wills", label: "拆验方向相反的双面遗书", note: "核对纸张、墨水与每一道笔压。" },
        { id: "clocks", label: "追查全街停在 23:43 的钟", note: "不要把共同停摆当成巧合。" },
      ],
      clueIds: ["stopped-clocks-2343", "twin-wills", "double-shadow", "wall-blood-name"],
      collectibleIds: ["bloodied-bell", "white-chalk", "twin-will-folder"],
      route: ["夜班事务所", "白钟区双影房", "停摆钟表铺", "临时验尸档案桌"],
      events: [
        "23:43 — 白钟区所有秒针同时停在同一个缺口前。",
        "00:56 — 两封遗书在侧光下显出完全相同的笔压。",
        "02:14 — 空床旁的单一灯源投出两道不相交的人影。",
        "03:37 — 拉普拉斯刺向空墙，特蕾莎同时喊出一个陌生名字。",
        "05:06 — 墙内传来一声惨叫，暗红血迹沿不存在的门框渗出。",
      ],
      journal: "第三名死者的住宅没有尸体，只有两封彼此指控的遗书和一道无法由房间灯位形成的第二影子。拉普拉斯听见墙内残留的呼救，特蕾莎在她开口前说出死者从未登记过的名字。她们没有同行，也没有接受我们的指挥，却仍完成了暮钟馆训练出的旧分工。白粉笔不是凶手签名，而是在要求一个外部见证者把矛盾压成唯一事实。",
      contradiction: "如果房间只发生过一次死亡，为什么遗书、影子和墙内血迹都保存着两套完整因果？",
    },
    {
      number: 2,
      title: "身体记得怎样猎杀",
      subtitle: "停业剧院的无舌铜钟下，两名旧猎手拒绝让熟练等同于愿意回去。",
      cityAside: "圣维斯帕剧院没有演出许可证，却仍在每个雨夜排练一场听不见的追逐。",
      question: "拉普拉斯与特蕾莎为何在分开七年后仍能完成同一套异常猎杀？",
      choices: [
        { id: "stage", label: "检查无舌铜钟与舞台声场", note: "让回声位置从机械结构里显形。" },
        { id: "score", label: "重排回声猎犬声学谱", note: "只辨认训练方式，不让猎犬获得形体。" },
        { id: "protocol", label: "拆读相反证人训练协议", note: "区分身体记忆与当事人的当前意愿。" },
      ],
      clueIds: ["echo-hound-score", "hunter-pair-protocol"],
      collectibleIds: ["tongueless-bell"],
      route: ["圣维斯帕剧院街", "废弃排练舞台", "反向留声机室", "声学设备夹层"],
      events: [
        "00:11 — 无舌铜钟在没人触碰时发出一段只有蜡筒能记录的振动。",
        "01:29 — 林渡调整侧台号角，让拉普拉斯从混响中指出无形目标。",
        "02:42 — 特蕾莎说出训练手册禁止公开的猎犬名称。",
        "03:58 — 两人同时退到彼此盲区之外，拒绝恢复旧站位。",
        "05:09 — 艾达·莫恩从道具库交出分藏七年的两把播放钥匙。",
      ],
      journal: "剧院地下保存着暮钟馆反向留声机、临终蜡筒和一口没有钟舌的实验铜钟。声学谱证明拉普拉斯负责从混乱中听见异常，特蕾莎负责为异常命名；这套分工已经被训练进反射动作。林渡只调度声源，没有把任何人推回指定位置。两人仍然擅长合作，但她们都明确表示：熟练不是同意，救过彼此也不是继续服役的契约。",
      contradiction: "如果她们只是重新成为旧搭档，为什么每一次成功配合后都主动打乱暮钟馆规定的站位？",
    },
    {
      number: 3,
      title: "同一声钟的两只蜡筒",
      subtitle: "一只记录她找到出口，另一只记录她请求被留下；两份录音都没有剪接。",
      cityAside: "雾灯城的声学档案允许一段录音有噪点，不允许同一秒钟拥有两种真实结局。",
      question: "七年前暮钟响起前，拉普拉斯究竟请求特蕾莎做了什么？",
      choices: [
        { id: "laplace", label: "校准拉普拉斯蜡筒的出口回声", note: "先听完她请求不要敲钟的版本。" },
        { id: "theresa", label: "校准特蕾莎蜡筒的断裂语言", note: "再听完她请求阻止自己离开的版本。" },
        { id: "waveform", label: "叠合两份录音的背景声纹", note: "只比较可验证的石屑、哭声和钟波。" },
      ],
      clueIds: ["laplace-cylinder", "theresa-cylinder"],
      collectibleIds: ["paired-cylinders"],
      route: ["圣维斯帕剧院", "双钥匙蜡筒库", "回声调谐台", "旧暮钟波形室"],
      events: [
        "00:43 — 第一只蜡筒录到拉普拉斯找到出口并请求不要敲钟。",
        "01:35 — 第二只蜡筒录到她失去完整语言并请求切断联系。",
        "02:48 — 两段哭声、石屑坠落和远钟波形逐帧完全重合。",
        "04:03 — 调谐台在两条同样清晰的声纹之间拒绝给出真伪指示。",
        "05:12 — 特蕾莎第一次承认，她害怕的不是记错，而是两段都没有记错。",
      ],
      journal: "艾达把播放钥匙分开藏匿，是为了阻止暮钟馆只公开一只蜡筒。拉普拉斯的录音里，她找到出口并不断请求特蕾莎不要敲钟；特蕾莎的录音里，她已经无法完整说话，请求对方阻止自己出去。两段背景声纹属于同一个时刻，均无拼接。回声调谐台只能帮助我们对齐频段，不能替任何人判定唯一版本。暮钟真正制造的是两段都能独立成立的现实。",
      contradiction: "当两份录音共享同一秒钟的所有背景细节时，哪一项证据还能允许我们把其中一份降格为谎言？",
    },
    {
      number: 4,
      title: "被登记册剪掉的一分钟",
      subtitle: "缺失的一分钟不是空白，而是暮钟让第三见证者进入两段现实的门。",
      cityAside: "计时署保存每一秒的责任人，唯独把 23:43 之后的一分钟归档为从未发生。",
      question: "暮钟馆为什么需要一名不在七年前现场的第三见证者？",
      choices: [
        { id: "register", label: "核对失去一分钟的市政登记册", note: "沿怀表与钟盘寻找被制度剪掉的入口。" },
        { id: "handwriting", label: "追查日志里出现的第二种笔迹", note: "辨认谁一直替见证者预写结论。" },
        { id: "form", label: "拆解最终见证表的空白裁决格", note: "找出仪式真正等待的那次签名。" },
      ],
      clueIds: ["mismatched-gloves", "missing-minute-register", "second-handwriting-log", "final-witness-form"],
      collectibleIds: ["mismatched-gloves", "split-minute-watch", "unsigned-report"],
      route: ["白钟区", "市政计时档案室", "孤儿院旧钟房", "最终见证表保管柜"],
      events: [
        "00:17 — 一排怀表都在同一处缺失整整六十秒的刻度。",
        "01:44 — 日志后半出现第二种笔迹，内容却早于书写者出生。",
        "02:59 — 不成对手套分别保留拉普拉斯与特蕾莎的旧训练磨痕。",
        "04:10 — 最终见证表只允许勾选一个真实版本。",
        "05:15 — 费利克斯承认暮钟不在乎勾哪一格，只在乎有人愿意删掉另一格。",
      ],
      journal: "市政登记册把 23:43 之后的一分钟整齐剪掉，所有受暮钟影响的怀表也留下同样缺口。第二种笔迹不是附身，而是历代第三见证者预写的行政语气。最终表格要求未参与旧案的人选择唯一版本；一旦签名，另一个人便会被现实当作污染残余删除，钟后聆听者则从被删除的矛盾中取得入口。费利克斯不关心谁正确，他只需要我们相信真相必须唯一。",
      contradiction: "如果暮钟能自行辨认真相，仪式为什么非要等待一个外部人填完空白裁决格？",
    },
    {
      number: 5,
      title: "第十三声钟",
      subtitle: "巨钟等待一份唯一报告，两名旧猎手却第一次交换了被训练好的位置。",
      cityAside: "城市愿意容纳十二声报时；第十三声只在有人准备删去另一段人生时出现。",
      question: "证据应当公开、封存，还是拒绝替两段真实记忆指定唯一主人？",
      choices: [
        { id: "publish", label: "提交特蕾莎的唯一官方版本", note: "关闭这次入口，也让拉普拉斯承担被删除的代价。" },
        { id: "protect", label: "切断两人的名字与共同记忆", note: "用彻底遗忘换取一段可靠的安全。" },
        { id: "return", label: "拒绝唯一报告并交换猎手角色", note: "只确认两段真实，把命名与聆听还给当事人。" },
      ],
      clueIds: ["final-witness-form"],
      collectibleIds: ["unsigned-report"],
      route: ["地图外拆除区", "暮钟工场", "第十三声维护桥", "夜班事务所归档桌"],
      events: [
        "00:43 — 巨钟在没有钟舌的情况下连续产生十二圈压力波。",
        "01:51 — 费利克斯把最终报告推到第三见证者的位置。",
        "03:06 — 拉普拉斯替特蕾莎说出名字，特蕾莎第一次只负责聆听。",
        "04:22 — 固定角色被交换以后，第十三声找不到进入现实的方向。",
        "05:00 — 未签报告留在桌上，两只不成对手套被各自取回。",
      ],
      journal: "暮钟馆把拉普拉斯和特蕾莎训练成一对相反证人，再要求第三个人把她们压成唯一结论。公开特蕾莎的版本可以暂时维持制度，却会让拉普拉斯从档案中消失；切断名字能安全封闭裂隙，也会删除两人的共同历史。证据最完整的方向是不签那份唯一报告：拉普拉斯替特蕾莎命名，特蕾莎替拉普拉斯聆听，角色交换以后，钟后聆听者无法再把她们固定成入口。",
      contradiction: "当两段记忆与两个当前人格都真实存在，调查者还有什么资格用整齐的报告删除其中一个？",
    },
  ],
  clues: [
    ["stopped-clocks-2343", "停在 23:43 的整街钟表", "白钟区所有钟表在同一秒停摆", "机械结构与上弦时间不同，停针位置却共同缺失下一分钟。", "计时署称整街钟表可能同时遇到潮气。", "共同停摆不是背景气氛，而是现实被切开时留下的同步伤口。", "event", 1],
    ["twin-wills", "同笔迹的相反遗书", "两份遗书分别指控拉普拉斯与特蕾莎", "纸张、墨水、笔压和停顿完全一致，内容却描述相反的死亡经过。", "警方建议挑选更符合常理的一封存档。", "两份文字都由同一只手在两个成立的事件里写下。", "object", 1],
    ["double-shadow", "单灯下的双重影子", "一具缺席的身体留下两道人影", "两道影子分别响应房间中两个互斥灯位，均能和遗书叙述对应。", "巡警把第二道影子归因于窗外车灯。", "光线保存了同一房间曾同时容纳两种事件的事实。", "contradiction", 1],
    ["wall-blood-name", "墙中鲜血与陌生名字", "拉普拉斯定位、特蕾莎命名后异常才获得现实位置", "空墙在名字被说出后渗血，声源与登记失踪者的旧房间重合。", "房东称老墙渗水总会形成近似名字的形状。", "她们的旧分工仍能让回声获得可调查的位置。", "place", 1],
    ["echo-hound-score", "回声猎犬声学谱", "剧院设备记录出只在命名后显形的异常追逐", "声谱把定位与命名分成两条互相依赖的操作线，和两人的身体反应一致。", "剧院理事会称声谱只是废演出的实验音乐。", "训练塑造了动作，却没有替当前的她们续签同意。", "event", 2],
    ["hunter-pair-protocol", "相反证人训练协议", "暮钟馆把聆听者与命名者训练为固定搭档", "协议规定拉普拉斯只能定位、特蕾莎只能命名，并禁止交换位置。", "旧结社档案把强制分工写成天赋互补。", "禁止交换说明角色本身就是维持仪式的结构。", "person", 2],
    ["laplace-cylinder", "拉普拉斯留声筒", "她找到出口并请求特蕾莎不要敲钟", "哭声、石屑和远钟波形连续完整，没有剪接或后期覆盖。", "声学署认为濒危证词不能代表稳定人格。", "这段记忆真实发生，也塑造了七年后的拉普拉斯。", "object", 3],
    ["theresa-cylinder", "特蕾莎留声筒", "拉普拉斯请求阻止自己离开，特蕾莎答应记住她", "背景声纹与另一只蜡筒逐帧重合，同样没有剪接。", "声学署建议将互斥录音判为设备串音。", "这段记忆同样真实，也塑造了七年后的特蕾莎。", "object", 3],
    ["mismatched-gloves", "不成对的旧手套", "一深一浅两只手套保存交换训练位置的磨痕", "磨损证明两人曾私下练习过彼此的角色，暮钟馆随后封存了装备。", "馆藏清单称不成对物件不具备完整证据价值。", "她们从前就知道角色可以交换，只是被制度禁止承认。", "object", 4],
    ["missing-minute-register", "缺失一分钟的登记册", "所有暮钟事件都从市政时间里失去同一段六十秒", "缺口不是空页；订线、页码与校时章都绕开了那一分钟。", "计时署称没有被记录的时间不产生法律后果。", "被剪掉的一分钟是第三见证者进入分裂现实的门。", "event", 4],
    ["second-handwriting-log", "日志里的第二种笔迹", "历代见证日志都被另一种行政笔迹提前补完", "笔迹跨越数十年保持相同措辞，只在第三见证者接触表格后出现。", "档案处称统一措辞有助于降低公众理解成本。", "仪式在训练见证者怎样把删除写成归档。", "person", 4],
    ["final-witness-form", "最终见证表", "表格只允许从两段真实记忆中勾选一个", "无论选择哪一格，另一格都会被标为污染残余；空白本身不会触发仪式。", "暮钟馆称唯一结论是保护现实所需的行政卫生。", "聆听者需要的不是正确答案，而是第三个人同意删除矛盾。", "contradiction", 4],
  ].map(([id, title, summary, detail, cityObjection, marginNote, type, chapter], index, all) => ({
    id,
    title,
    summary,
    detail,
    cityObjection: `${String(cityObjection).replace(/。$/, "，")}并建议归入“钟表潮损”临时卷宗。`,
    marginNote,
    type,
    chapter,
    relatedIds: index ? [String(all[index - 1][0])] : [],
  })),
  collectibles: [
    ["bloodied-bell", "染血旧银铃", "⌁", "collectible.fog-without-wolves.bloodied-bell", "铃口没有钟舌，边缘留着暗红污迹。", "污迹来自七年前两段现实的共同边界，银铃从未真正发声。", "夜班事务所", "rare", 1],
    ["white-chalk", "白粉笔残段", "○", "collectible.fog-without-wolves.white-chalk", "短小粉笔在纸面留下近乎闭合的圆。", "粉尘配方属于暮钟馆；字迹是写给钟后聆听者的祷文。", "白钟区双影房", "unusual", 1],
    ["twin-will-folder", "双面遗书档案夹", "⇄", "collectible.fog-without-wolves.twin-will-folder", "旧酒红细绳束着两叠厚度相同的文件。", "两份遗书共享纸张与笔迹，却分别属于两次都发生过的死亡。", "临时验尸档案桌", "rare", 1],
    ["tongueless-bell", "剧院无舌铜钟", "∩", "collectible.fog-without-wolves.tongueless-bell", "铜钟内部空缺，表面裂纹沿声场方向延伸。", "它不制造声音，只把暮钟馆训练留下的动作放大成可记录振动。", "圣维斯帕剧院", "unusual", 2],
    ["paired-cylinders", "成对证词蜡筒", "≋", "collectible.fog-without-wolves.paired-cylinders", "两只蜡筒并排躺在深蓝绒盘中。", "不同语言共享同一段背景波形，证明一声钟分裂出两段真实事件。", "双钥匙蜡筒库", "rare", 3],
    ["mismatched-gloves", "不成对猎手手套", "◐", "collectible.fog-without-wolves.mismatched-gloves", "一只深色右手套与一只浅色左手套被放在一起。", "交换方向的磨痕证明两人能够跨越暮钟馆规定的固定角色。", "孤儿院旧钟房", "unusual", 4],
    ["split-minute-watch", "失去一分钟的怀表", "◴", "collectible.fog-without-wolves.split-minute-watch", "银怀表的分钟环缺失一段，齿轮仍能越过空白。", "六十秒缺口与历次见证登记完全对应，是进入分裂现实的制度门。", "市政计时档案室", "rare", 4],
    ["unsigned-report", "未签最终报告", "□", "collectible.fog-without-wolves.unsigned-report", "黄铜夹固定着无字封蜡与空白签名线。", "只有签名和唯一勾选会触发删除；拒绝提交本身是一种可执行决定。", "最终见证表保管柜", "rare", 4],
  ].map(([id, title, glyph, assetId, surfaceDescription, revealedDescription, district, rarity, chapter]) => ({
    id,
    title,
    glyph,
    assetId,
    surfaceDescription,
    revealedDescription,
    district,
    rarity,
    chapter,
  })),
});

const routeTemplates = [
  ["misfiled-registry", "market"],
  ["mislaid-consulate", "river"],
  ["afterlight-cartographers", "heights"],
] as const;

const fogWithoutWolvesRoutes: RouteDirection[] = fogWithoutWolvesCase.chapters.flatMap((chapter) =>
  chapter.choices.map((choice, index) => routeDirectionSchema.parse({
    id: `fog-night-${chapter.number}-${choice.id}`,
    chapter: chapter.number,
    choiceId: choice.id,
    dispatchTitle: choice.label,
    departureIntent: choice.note,
    destination: chapter.route[Math.min(index + 1, chapter.route.length - 1)],
    mapVariant: routeTemplates[index][1],
    routeNodes: [
      chapter.route[0],
      chapter.route[Math.min(index + 1, chapter.route.length - 1)],
      chapter.route[Math.min(index + 2, chapter.route.length - 1)],
      chapter.route.at(-1)!,
    ],
    events: chapter.events.map((event, eventIndex) =>
      eventIndex === index ? `${event} 林渡把这一段回声单独封存，没有覆盖另一份记录。` : event),
    cityEncounter: `${chapter.cityAside} 林渡选择“${choice.label}”以后，只记录可验证的声源、笔迹与时间，不替当事人恢复暮钟馆站位。`,
    returnLetter: `我按“${choice.label}”走完这一夜。${chapter.journal}`,
    societyId: routeTemplates[index][0],
    societyNotice: `你用“${choice.label}”处理了第 ${chapter.number} 夜的矛盾证词，没有把熟练配合误写成继续服从。`,
  })),
);

const fogWithoutWolvesSyntheses = [
  {
    id: "fog-one-room-two-events",
    inputIds: ["twin-wills", "double-shadow"],
    title: "同一房间同时保存两起完整事件",
    explanation: "同笔迹遗书与双重光影分别对应两套自洽因果，证明现场不是一份真相和一份伪造。",
  },
  {
    id: "fog-one-bell-split-event",
    inputIds: ["laplace-cylinder", "theresa-cylinder"],
    title: "同一声暮钟分裂出两段真实记忆",
    explanation: "两只蜡筒的背景声纹逐帧重合，矛盾请求却都连续无剪接，只能来自同一事件分裂后的两段现实。",
  },
  {
    id: "fog-missing-minute-is-door",
    inputIds: ["stopped-clocks-2343", "missing-minute-register"],
    title: "缺失的一分钟是见证者入口",
    explanation: "整街停钟与市政登记缺口共享同一段六十秒，证明空白是被维护的仪式通道而非计时故障。",
  },
  {
    id: "fog-third-witness-is-trigger",
    inputIds: ["fog-one-bell-split-event", "final-witness-form"],
    title: "第三见证者的唯一裁决才会触发删除",
    explanation: "两段记忆本可并存，最终表格却只在外部人勾选一个版本后删除另一个；见证不是核验，而是仪式开关。",
  },
  {
    id: "fog-roles-can-be-exchanged",
    inputIds: ["hunter-pair-protocol", "mismatched-gloves"],
    title: "聆听与命名不是不可交换的天赋",
    explanation: "训练协议明令禁止交换，手套磨痕却证明两人早已私下跨越固定站位；角色本身才是暮钟维持入口的结构。",
  },
].map((item) => evidenceSynthesisSchema.parse(item));

const fogWithoutWolvesEndings: EndingEpilogue[] = [
  {
    id: "public",
    archiveLabel: "CASE CLOSED · ONE VERSION FILED",
    title: "提交唯一官方版本",
    theme: "让现实恢复整齐，也让另一段人生独自支付整理费用。",
    result: "事务所把特蕾莎的记忆写成官方事实，暮钟入口暂时关闭；拉普拉斯被归为污染残余，逐渐从现实和档案中消失。",
    detectiveLetter: "我们在最终表格上勾选了特蕾莎的版本。钟声停下，白钟区所有表重新走动，新闻只需刊登一段可以理解的旧案。拉普拉斯先从照片里失去轮廓，再从旁人的句子里失去主语。特蕾莎保住七年来建立的生活，却再次看着沉默替她完成选择。暮钟馆没有在今晚迎来聆听者，但它最重要的制度仍被保留：只要事实足够矛盾，就让其中一个人承担被整理掉的代价。",
    closingLine: "城市得到一份整齐报告，雾里少了一个仍然真实的人。",
  },
  {
    id: "protect",
    archiveLabel: "CASE CLOSED · NAMES SEVERED",
    title: "切断彼此的名字",
    theme: "用可靠的遗忘保护现实，也把共同历史连同伤害一起封存。",
    result: "拉普拉斯亲手切断特蕾莎为她留下的名字，裂隙安全关闭；两人失去关于彼此的一切记忆。",
    detectiveLetter: "特蕾莎最后一次说出拉普拉斯的名字，拉普拉斯沿声音切断了它。巨钟立刻失去压力，蜡筒表面也恢复成无意义的细纹。数周后，她们在夜间货运站擦肩，同时为一种没有来源的悲伤停步。没有人被删除，暮钟也再没有入口；代价是两个人无法再判断自己的习惯、恐惧和勇气有多少来自那段共同生活。安全是真实的，失去同样真实。",
    closingLine: "她们都走进清晨，却再也不知道为何会为陌生人回头。",
  },
  {
    id: "return",
    archiveLabel: "TRUE ENDING · NO WOLVES IN THE FOG",
    title: "雾中无狼",
    theme: "拒绝唯一真相，把聆听、命名与当前选择还给两个活着的人。",
    result: "事务所拒绝签署唯一报告；拉普拉斯替特蕾莎命名，特蕾莎替拉普拉斯聆听，角色交换后钟后聆听者失去入口。",
    detectiveLetter: "我们只在报告上写下两件事：两段记忆都真实发生，两位当事人都拥有现在的选择。拉普拉斯第一次替特蕾莎说出一个不属于暮钟馆的名字，特蕾莎则闭上眼，替她听完那段没有命令的回声。第十三声钟找不到固定位置，最终消散在雾里。她们没有恢复旧关系，也没有许诺和解，只停止允许任何组织把理解彼此定义成猎犬的义务。",
    closingLine: "雾里从来没有狼，只有被训练成猎犬的人终于换回自己的位置。",
  },
].map((item) => endingEpilogueSchema.parse(item));

const postcardTitles = ["白钟区双影房", "圣维斯帕空舞台", "双钥匙蜡筒库", "失分钟计时档案", "第十三声钟工场"];
const fogWithoutWolvesPostcards: JourneyPostcard[] = fogWithoutWolvesCase.chapters.map((chapter, index) => journeyPostcardSchema.parse({
  id: `fog-postcard-${chapter.number}`,
  chapter: chapter.number,
  assetId: `case.fog-without-wolves.postcard.0${chapter.number}`,
  title: postcardTitles[index],
  location: chapter.route.at(-1)!,
  cityRumor: chapter.cityAside,
  message: chapter.journal,
  preparationNotes: {
    "side-lamp": "侧照灯把重叠笔压、双重影子与蜡筒声纹分层显出，没有强迫它们合成单一版本。",
    "flower-note": "花笺吸附了白粉笔与钟房灰尘，天亮后仍能区分祷文、机械磨损和当事人的痕迹。",
    "tram-fare": "旧零钱让林渡在三处档案点之间多走一段支线，只增加旁证，不改变核心事实或结局资格。",
  },
}));

const botanicalNames = ["钟尘蕨", "帷刺藤", "双录芦", "失分钟花", "见证钟兰"];
const botanicalArchiveNames = ["Filix pulvis campanae", "Vitis velarium spina", "Calamus cylindri gemini", "Flos minutum absentem", "Orchis testis campana"];
const fogWithoutWolvesBotanicals: NightBotanical[] = fogWithoutWolvesCase.chapters.map((chapter, index) => nightBotanicalSchema.parse({
  id: `fog-botanical-${chapter.number}`,
  chapter: chapter.number,
  assetId: `case.fog-without-wolves.botanical.0${chapter.number}`,
  name: botanicalNames[index],
  archiveName: botanicalArchiveNames[index],
  district: chapter.route.at(-1)!,
  cityRumor: `据说它只在有人记录第 ${chapter.number} 夜的两份证词、又拒绝删去其中一份时发芽；园艺处称植物不应参与事实核验。`,
  specimenNote: `根与花冠保存着“${chapter.title}”归来时的一层白粉笔、蜡筒细纹或失分钟刻度。`,
  growthStages: {
    seed: "暗色种核外壳像一枚没有钟舌的小钟，贴在暖纸上保持沉默。",
    sprout: "两道深浅不同的嫩芽并行长出，没有一边抢占另一边的根。",
    leaf: "叶脉分成聆听与命名两路，在茎部交换位置后仍能继续生长。",
    bloom: "花冠围住一块开放空白，中心没有等待被命名的怪物或唯一答案。",
  },
  qualityNotes: {
    interrupted: "植株较小但两路叶脉完整；提前醒来不会删除任何线索、人物或主线事实。",
    regular: "根系、钟形花冠与失刻叶缘稳定成形，保存一份清楚的标准标本。",
    restful: "外层多展开几圈细密声纹，让标本更丰盛但不改变推论或结局资格。",
  },
}));

const watchIds: CityWatchId[] = ["lamplighting", "midnight", "last-watch", "daylight"];
const watchLabels = ["掌灯", "夜半", "末更", "白昼"];
const fogWithoutWolvesWatchEchoes = fogWithoutWolvesCase.chapters.flatMap((chapter) =>
  watchIds.map((watchId, index) => cityWatchEchoSchema.parse({
    chapter: chapter.number,
    watchId,
    scene: `${watchLabels[index]}时分，${chapter.route.at(-1)}把“${chapter.title}”送进两层轻微错位的声场，每一层都有独立回声。`,
    encounter: `一名夜间抄表员经过第 ${chapter.number} 夜的路线，请林渡不要为了准时报时而补写缺失的一分钟。`,
    fieldNote: `${watchLabels[index]}只改变今晚遇见的旁证与城市侧影，不改变核心线索、当事人选择或任何结局资格。`,
  })),
);

const fogWithoutWolvesWakeEchoes = fogWithoutWolvesCase.chapters.map((chapter) => wakeEchoSchema.parse({
  id: `fog-sleep-gap-0${chapter.number}`,
  chapter: chapter.number,
  title: `${chapter.title}之间的一次无舌钟回声`,
  sound: `你短暂醒来时，窗外没有钟声，只有两段呼吸隔着“${chapter.title}”保持同样清楚。`,
  glimpse: `林渡在第 ${chapter.number} 夜的错位街景里停步，让拉普拉斯与特蕾莎分别走完自己的路线，没有把任何人叫回旧站位。`,
  fieldNote: "这次醒转没有结束夜班。它只增加一段城市回声，不改变调查方向、主线线索或五夜进度。",
}));

const fogWithoutWolvesCharacters = [
  {
    id: "laplace",
    assetId: "case.fog-without-wolves.character.laplace",
    name: "拉普拉斯",
    archiveName: "LAPLACE · LISTENER OF RESIDUAL EVENTS",
    role: "大陆旅行者与暮钟馆前聆听者",
    district: "白钟区",
    encounterChapter: 2,
    publicRumor: "她被警局描述成危险、轻佻且总在谋杀发生前出现的持刀者。",
    knownFact: "她能听见事件留下的异常回声，并准确定位没有形体的声源。",
    withheld: "她寻找特蕾莎既因被抛弃的愤怒，也因为特蕾莎曾是唯一能压住回声的安静。",
    quote: "我可以接受她选择离开，不能接受你们替她说那从未发生。",
    revealClueIds: ["wall-blood-name", "laplace-cylinder"],
  },
  {
    id: "theresa-vale",
    assetId: "case.fog-without-wolves.character.theresa",
    name: "特蕾莎·维尔",
    archiveName: "THERESA VALE · NIGHT FREIGHT DISPATCHER",
    role: "夜间货运调度员与暮钟馆前命名者",
    district: "白钟区",
    encounterChapter: 2,
    publicRumor: "她被邻居视为安静可靠、从未离开夜运调度室的普通职员。",
    knownFact: "她曾烧毁暮钟馆，也能为异常说出使其获得现实位置的名字。",
    withheld: "她害怕的不是拉普拉斯报复，而是两人重新完美配合以后再次成为入口。",
    quote: "记得怎样合作，不等于我们仍欠那个组织一次合作。",
    revealClueIds: ["hunter-pair-protocol", "theresa-cylinder"],
  },
  {
    id: "ada-morne",
    assetId: "case.fog-without-wolves.character.ada",
    name: "艾达·莫恩",
    archiveName: "ADA MORNE · LAST ACOUSTIC ENGINEER",
    role: "圣维斯帕剧院最后一任声学技师",
    district: "圣维斯帕剧院街",
    encounterChapter: 2,
    publicRumor: "剧院理事会称她因年老而把两次排练错误记成同一晚。",
    knownFact: "她保存两只原始蜡筒，并把播放钥匙分别藏在两个互不通信的地方。",
    withheld: "她早已听出两份录音都真实，分藏钥匙是为了阻止任何机构只公开一个版本。",
    quote: "机器可以失真，但它不会为了让报告好看而主动删除另一只筒。",
    revealClueIds: ["echo-hound-score", "laplace-cylinder", "theresa-cylinder"],
  },
  {
    id: "felix-rowe",
    assetId: "case.fog-without-wolves.character.felix",
    name: "费利克斯·罗",
    archiveName: "FELIX ROWE · KEEPER OF THE FINAL FORM",
    role: "暮钟馆残党与最终见证表保管人",
    district: "地图外拆除区",
    encounterChapter: 4,
    publicRumor: "他只是替旧机构整理事故表格的普通档案员。",
    knownFact: "三处白粉笔祷文均出自他手，他也维护缺失一分钟的登记结构。",
    withheld: "他不在乎哪段记忆为真，只需要第三见证者相信真相必须唯一。",
    quote: "请随便选一个。现实只要求你别让两个答案同时活着。",
    revealClueIds: ["second-handwriting-log", "final-witness-form"],
  },
].map((item) => caseCharacterSchema.parse(item));

const fogWithoutWolvesDistricts = [
  {
    id: "white-bell-quarter",
    assetId: "case.fog-without-wolves.district.white-bell",
    name: "白钟区",
    archiveName: "DISTRICT 01 · WHITE BELL QUARTER",
    subtitle: "旧住宅、货运高架与整街停摆钟表围住一间没有尸体的房",
    introducedChapter: 1,
    publicVersion: "计时署称该区只发生过一次普通机械故障，所有双重记录均为潮湿误差。",
    cityRule: "当一条街同时停在 23:43，先检查下一分钟被谁从登记册里取走。",
    landmarks: ["双影房", "停摆钟表铺", "夜运调度桥"],
  },
  {
    id: "saint-vesper-theatre-row",
    assetId: "case.fog-without-wolves.district.saint-vesper",
    name: "圣维斯帕剧院街",
    archiveName: "DISTRICT 02 · SAINT VESPER THEATRE ROW",
    subtitle: "旧剧院、声学工坊与雨中货轨共同保存两只互不覆盖的蜡筒",
    introducedChapter: 2,
    publicVersion: "理事会称停业剧院只保存舞台机械，不存在秘密声学档案或异常训练。",
    cityRule: "没有钟舌的钟仍会放大身体记忆；听见以前，先确认是谁布置了声场。",
    landmarks: ["废弃排练舞台", "双钥匙蜡筒库", "回声调谐台"],
  },
  {
    id: "unlisted-bellworks",
    assetId: "case.fog-without-wolves.district.unlisted-bellworks",
    name: "地图外钟工场",
    archiveName: "DISTRICT 03 · UNLISTED BELLWORKS",
    subtitle: "工业边缘的巨钟等待外部见证者把两个人压成一份结论",
    introducedChapter: 4,
    publicVersion: "拆除署称此处没有登记建筑，雾中可见的钟楼只是相邻厂房叠影。",
    cityRule: "第十三声不由钟舌发出；它从一份愿意删除矛盾的报告里取得方向。",
    landmarks: ["暮钟工场", "第十三声维护桥", "最终见证表保管柜"],
  },
].map((item) => cityDistrictSchema.parse(item));

export const fogWithoutWolvesCampaign = defineCampaign({
  id: FOG_WITHOUT_WOLVES_CAMPAIGN_ID,
  version: 1,
  case: fogWithoutWolvesCase,
  routes: fogWithoutWolvesRoutes,
  syntheses: fogWithoutWolvesSyntheses,
  endings: fogWithoutWolvesEndings,
  postcards: fogWithoutWolvesPostcards,
  botanicals: fogWithoutWolvesBotanicals,
  watchEchoes: fogWithoutWolvesWatchEchoes,
  wakeEchoes: fogWithoutWolvesWakeEchoes,
  characters: fogWithoutWolvesCharacters,
  districts: fogWithoutWolvesDistricts,
  rules: {
    trueEndingId: "return",
    requiredClueCount: fogWithoutWolvesCase.clues.length,
    requiredCollectibleCount: 7,
    requiredSynthesisCount: fogWithoutWolvesSyntheses.length,
  },
  presentation: {
    archiveNumber: "005",
    teaser: "两名旧猎手记得同一声钟的两个真实结局，第三见证者被要求删除其中一个。",
    headlineMain: "两封遗书出自同一笔迹，",
    headlineAccent: "他不肯删掉任何一个结局。",
    description: "沿双面遗书、两只蜡筒与缺失一分钟走进暮钟工场，拒绝把理解彼此重新写成服从。",
    cityName: "雾灯城",
    detectiveName: "林渡",
    heroAssetId: "case.fog-without-wolves.header.handoff",
    nightAssetId: "case.fog-without-wolves.header.night",
    morningAssetId: "case.fog-without-wolves.header.morning",
    endingAssetId: "case.fog-without-wolves.ending.tableau",
    nightSealAssetIds: fogWithoutWolvesCase.chapters.map((chapter) => `case.fog-without-wolves.night-seal.0${chapter.number}`),
    endingQuestion: "两段记忆都真实发生以后，谁还有资格要求其中一个人消失？",
    endingPrompt: "双重现场、成对蜡筒与第三见证表都已查明。最后要决定的是提交唯一版本、切断共同记忆，还是拒绝让暮钟馆继续规定谁只能聆听、谁只能命名。",
    closingRefrain: "天已经亮了，雾中没有狼，两个人分别取回了自己的手套。",
    prologue: {
      scenes: [
        {
          stage: "incident",
          eyebrow: "夜班事务所 22:17 · 雨水刚停",
          title: "七年前死去的人从阁楼走下来",
          body: "夜间货运调度员特蕾莎·维尔刚问完拉普拉斯为何仍然活着，闲置阁楼便响起脚步。拉普拉斯走到交接桌前，放下一枚染血却没有钟舌的旧银铃。",
          aside: "“你们问错了。应该问：她为什么需要我死过一次？”",
          assetId: "case.fog-without-wolves.header.handoff",
        },
        {
          stage: "evidence",
          eyebrow: "接案物证 · 两份都真实的记忆",
          title: "同一声钟拥有两个结局",
          body: "特蕾莎记得拉普拉斯请求她敲钟；拉普拉斯记得自己找到出口，却被清醒地留在地下。三起新死亡把两段旧案重新叠进雾灯城，现场只留下白粉笔祷文与相反遗书。",
          aside: "你将核对现场、蜡筒与缺失的一分钟。证据需要解释矛盾，不需要提前选出赢家。",
          assetId: "collectible.fog-without-wolves.bloodied-bell",
        },
        {
          stage: "handoff",
          eyebrow: "第一夜交接 · 林渡",
          title: "今晚先调查一间没有尸体的谋杀现场",
          body: "林渡把两封遗书分装进不同证物袋，先去白钟区复原灯位，再追查全街停在 23:43 的钟。他不会让拉普拉斯或特蕾莎同行，也不会替她们恢复旧站位。",
          aside: "“你去睡。我带回两份报告；如果它们互相矛盾，就让矛盾完整地回来。”",
          assetId: "case.fog-without-wolves.header.night",
        },
      ],
      acceptLabel: "接下案件，进入事务所",
    },
  },
});
