import {
  caseCharacterSchema,
  caseSchema,
  cityDistrictSchema,
  cityWatchEchoSchema,
  endingEpilogueSchema,
  evidenceSynthesisSchema,
  journeyPostcardSchema,
  nightBotanicalSchema,
  routeDirectionSchema,
  wakeEchoSchema,
  type CityWatchId,
  type EndingEpilogue,
  type JourneyPostcard,
  type NightBotanical,
  type RouteDirection,
} from "@/src/lib/game-engine/schema";
import { defineCampaign } from "./types";

export const THIRTEENTH_LOAF_CAMPAIGN_ID = "case-004";

const thirteenthLoafCase = caseSchema.parse({
  id: THIRTEENTH_LOAF_CAMPAIGN_ID,
  title: "面包奇谈",
  englishTitle: "The Thirteenth Loaf Before Dawn",
  chapters: [
    {
      number: 1,
      title: "柜中多出的一只",
      subtitle: "十二枚持份环领走十二只面包，街边柜里每天仍会留下第十三只。",
      cityAside: "雾灯城不反对面包多出一只，只要求它尽快找到可以被收费的主人。",
      question: "谁在合作面包房停业十七年后，仍把第十三只面包放进保温柜？",
      choices: [
        { id: "cabinet", label: "守着街边保温柜", note: "先看谁来取走没有名字的一份。" },
        { id: "crumbs", label: "沿面粉脚印逆行", note: "脚印会把送达和领取分开。" },
        { id: "rings", label: "核对黄铜持份环", note: "数清有主的份额，再看剩下什么。" },
      ],
      clueIds: ["extra-loaf", "twelve-tallies", "warm-cabinet"],
      collectibleIds: ["loaf-tally-ring", "cabinet-hook"],
      route: ["夜班事务所", "煤钟街", "旧合作面包房", "街边保温柜"],
      events: ["00:38 — 保温柜的黄铜门闩自行松开。", "01:12 — 十二枚持份环依次碰响木钉。", "02:06 — 面粉脚印从三条巷口汇入柜前。", "03:47 — 一只无字纸包被放上最下层。", "05:09 — 取面包的人没有留下欠条。"],
      journal: "合作面包房停业十七年，街边保温柜却每天在黎明前多出一只温热面包。柜边只有十二枚黄铜持份环的磨痕，没有第十三枚；来取面包的人也不是固定的一位。城市把它归为无主货物，柜门却显然一直被许多人共同维护。",
      contradiction: "如果合作社只有十二名持份人，为什么每天稳定烤出第十三只面包？",
    },
    {
      number: 2,
      title: "没有第十三名烘焙师",
      subtitle: "工资簿、围裙和工作台都只承认十二人，空白访客牌却从未缺席。",
      cityAside: "登记处愿意替不存在的人补缴工资，却不愿承认没有姓名的份额。",
      question: "第十三只面包是否对应一名被从名册删掉的成员？",
      choices: [
        { id: "roster", label: "拆开烧焦工资簿", note: "工资最擅长证明谁必须存在。" },
        { id: "aprons", label: "数完墙上的旧围裙", note: "衣物会留下比姓名更诚实的尺寸。" },
        { id: "courier", label: "跟上夜间送货车", note: "看多出来的一份最终去了哪里。" },
      ],
      clueIds: ["twelve-name-roster", "blank-guest-share"],
      collectibleIds: ["blank-guest-token", "flour-route-spool"],
      route: ["街边保温柜", "十二人工作间", "烧焦账房", "后巷送货坡"],
      events: ["00:42 — 十二件围裙在空工作台前同时摆动。", "01:25 — 工资簿最后一行停在第十二个签名。", "02:31 — 空白访客牌从账页夹层滑落。", "03:56 — 送货车在免费诊所门口停下。", "05:02 — 第十三只面包被一双陌生手取走。"],
      journal: "工资簿、围裙、工作台和黄铜持份环都只属于十二个人。夹在章程里的空白访客牌没有姓名、工时或投票权，却写在每日烘焙量的算法里。第十三只面包不是被删掉成员的工资，而是合作社主动留下的一份不问身份的早餐。",
      contradiction: "空白访客牌没有姓名和投票权，为什么仍被写进每日必须完成的烘焙量？",
    },
    {
      number: 3,
      title: "火从炉外开始",
      subtitle: "市政报告指控煤炉，焦痕与熔断器却把方向指向炉桥下的热力主管。",
      cityAside: "一场火若来自公共管道，就很难只由一家小店负责。",
      question: "十七年前关闭合作社的火灾，究竟从哪里烧进来？",
      choices: [
        { id: "conduit", label: "钻进炉桥检修层", note: "让金属的熔化顺序重新作证。" },
        { id: "oven", label: "检查仍完整的砖炉", note: "被指控的东西也有权保留伤口。" },
        { id: "inspector", label: "寻找退役检察员", note: "有人在报告边缘写过第二个答案。" },
      ],
      clueIds: ["conduit-scorch", "intact-oven", "corrected-inspection"],
      collectibleIds: ["heat-main-fuse", "inspector-seal"],
      route: ["煤钟街", "炉桥廊", "市政阀门房", "封存检察室"],
      events: ["00:36 — 熔断器的市政侧先显出热裂。", "01:19 — 焦痕从热力管向面包房展开。", "02:44 — 砖炉内壁保留完整冷灰。", "03:32 — 费澄取出未提交的修正页。", "05:11 — 阀门房终于承认当年超压。"],
      journal: "面包炉内壁没有起火裂纹，热力主管的熔断器却从市政侧向店内熔化。退役检察员费澄当年写过修正页，认定炉桥阀门超压；上级要求他把原因改成合作社违规用煤。火灾报告不仅夺走房契，也把公共设施的责任转嫁给了十二名烘焙师。",
      contradiction: "若火灾始于面包炉，为什么熔断器和焦痕都从市政热力管一侧先受损？",
    },
    {
      number: 4,
      title: "整座街区保管一块酵母",
      subtitle: "合作社没有消失，它把一团活酵母拆成许多窗台上的微小证词。",
      cityAside: "一件财产分给足够多人保管以后，没收处会称它为无法定位的潮气。",
      question: "停业以后，第十三只面包为什么从未中断？",
      choices: [
        { id: "jars", label: "清点窗台酵母罐", note: "每户只保管一小勺活着的历史。" },
        { id: "ledger", label: "等地下炉翻开夜账", note: "账簿会记录劳动，不记录领袖。" },
        { id: "route", label: "和柯遥走完送货线", note: "面包抵达之处比店址更接近合作社。" },
      ],
      clueIds: ["starter-census", "night-bake-ledger", "courier-route"],
      collectibleIds: ["shared-starter-lid", "commons-deed-clasp"],
      route: ["炉桥廊", "黎明粮仓", "酵母窗台庭院", "地下公共炉"],
      events: ["00:40 — 第一户窗台送下一勺活酵母。", "01:23 — 十二条细路在地下炉前汇合。", "02:52 — 夜账只记录劳动时长，不写负责人。", "03:43 — 柯遥装好诊所与候车室的面包。", "05:07 — 所有酵母罐各自带回一小份。"],
      journal: "十二名成员把母酵分给煤钟街和黎明粮仓的住户，每户保管一小勺，夜里再轮流送到地下公共炉。夜账没有领袖签名，只有谁揉面、谁看火、谁骑车；柯遥把第十三只面包送往诊所、候车室和街边柜。合作社从一栋房子变成了许多人重复的一套动作。",
      contradiction: "如果合作社已被没收，为什么没有任何单一负责人仍能让它每夜完整运转？",
    },
    {
      number: 5,
      title: "把一份归还给无人",
      subtitle: "房契可以还给十二名持份人，第十三份却必须继续不属于任何人。",
      cityAside: "城市终于同意归还财产，只是不理解为何有人拒绝把最后一份写进姓名栏。",
      question: "怎样归还合作社，才不会把公共早餐变成第十三份私人财产？",
      choices: [
        { id: "announce", label: "公开火灾与全部名册", note: "让整座城见证错误与补偿。" },
        { id: "shelter", label: "先保护地下炉与送货线", note: "让互助网络在追责前保持安全。" },
        { id: "charter", label: "重写十二人共同章程", note: "归还房契，也把无主份额写成不能出售的权利。" },
      ],
      clueIds: ["commons-charter"],
      collectibleIds: ["commons-deed-clasp"],
      route: ["地下公共炉", "市政房契库", "旧合作面包房", "街边保温柜"],
      events: ["00:43 — 烧焦房契在修复台上重新展开。", "01:28 — 十二枚持份环回到十二个姓名旁。", "02:37 — 第十三栏仍然保持空白。", "03:59 — 宋岑把柜门钥匙放在公共桌上。", "05:00 — 第一只归还后的面包留给尚未来到的人。"],
      journal: "何砾修复了原房契，费澄愿意公开修正报告，十二名成员也都还活着。真正困难的是第十三份：它从来没有所有者，不能在补偿时被某个人领取。宋岑提出把房契还给十二人，把街边柜和每日一只面包写成不可出售、不可取消、由社区轮值维护的公共使用权。",
      contradiction: "财产归还通常要求写明所有者，为什么真相反而要求第十三栏永远空白？",
    },
  ],
  clues: [
    ["extra-loaf", "每日多出的一只面包", "停业面包房每天稳定留下第十三只温热面包", "面包来自仍在运转的地下公共炉，不是旧库存或匿名商店捐赠。", "工商处愿意登记它的价格，却找不到可以承担税费的店主。", "多出来的不是产量误差，而是一条仍被执行的旧规矩。", "event", 1],
    ["twelve-tallies", "十二枚持份环磨痕", "保温柜只留下十二枚黄铜环的长期磨痕", "每枚环对应合作社一名持份人，数量十七年来没有变化。", "登记处认为磨痕不足以证明成员资格。", "有主的份额从来只有十二份。", "object", 1],
    ["warm-cabinet", "仍有人维护的保温柜", "门闩、油布与挂钩每月都被重新保养", "维护痕迹来自多种工具和手势，说明保温柜由街区共同照看。", "市政厅称公共维护属于责任主体不明。", "柜子没有主人，却从未被遗弃。", "place", 1],
    ["twelve-name-roster", "十二人完整名册", "工资、围裙、工作台与持份环都逐一对应十二人", "名册没有被刮去的第十三行，也没有少发过一份工资。", "劳动处建议为不存在的第十三人补做离职手续。", "没有失踪的烘焙师，只有被误读的面包。", "contradiction", 2],
    ["blank-guest-share", "空白访客份额", "章程把一只无字面包计入每日固定产量", "它没有投票权、工资或领取人，只要求留在任何饥饿者能打开的柜中。", "产权处称无人所有的固定份额无法估值。", "不写名字不是遗漏，而是保护它属于下一位需要的人。", "object", 2],
    ["conduit-scorch", "向内展开的管道焦痕", "焦痕从市政热力主管破口扇形指向面包房", "金属氧化与墙面碳化顺序证明热量先在炉桥检修层爆发。", "热力处称方向性焦痕不具备行政方向。", "火从公共管道进店，不是从炉膛出店。", "place", 3],
    ["intact-oven", "没有起火裂纹的砖炉", "被指控的煤炉内壁只保留正常冷灰", "炉门、耐火砖与烟道均未出现由内向外的爆燃痕迹。", "消防档案称完整也可能是一种过度损坏。", "被定罪的炉子反而保存了最干净的伤口。", "object", 3],
    ["corrected-inspection", "未提交的检察修正页", "费澄曾认定市政阀门超压并要求撤回原结论", "修正页纸纤维、压力曲线与熔断器编号互相吻合，后来被上级压下。", "市政厅称没有收件章的真话只是一份私人草稿。", "报告被改过，火的方向没有。", "person", 3],
    ["starter-census", "分散酵母清册", "多户窗台各保管一小份同源母酵", "每罐只足以维持菌种，合在一起才足够完成夜间烘焙。", "卫生处认为分散保存会导致责任分散。", "合作社把自己拆成无法被一次没收的活物。", "object", 4],
    ["night-bake-ledger", "无负责人夜账", "账簿只记录揉面、看火与送达，不记录领袖", "十二名成员和邻居轮班完成工作，任何一人缺席都不会让主线中断。", "劳动处要求先选出一位可以被处罚的负责人。", "没有中心不等于没有秩序。", "event", 4],
    ["courier-route", "柯遥的免费送达线", "第十三只面包总在诊所、候车室与街边柜之间轮换", "路线只根据当夜哪里有人需要，不对应固定会员或购买记录。", "交通处称没有收费终点的路线不构成运输。", "面包的目的地是一种需要，不是一个账户。", "person", 4],
    ["commons-charter", "永远空白的第十三栏", "修复章程把房契归还十二人，把访客份额留作不可出售的公共使用权", "十二枚持份环对应所有权；空白栏只约束合作社每天留下一只任何人可取的面包。", "产权处认为最稳妥的公共权利应当先找一名私人代持。", "真正的归还是让十二人重新拥有，也让第十三份继续无人占有。", "contradiction", 5],
  ].map(([id, title, summary, detail, cityObjection, marginNote, type, chapter], index, all) => ({
    id,
    title,
    summary,
    detail,
    cityObjection: `${String(cityObjection).replace(/。$/, "，")}并建议暂存到“无人可追责物品”抽屉。`,
    marginNote,
    type,
    chapter,
    relatedIds: index ? [String(all[index - 1][0])] : [],
  })),
  collectibles: [
    ["loaf-tally-ring", "合作社持份环", "○", "collectible.thirteenth-loaf.tally-ring", "一枚内槽嵌着面粉的厚黄铜环。", "十二枚环各有姓名；它证明第十三份从未对应成员。", "煤钟街", "common", 1],
    ["cabinet-hook", "保温柜空挂钩", "∪", "collectible.thirteenth-loaf.cabinet-hook", "被许多双手磨亮下弯处的铜绿挂钩。", "它每月都被不同工具重新固定，柜子一直由街区共同维护。", "煤钟街", "unusual", 1],
    ["blank-guest-token", "无字访客牌", "◇", "collectible.thirteenth-loaf.blank-guest-token", "黄铜包边的纸牌，正反两面完全空白。", "空白不是待填姓名，而是合作社特意保留的领取资格。", "十二人工作间", "rare", 2],
    ["flour-route-spool", "面粉路线线轴", "⌁", "collectible.thirteenth-loaf.flour-route-spool", "缠着铜线与白绳的小线轴。", "三条线分别通往诊所、候车室与街边柜，均没有收费终点。", "后巷送货坡", "unusual", 2],
    ["heat-main-fuse", "热力主管熔断器", "⫯", "collectible.thirteenth-loaf.heat-main-fuse", "市政侧熔成黑色扇形的陶瓷黄铜管。", "熔化顺序证明热量从炉桥进入面包房。", "炉桥廊", "rare", 3],
    ["inspector-seal", "焦边检察圆章", "◴", "collectible.thirteenth-loaf.inspector-seal", "一侧起泡、封线断裂的热力检察章。", "烧焦位置与费澄修正页的压力曲线完全对应。", "市政阀门房", "rare", 3],
    ["shared-starter-lid", "共酵罐盖", "◉", "collectible.thirteenth-loaf.starter-lid", "带发酵观察窗的旧深蓝搪瓷盖。", "窗口里的菌泡来自十二户同源酵母中的一份。", "黎明粮仓", "unusual", 4],
    ["commons-deed-clasp", "公共房契扣", "⌒", "collectible.thirteenth-loaf.deed-clasp", "两只铜绿手掌托住一只无记号面包。", "它把十二人房契与不可出售的访客份额扣在同一份章程里。", "市政房契库", "rare", 4],
  ].map(([id, title, glyph, assetId, surfaceDescription, revealedDescription, district, rarity, chapter]) => ({
    id,
    title,
    glyph,
    assetId,
    surfaceDescription,
    revealedDescription,
    district,
    rarity,
    chapter,
  })),
});

const routeTemplates = [
  ["misfiled-registry", "market"],
  ["mislaid-consulate", "river"],
  ["afterlight-cartographers", "heights"],
] as const;

const thirteenthLoafRoutes: RouteDirection[] = thirteenthLoafCase.chapters.flatMap((chapter) =>
  chapter.choices.map((choice, index) => routeDirectionSchema.parse({
    id: `loaf-night-${chapter.number}-${choice.id}`,
    chapter: chapter.number,
    choiceId: choice.id,
    dispatchTitle: choice.label,
    departureIntent: choice.note,
    destination: chapter.route[Math.min(index + 1, chapter.route.length - 1)],
    mapVariant: routeTemplates[index][1],
    routeNodes: [chapter.route[0], chapter.route[Math.min(index + 1, chapter.route.length - 1)], chapter.route[Math.min(index + 2, chapter.route.length - 1)], chapter.route.at(-1)!],
    events: chapter.events.map((event, eventIndex) => eventIndex === index ? `${event} 林渡沿“${choice.label}”留下了一道面粉色旁注。` : event),
    cityEncounter: `${chapter.cityAside} 林渡选择“${choice.label}”以后，沿途每一扇尚有余温的窗都提供了措辞不同、方向一致的证词。`,
    returnLetter: `我按“${choice.label}”走完这一夜。${chapter.journal}`,
    societyId: routeTemplates[index][0],
    societyNotice: `你用“${choice.label}”处理了第 ${chapter.number} 夜的合作社异议，让一份不写姓名的证据获得了可归档的来路。`,
  })),
);

const thirteenthLoafSyntheses = [
  {
    id: "loaf-no-thirteenth-owner",
    inputIds: ["twelve-name-roster", "blank-guest-share"],
    title: "第十三只面包不是失踪成员的份额",
    explanation: "完整十二人名册与刻意保持空白的访客份额互相证明：合作社从未有第十三名持份人，多出来的一只面包是公共早餐。",
  },
  {
    id: "loaf-fire-from-main",
    inputIds: ["conduit-scorch", "corrected-inspection"],
    title: "火灾由市政热力主管超压引起",
    explanation: "向内展开的管道焦痕与费澄未提交的修正页方向一致，原报告把公共设施责任转嫁给了合作社。",
  },
  {
    id: "loaf-cooperative-survived",
    inputIds: ["starter-census", "night-bake-ledger"],
    title: "合作社以分布式轮值继续存在",
    explanation: "分散酵母清册与无负责人夜账说明，成员和邻居把菌种与劳动拆开保管，使任何一次没收都无法终止互助。",
  },
].map((item) => evidenceSynthesisSchema.parse(item));

const thirteenthLoafEndings: EndingEpilogue[] = [
  {
    id: "public",
    archiveLabel: "CASE CLOSED · PUBLIC HEARING",
    title: "把火灾报告贴满全城",
    theme: "让每个人看见公共责任如何被写成一家小店的过错。",
    result: "修正报告、焦痕证据与十二人名册在公开听证会上同时出现，合作社获得赔偿与房契；地下炉和送货线也因此受到突然涌来的关注。",
    detectiveLetter: "我们让那份迟到十七年的修正页先于面包出现在清晨。市政热力处终于承认主管超压，十二名成员的名字也重新写回房契。公开把错误纠正得很快，却把太多目光带向本来只需一只柜门就能维持的互助线。宋岑没有反对，她只提醒我：知道面包从哪里来的人变多以后，仍要有人记得别替取走它的人登记姓名。",
    closingLine: "真相被贴上街以后，第十三只面包仍用空白纸包着。",
  },
  {
    id: "protect",
    archiveLabel: "CASE CLOSED · NIGHT OVEN SHELTERED",
    title: "先保住地下公共炉",
    theme: "让证据足以停止没收，不让网络先成为新的检查对象。",
    result: "关键证据进入独立保全，房契诉讼启动；地下炉、酵母窗台和免费送达线继续保持低调，城市暂时不知道是谁在每夜轮值。",
    detectiveLetter: "我们没有把每一只酵母罐都画到公开地图上。熔断器与修正页足以让没收失去依据，剩下的路线先留在十二户窗台之间。保护不是把真相重新藏起来，而是拒绝让追责过程顺便取得一份可以管理互助的名单。何砾把修好的房契分成三份保管；等十二名成员准备好走进白天，地下炉仍会替他们守住火种。",
    closingLine: "有些炉火保持微弱，是为了不让取暖的人先暴露姓名。",
  },
  {
    id: "return",
    archiveLabel: "TRUE ENDING · THE GUEST SHARE RETURNED",
    title: "让第十三栏永远空白",
    theme: "把房契还给十二人，把使用权留给尚未到来的人。",
    result: "十二名成员恢复合作社所有权，新章程把街边柜和每日访客面包登记为不可出售、不可取消的公共使用权，由街区轮值维护。",
    detectiveLetter: "十二枚持份环各自回到一个名字旁边，最后那张访客牌却没有被任何人领取。我们把空白写进了章程：它不是等待新主人的财产，而是一项所有持份人都必须维护、任何饥饿者都可以使用的权利。房契终于完整，因为它允许一部分价值不属于房契本身。黎明时，柯遥把第一只归还后的面包放进柜里；拿走它的人没有道谢，也没有欠下什么。",
    closingLine: "十二个人重新拥有面包房，第十三只面包继续属于下一位需要它的人。",
  },
].map((item) => endingEpilogueSchema.parse(item));

const postcardTitles = ["街边暖柜", "十二件围裙", "炉桥热力管", "共酵庭院", "无主访客份额"];
const thirteenthLoafPostcards: JourneyPostcard[] = thirteenthLoafCase.chapters.map((chapter, index) => journeyPostcardSchema.parse({
  id: `loaf-postcard-${chapter.number}`,
  chapter: chapter.number,
  assetId: `case.thirteenth-loaf.postcard.0${chapter.number}`,
  title: postcardTitles[index],
  location: chapter.route.at(-1)!,
  cityRumor: chapter.cityAside,
  message: chapter.journal,
  preparationNotes: {
    "side-lamp": "侧照灯让面粉、焦痕与铜线的方向同时显影，报告因此少了一句替城市猜测的话。",
    "flower-note": "花笺吸住一小段新面包的暖气，天亮以后仍能闻出这份证词来自活着的酵母。",
    "tram-fare": "旧零钱没有购买面包，只替一位错过末班车的人保留了街边柜前的一段路。",
  },
}));

const botanicalNames = ["暖柜麦", "十二指黑麦", "热力管莎草", "共酵藤", "客份晨花"];
const botanicalArchiveNames = ["Triticum armarium", "Secale duodecim", "Carex thermalis", "Vitis fermentum commune", "Flos hospitium"];
const thirteenthLoafBotanicals: NightBotanical[] = thirteenthLoafCase.chapters.map((chapter, index) => nightBotanicalSchema.parse({
  id: `loaf-botanical-${chapter.number}`,
  chapter: chapter.number,
  assetId: `case.thirteenth-loaf.botanical.0${chapter.number}`,
  name: botanicalNames[index],
  archiveName: botanicalArchiveNames[index],
  district: chapter.route.at(-1)!,
  cityRumor: `据说它只在有人完整执行第 ${chapter.number} 夜的轮值以后发芽；园艺处认为共同维护不属于稳定光照。`,
  specimenNote: `根与种荚保留着“${chapter.title}”归来时最后一缕面粉、热气或铜线方向。`,
  growthStages: {
    seed: "种核贴着报告纸，像一粒尚未被谁领取的麦种。",
    sprout: "第一根深蓝嫩芽朝最近一扇仍开着的公共柜门弯去。",
    leaf: "叶片逐层展开，铜色脉络把分散的照料连成完整路线。",
    bloom: "暖色花芯稳定亮起，把这一夜的劳动归档而不写成谁的功劳。",
  },
  qualityNotes: {
    interrupted: "植株较小但结构完整；提前醒来没有删掉线索、份额或任何主线事实。",
    regular: "根系、叶片与花芯稳定成形，保存一份清楚的标准标本。",
    restful: "最外层多长出几段城市侧影，让标本更丰盛但不改变结局资格。",
  },
}));

const watchIds: CityWatchId[] = ["lamplighting", "midnight", "last-watch", "daylight"];
const watchLabels = ["掌灯", "夜半", "末更", "白昼"];
const thirteenthLoafWatchEchoes = thirteenthLoafCase.chapters.flatMap((chapter) => watchIds.map((watchId, index) => cityWatchEchoSchema.parse({
  chapter: chapter.number,
  watchId,
  scene: `${watchLabels[index]}时分，${chapter.route.at(-1)}把“${chapter.title}”的余温留在铜管与面粉之间，街窗依次回应。`,
  encounter: `一位没有登记姓名的取面包者在第 ${chapter.number} 夜经过，又请林渡不要把领取写成欠债。`,
  fieldNote: `${watchLabels[index]}改变了沿途遇见谁，却没有改变合作社事实；我只记录劳动怎样抵达，不替它挑选所有者。`,
})));

const thirteenthLoafWakeEchoes = thirteenthLoafCase.chapters.map((chapter) => wakeEchoSchema.parse({
  id: `loaf-sleep-gap-0${chapter.number}`,
  chapter: chapter.number,
  title: `${chapter.title}之间的一次炉火回声`,
  sound: `你短暂醒来时，窗外传来柜门轻响，一小段揉面声从“${chapter.title}”里漏进房间。`,
  glimpse: `林渡在蒸汽雾里回头，看见第 ${chapter.number} 夜的路线绕开一张要求写明所有者的表格。`,
  fieldNote: "这次醒转没有结束夜班。城市只趁你翻身时，把一小段尚有余温的公共劳动夹进报告。",
}));

const thirteenthLoafCharacters = [
  {
    id: "song-cen",
    assetId: "case.thirteenth-loaf.character.song-cen",
    name: "宋岑",
    archiveName: "SONG CEN · LEDGER KEEPER",
    role: "十二人合作社账房与烘焙师",
    district: "煤钟街",
    encounterChapter: 2,
    publicRumor: "她被说成十七年前带着第十三份分红失踪的人。",
    knownFact: "她保存着完整十二人名册、持份环和从未写名的访客牌。",
    withheld: "她一直参与地下公共炉轮值，却拒绝成为方便市政追责的单一负责人。",
    quote: "有名字的十二份要还清；没名字的那份，才不能落到谁手里。",
    revealClueIds: ["blank-guest-share", "night-bake-ledger"],
  },
  {
    id: "fei-cheng",
    assetId: "case.thirteenth-loaf.character.fei-cheng",
    name: "费澄",
    archiveName: "FEI CHENG · RETIRED HEAT INSPECTOR",
    role: "退役市政热力检察员",
    district: "炉桥廊",
    encounterChapter: 3,
    publicRumor: "他亲手在报告上确认煤炉违规，是合作社被没收的直接证人。",
    knownFact: "熔断器、压力曲线与焦痕方向都来自他当年的现场记录。",
    withheld: "他写过认定市政主管超压的修正页，却在上级压力下没有提交。",
    quote: "我改过报告，火没有跟着我的笔改方向。",
    revealClueIds: ["conduit-scorch", "corrected-inspection"],
  },
  {
    id: "ke-yao",
    assetId: "case.thirteenth-loaf.character.ke-yao",
    name: "柯遥",
    archiveName: "KE YAO · NIGHT COURIER",
    role: "夜间免费送达线骑手",
    district: "黎明粮仓",
    encounterChapter: 4,
    publicRumor: "她被当作一家无证面包坊的私人送货员。",
    knownFact: "她每夜从多户窗台收集酵母，再把访客面包送到需要出现的地方。",
    withheld: "路线没有固定终点；她根据诊所、候车室和街边柜当夜的余量决定去向。",
    quote: "不收钱的路线也有终点，只是终点会先饿。",
    revealClueIds: ["starter-census", "courier-route"],
  },
  {
    id: "he-li",
    assetId: "case.thirteenth-loaf.character.he-li",
    name: "何砾",
    archiveName: "HE LI · ARCHIVE CONSERVATOR",
    role: "市政档案修复师",
    district: "市政房契库",
    encounterChapter: 5,
    publicRumor: "他们受命修复没收房契，以便把旧面包房重新拍卖。",
    knownFact: "烧焦章程能还原十二名持份人和一栏无主访客份额。",
    withheld: "他们故意让第十三栏保持空白，等待一种不会把公共权利变成私人代持的写法。",
    quote: "修复不是把每一处空白填满，有时是证明空白本来就在那里。",
    revealClueIds: ["twelve-name-roster", "commons-charter"],
  },
].map((item) => caseCharacterSchema.parse(item));

const thirteenthLoafDistricts = [
  {
    id: "coalclock-row",
    assetId: "case.thirteenth-loaf.district.coalclock-row",
    name: "煤钟街",
    archiveName: "DISTRICT 01 · COALCLOCK ROW",
    subtitle: "钟面没有时间，面包柜仍按黎明开门",
    introducedChapter: 1,
    publicVersion: "市政厅称旧烘焙区在火灾后已停止生产，只保留空置商铺。",
    cityRule: "任何在天亮前多出来的面包，都要先经过一扇不询问姓名的柜门。",
    landmarks: ["空白煤钟塔", "十二人工作间", "街边保温柜"],
  },
  {
    id: "ovenbridge-arcades",
    assetId: "case.thirteenth-loaf.district.ovenbridge",
    name: "炉桥廊",
    archiveName: "DISTRICT 02 · OVENBRIDGE ARCADES",
    subtitle: "公共热力在石拱下流动，责任总往小店里漏",
    introducedChapter: 3,
    publicVersion: "热力处称主管从未发生足以影响商户的超压事故。",
    cityRule: "铜管记得热从哪边来，即使报告要求它指向相反方向。",
    landmarks: ["市政阀门房", "双层热力主管", "封存检察室"],
  },
  {
    id: "dawn-granary",
    assetId: "case.thirteenth-loaf.district.dawn-granary",
    name: "黎明粮仓",
    archiveName: "DISTRICT 03 · DAWN GRANARY",
    subtitle: "一团酵母被整座街区拆开保管",
    introducedChapter: 4,
    publicVersion: "粮食管理处称此处只剩仓储与住宅，不存在集体生产。",
    cityRule: "每扇窗只保存一小勺火种，合起来却足以让一条街在天亮前吃饱。",
    landmarks: ["酵母窗台庭院", "地下公共炉", "河岸送货坡"],
  },
].map((item) => cityDistrictSchema.parse(item));

export const thirteenthLoafCampaign = defineCampaign({
  id: THIRTEENTH_LOAF_CAMPAIGN_ID,
  version: 1,
  case: thirteenthLoafCase,
  routes: thirteenthLoafRoutes,
  syntheses: thirteenthLoafSyntheses,
  endings: thirteenthLoafEndings,
  postcards: thirteenthLoafPostcards,
  botanicals: thirteenthLoafBotanicals,
  watchEchoes: thirteenthLoafWatchEchoes,
  wakeEchoes: thirteenthLoafWakeEchoes,
  characters: thirteenthLoafCharacters,
  districts: thirteenthLoafDistricts,
  rules: {
    trueEndingId: "return",
    requiredClueCount: thirteenthLoafCase.clues.length,
    requiredCollectibleCount: 7,
    requiredSynthesisCount: thirteenthLoafSyntheses.length,
  },
  presentation: {
    archiveNumber: "003",
    teaser: "十二名烘焙师停业十七年后，街边柜里每天仍会多出第十三只面包。",
    headlineMain: "停业十七年的烤炉，",
    headlineAccent: "每天仍多出一只面包。",
    description: "沿面粉、热力管与分散酵母找回合作社，把一份早餐归还给无人。",
    cityName: "雾灯城",
    detectiveName: "林渡",
    heroAssetId: "case.thirteenth-loaf.header.handoff",
    nightAssetId: "case.thirteenth-loaf.header.night",
    morningAssetId: "case.thirteenth-loaf.header.morning",
    endingAssetId: "case.thirteenth-loaf.ending.tableau",
    nightSealAssetIds: thirteenthLoafCase.chapters.map((chapter) => `case.thirteenth-loaf.night-seal.0${chapter.number}`),
    endingQuestion: "房契还给十二人以后，第十三份该属于谁？",
    endingPrompt: "火灾责任、十二名成员与地下公共炉都已查明。最后要决定的是公开、保护，还是让一项权利永远没有私人所有者。",
    closingRefrain: "天已经亮了，街边柜仍替下一位没有名字的人留着余温。",
    prologue: {
      scenes: [
        {
          stage: "incident",
          eyebrow: "清晨 05:46 · 街边保温柜",
          title: "停业十七年后，第十三只面包仍会出炉",
          body: "煤钟街合作面包房只登记过十二名烘焙师。火灾让它停业以后，街边保温柜却每天清晨多出第十三只面包，温度、重量与刀口都像刚离开一座仍在工作的炉。",
          aside: "包面包的纸从不写姓名，只盖着一句旧章：给尚未拥有份额的人。",
          assetId: "case.thirteenth-loaf.header.handoff",
        },
        {
          stage: "evidence",
          eyebrow: "接案物证 · 黄铜持份环",
          title: "十二个人共同保管着第十三份",
          body: "面包篮底藏着十二枚黄铜持份环，内槽都有新鲜面粉。旧房契只承认十二份产权，烧焦的炉门却留下十三种长期使用的痕迹。",
          aside: "你将核对份额、火灾与酵母。林渡会沿着余温寻找那位从未被登记的烘焙者。",
          assetId: "collectible.thirteenth-loaf.tally-ring",
        },
        {
          stage: "handoff",
          eyebrow: "第一夜交接 · 林渡",
          title: "今晚守着不会冷掉的面包",
          body: "林渡把第十三只面包装进纸袋，沿市政蒸汽管寻找仍在供热的地下炉。他不会先问面包属于谁，只会确认是谁一直替陌生人保留一份早餐。",
          aside: "“等你醒来，我们至少该知道：这份余温为什么比产权活得更久。”",
          assetId: "case.thirteenth-loaf.header.night",
        },
      ],
      acceptLabel: "接下案件，进入事务所",
    },
  },
});
