import { assertSandboxCampaign } from "@/src/lib/sandbox/engine";

export const tideRefusedSandbox = assertSandboxCampaign({
  title: "潮汐不肯归档 · 河下区支线",
  englishTitle: "The Tide Refused to Be Filed",
  year: "雾灯历 41 年",
  place: "雾灯城 · 河下区",
  premise: "43 号线的刮痕与运输箱上的姓氏都指向同一片空白：市政厅说河下区从未存在，夜渡船却连续七晚载回握着旧钥匙的乘客。沿两组既有证物中的任一组继续追查，林渡便能趁退潮进入被删去的街区。",
  contentWarnings: ["失踪与溺亡暗示", "制度性抹除", "受困居民", "轻度身体异变"],
  origins: [
    {
      id: "salvage-clerks",
      title: "沿被刮掉的线路进入",
      subtitle: "Follow the Scratched Map",
      briefing: "奥林保留的原始地图在河岸下方多出一层盐白色街网；它与 43 号线被刮去的笔势出自同一套档案规程。",
      objective: "沿删图手续追到水务委员会，找出被改写的泄洪命令与责任人。",
      startingLocationIds: ["water-committee", "seventh-floodgate"],
      startingItemIds: ["committee-seal", "waterworks-pass"],
      startingClueIds: ["blank-compensation"],
      trait: "主案里的地图证物会替林渡打开档案门，但河下区居民仍会观察他准备把真相交给谁。",
    },
    {
      id: "night-ferry-families",
      title: "沿箱子上的姓氏进入",
      subtitle: "Follow the Family Names",
      briefing: "维修车照片里的家庭姓氏，有七个也出现在一叠无主返程票上。票背只写着同一句话：潮退时，请来接我们。",
      objective: "追查秘密运输遗漏的住户，找到他们仍活着的证据，并准备一条真正能回家的路。",
      startingLocationIds: ["night-ferry-pier", "river-rowhouses"],
      startingItemIds: ["family-keyring", "return-ticket-bundle"],
      startingClueIds: ["return-tickets"],
      trait: "主案里的运输证物让居民愿意先说真话，但官方门锁仍不会承认那些被删去的家庭。",
    },
  ],
  clues: [
    { id: "blank-compensation", title: "没有地址的补偿清册", category: "document", summary: "四十三户补偿款存在，住址栏却全部空白。", detail: "付款日期早于官方所称的首次洪灾，签收人栏使用同一枚代签章。", relatedIds: ["tenancy-ledger", "complete-casualty-list"] },
    { id: "salt-nameplates", title: "盐结门牌", category: "place", summary: "退潮后显露的门牌都以盐晶重新长出街名。", detail: "它们拼出“河下区”三个字，也证明街区并非民间误记。", relatedIds: ["doorplate-rubbings", "redrawn-master-map"] },
    { id: "tenancy-ledger", title: "河下区租住总账", category: "document", summary: "总账记录四十三户、七条巷和一所夜校。", detail: "最后一页被市政水务委员会撕走，残余装订线与补偿清册吻合。", relatedIds: ["blank-compensation", "complete-casualty-list"] },
    { id: "doorplate-rubbings", title: "淹屋门牌拓片", category: "place", summary: "七条巷的门牌在不同房屋里重复出现。", detail: "重复不是造假；退潮会把同一所房屋在不同年份的入口叠在一起。", relatedIds: ["salt-nameplates", "child-route-map"] },
    { id: "revised-release-order", title: "修订后的泄洪令", category: "document", summary: "公开版本把开闸时间改晚了四十七分钟。", detail: "这四十七分钟足以让委员撤出仓库，却不足以通知河下区居民。", relatedIds: ["emergency-gate-log", "original-engineering-ledger"] },
    { id: "reverse-tide-gauge", title: "倒走的潮位尺", category: "contradiction", summary: "第七码头的水位记录在泄洪后逆向下降。", detail: "有人让河水暂时倒灌，把街区和事故现场压进城市下层。", relatedIds: ["revised-release-order", "stopped-clock-core"] },
    { id: "emergency-gate-log", title: "紧急闸门日志", category: "document", summary: "值班工程师拒绝执行第二次开闸。", detail: "日志末行写着“下面还有人”，随后被另一种墨水标成设备故障。", relatedIds: ["revised-release-order", "original-engineering-ledger"] },
    { id: "original-engineering-ledger", title: "原始工程总账", category: "document", summary: "河下区被主动用作泄洪缓冲层。", detail: "签章与预算流向显示委员会早已知道居民仍未撤离。", relatedIds: ["emergency-gate-log", "complete-casualty-list"] },
    { id: "night-ferry-roster", title: "最后一班夜渡名册", category: "document", summary: "船上人数比官方失踪数多十二人。", detail: "多出的姓名来自夜校与无证租户，他们从未进入市政人口册。", relatedIds: ["return-tickets", "complete-casualty-list"] },
    { id: "warning-cylinder", title: "未播出的警报蜡筒", category: "testimony", summary: "警报在开闸前录好，却被锁进钟棚。", detail: "录音中能听见工程师报出七条巷名，证明市政掌握完整撤离范围。", relatedIds: ["stopped-clock-core", "child-route-map"] },
    { id: "stopped-clock-core", title: "停在 00:43 的钟芯", category: "place", summary: "钟棚机械被人为卡在警报前一分钟。", detail: "卡榫上残留委员会封蜡，事故并非单纯设备失灵。", relatedIds: ["warning-cylinder", "reverse-tide-gauge"] },
    { id: "child-route-map", title: "夜校生画的屋顶路线", category: "document", summary: "孩子用红线画出高处相连的回家路。", detail: "路线避开倒灌最深处，今天仍能把受困居民带到渡船。", relatedIds: ["doorplate-rubbings", "resident-testimony"] },
    { id: "return-tickets", title: "七张返程票", category: "contradiction", summary: "票面日期每天都会变成下一次退潮。", detail: "它们不是召唤牺牲品，而是河下区反复尝试把求救送上岸。", relatedIds: ["night-ferry-roster", "resident-testimony"] },
    { id: "resident-testimony", title: "仍在等钟响的居民证词", category: "testimony", summary: "居民记得开闸，也记得城市在第二天删掉街名。", detail: "他们不是亡灵；被折叠的街区让身体停留在同一场退潮里。", relatedIds: ["return-tickets", "child-route-map"] },
    { id: "complete-casualty-list", title: "完整遇难与受困者名单", category: "document", summary: "名单把四十三户与最后一班渡船合并成可核对的人名。", detail: "它同时证明事故规模、未登记居民与市政的系统性删改。", relatedIds: ["blank-compensation", "tenancy-ledger", "night-ferry-roster"] },
    { id: "redrawn-master-map", title: "重绘的城市母图", category: "contradiction", summary: "把七条巷重新画回去后，河下区开始与雾灯城同潮。", detail: "地图不是象征物；市政母图决定城市承认哪些道路能通向现在。", relatedIds: ["salt-nameplates", "complete-casualty-list"] },
  ],
  handouts: [
    { id: "amended-flood-order", number: 1, title: "泄洪令修订页", source: "水务委员会临时档案室", summary: "两种墨水把关键时间错开四十七分钟。", archiveText: ["原定警报：零点四十三分。", "修订开闸：零点四十二分。", "边注：先保全上层仓储及委员会印信。"] },
    { id: "ferry-roster-page", number: 2, title: "最后一班夜渡名册", source: "夜渡船码头", summary: "名单末尾有十二个从未被市政承认的名字。", archiveText: ["登记乘客三十一人。", "船工另记夜校师生十二人。", "页脚：返程未完成，不得销票。"] },
    { id: "archivist-marginalia", number: 3, title: "盐档员边注", source: "盐档案馆", summary: "档员用会溶解的盐墨记录被删街名。", archiveText: ["城里删去一个地址，盐会在低处替它保存。", "不要擦门牌；抄下它们彼此呼应的次序。", "第七行只有在有人喊出完整名单时出现。"] },
    { id: "alarm-transcript", number: 4, title: "未播警报转写", source: "停钟棚", summary: "一段从未响彻街区的撤离通知。", archiveText: ["河下七巷居民，请沿屋顶红线前往夜渡。", "不要进入低井，不要等待第二次钟声。", "下面还有人。重复：下面还有人。"] },
    { id: "evacuation-note", number: 5, title: "住户撤离便笺", source: "淹没排屋", summary: "一张传了四十一年的邻里接力单。", archiveText: ["先带孩子和不能走楼梯的人。", "钥匙挂在蓝门后，不要锁死后来者。", "若城里不认我们，就把名字带到能听见的地方。"] },
  ],
  items: [
    { id: "committee-seal", name: "委员会临时印章", description: "能开启官方抽屉，也会让居民先看见你的雇主。" },
    { id: "waterworks-pass", name: "水务检修通行证", description: "允许进入第七码头与钟棚的封锁层。" },
    { id: "family-keyring", name: "七户旧钥匙串", description: "每把钥匙都对应一扇如今不在地图上的门。" },
    { id: "return-ticket-bundle", name: "返程票束", description: "票孔会在靠近受困居民时渗出蓝光。" },
    { id: "tide-lantern", name: "低潮灯", description: "只照亮当前潮层中真实可走的地面。" },
    { id: "floodgate-key", name: "第七闸总钥匙", description: "能把闸门锁在关闭位，也能解除旧日的人工倒灌。" },
    { id: "salt-gloves", name: "盐档手套", description: "防止手温把脆弱的盐页融成无字水迹。" },
    { id: "clock-winding-key", name: "钟棚上弦匙", description: "让停住的警报机构重新走完最后一分钟。" },
    { id: "red-chalk-spool", name: "夜校红粉线", description: "拉开后会贴着仍可返回当下的屋顶边缘。" },
  ],
  npcs: [
    { id: "lin-wei", name: "林苇", role: "市政打捞科书记", faction: "打捞科", publicFace: "只想在晨钟前完成资产核销。", privateDrive: "她的祖母也在空白补偿名单里。" },
    { id: "qiao-he", assetId: "sandbox.tide.character.ferryman", name: "乔河", role: "最后一班夜渡船工", faction: "夜渡船", publicFace: "每晚把空船开进雾里。", privateDrive: "他记得所有乘客，却害怕承认自己当晚先送走了委员。" },
    { id: "su-yin", name: "苏茵", role: "返程票寄件人", faction: "失踪者家属", publicFace: "坚信姐姐还活着。", privateDrive: "她愿意用自己的名字换姐姐离开潮层。" },
    { id: "gu-shan", assetId: "sandbox.tide.character.engineer", name: "顾山", role: "退休水务工程师", faction: "旧水务局", publicFace: "声称事故源于钟棚故障。", privateDrive: "他拒绝第二次开闸，并藏起原始总账等待有人追问。" },
    { id: "yan-luo", assetId: "sandbox.tide.character.archivist", name: "阎珞", role: "盐档案馆守页人", faction: "盐档", publicFace: "把每个访客都当成会融化文件的热源。", privateDrive: "只愿把完整街名交给承诺重绘地图的人。" },
    { id: "mei-shao", name: "梅哨", role: "河下区住户代表", faction: "受困居民", publicFace: "要求先撤离居民，再谈证据。", privateDrive: "担心城市只带走名单，把人永远留在下面。" },
    { id: "he-zhang", name: "贺彰", role: "现任水务委员", faction: "市政厅", publicFace: "愿意承认一次历史文书错误。", privateDrive: "要用封闸换取证据沉底，保护仍在运转的委员会。" },
    { id: "a-jiu", name: "阿九", role: "夜校路线绘制者", faction: "河下夜校", publicFace: "仍维持着事故当晚的孩子模样。", privateDrive: "他知道屋顶路线，却只相信会逐户敲门的人。" },
    { id: "mu-lan", name: "穆岚", role: "低潮记录室见证人", faction: "无名住户", publicFace: "名字从所有正式记录中消失。", privateDrive: "她保管完整名单，并要求调查者先说出街区的名字。" },
  ],
  corruptionStages: [
    { stage: 0, name: "岸上", benefit: "你仍只看见一层城市。", cost: "河下区只在票背与证词里存在。" },
    { stage: 1, name: "鞋底返潮", benefit: "能辨认退潮后短暂显露的门槛。", cost: "离水很远时也会留下湿脚印。" },
    { stage: 2, name: "听见低钟", benefit: "能听见被停住的警报机械。", cost: "整点报时会比别人早一分钟抵达。" },
    { stage: 3, name: "双重街面", benefit: "可同时看见现在与事故夜的道路。", cost: "熟悉的地址开始出现两个门牌。" },
    { stage: 4, name: "盐字浮现", benefit: "皮肤能让被删文字短暂显影。", cost: "写下自己的名字时笔画会缺一角。" },
    { stage: 5, name: "借潮呼吸", benefit: "能在被淹房间里多停留片刻。", cost: "呼吸开始跟随河水而非胸口。" },
    { stage: 6, name: "归档重影", benefit: "能触碰不同年份叠在一起的物件。", cost: "同伴偶尔记不起你来自哪一年。" },
    { stage: 7, name: "成为地址", benefit: "河下区的每扇门都会为你打开。", cost: "离开时，城市可能把你也当成一条已删除的街道。" },
  ],
  locations: [
    {
      id: "water-committee", order: 1, name: "水务委员会临时档案室", archiveName: "地点 01", subtitle: "未干的墨水覆盖着四十一年前的空白。", atmosphere: "抽屉按预算而非年份排列，最下层传来缓慢滴水声。", coordinates: { x: 20, y: 20 },
      actions: [
        { id: "committee-compensation", title: "核对无址补偿款", intent: "从付款总额反推被删住户。", risk: "quiet", scene: "账本把四十三笔钱付给同一枚代签章。", result: "你们确认补偿真实存在，且发生在官方洪灾记录之前。", effects: { clueIds: ["blank-compensation"], handoutIds: ["amended-flood-order"], unlockLocationIds: ["salt-archive"] } },
        { id: "committee-order", title: "比对两份泄洪令", intent: "找出时间为何相差四十七分钟。", risk: "exposed", requirementHint: "需要委员会印章或紧急闸门日志。", requires: { anyClueIds: ["emergency-gate-log"], origins: ["salvage-clerks"] }, scene: "封蜡下藏着更早的一层签字。", result: "修订令把责任从人为提前开闸改写成迟到的设备故障。", effects: { clueIds: ["revised-release-order"], handoutIds: ["amended-flood-order"], threat: 1, npc: [{ npcId: "lin-wei", state: "helpful" }] } },
        { id: "committee-confront", title: "要求委员说明空白地址", intent: "逼贺彰在证据进入总档前表态。", risk: "dangerous", requirementHint: "至少带回原始总账或完整名单。", requires: { anyClueIds: ["original-engineering-ledger", "complete-casualty-list"] }, scene: "贺彰先关门，再把一份封闸授权推过桌面。", result: "他承认河下区被用作缓冲层，并提出用永久封闸换取所有原件。", effects: { threat: 2, npc: [{ npcId: "he-zhang", state: "hostile" }] } },
      ],
    },
    {
      id: "night-ferry-pier", order: 2, name: "夜渡船码头", archiveName: "地点 02", subtitle: "返程票在没有风的水面上自己打孔。", atmosphere: "乔河的船每晚准时靠岸，船板却总带回四十三双湿脚印。", coordinates: { x: 42, y: 14 },
      actions: [
        { id: "ferry-roster", title: "重抄最后一班名册", intent: "把船工私记与市政人数并列。", risk: "quiet", scene: "乔河用指节按住最后十二个名字，像怕它们再次漂走。", result: "名册证明夜校师生和无证住户被排除在官方统计之外。", effects: { clueIds: ["night-ferry-roster"], handoutIds: ["ferry-roster-page"], unlockLocationIds: ["clock-shed"], npc: [{ npcId: "qiao-he", state: "helpful" }] } },
        { id: "ferry-tickets", title: "让返程票靠近空座", intent: "确认票是诱饵还是求救。", risk: "exposed", scene: "每张票在一张空座前亮起，票孔组成七条巷的首字。", result: "返程票指向具体住户，并持续把下一次退潮写成有效日期。", effects: { clueIds: ["return-tickets"], itemIds: ["tide-lantern"], corruption: 1, unlockLocationIds: ["river-rowhouses"] } },
        { id: "ferry-confession", title: "问乔河先送走了谁", intent: "补上事故夜最难开口的一段。", risk: "exposed", requirementHint: "需要名册与修订泄洪令互相作证。", requires: { allClueIds: ["night-ferry-roster", "revised-release-order"] }, scene: "船工把缆绳在手里绕到发白。", result: "乔河承认委员占用了第一趟船，警报响起前居民已失去唯一渡口。", effects: { clueIds: ["resident-testimony"], threat: 1, npc: [{ npcId: "qiao-he", state: "wary" }] } },
      ],
    },
    {
      id: "seventh-floodgate", assetId: "sandbox.tide.location.floodgate", order: 3, name: "第七泄洪闸", archiveName: "地点 03", subtitle: "闸齿间卡着一页拒绝沉底的日志。", atmosphere: "黑铜闸门每隔四十三秒震动一次，像有什么街区在另一侧敲门。", coordinates: { x: 68, y: 20 },
      actions: [
        { id: "floodgate-log", title: "取出闸齿日志", intent: "恢复被标成故障的值班记录。", risk: "dangerous", scene: "纸页被水压贴在齿轮后，却没有一处墨迹晕开。", result: "日志写明值班工程师知道下方还有居民，并拒绝第二次开闸。", effects: { clueIds: ["emergency-gate-log"], itemIds: ["floodgate-key"], unlockLocationIds: ["clock-shed"], npc: [{ npcId: "gu-shan", state: "wary" }] } },
        { id: "floodgate-gauge", title: "复原逆潮刻度", intent: "证明河水曾被工程强制倒灌。", risk: "exposed", scene: "低潮灯下，磨平的刻度从零位向下重新长出。", result: "水位尺显示事故后发生过一次反向排水，把整个街区压进旧河床下层。", effects: { clueIds: ["reverse-tide-gauge"], corruption: 1, unlockLocationIds: ["low-tide-records"] } },
        { id: "floodgate-seal", title: "把第七闸锁死", intent: "阻止下一次回潮吞没更多街区。", risk: "terminal", requirementHint: "需要第七闸总钥匙与原始工程责任证据。", requires: { allItemIds: ["floodgate-key"], allClueIds: ["original-engineering-ledger"] }, scene: "总钥匙转到底时，河下区所有门窗同时发出闭合声。", result: "人工倒灌被永久切断，受困街区不再扩张；尚未撤离的人也失去最近的水路出口。", effects: { threat: 2, npc: [{ npcId: "he-zhang", state: "helpful" }] } },
      ],
    },
    {
      id: "salt-archive", assetId: "sandbox.tide.location.salt-archive", order: 4, name: "盐档案馆", archiveName: "地点 04", subtitle: "城市删掉的字在这里结晶。", atmosphere: "薄盐页悬在铜架之间，访客每次呼气都会让一个旧地址下雪。", coordinates: { x: 16, y: 52 },
      actions: [
        { id: "salt-nameplates", title: "拼合盐结门牌", intent: "还原街区与七条巷的名称。", risk: "quiet", scene: "阎珞把碎片按潮序排列，盐晶自行补出河下区的最后一笔。", result: "街名与补偿清册的四十三户分组一一对应。", effects: { clueIds: ["salt-nameplates"], handoutIds: ["archivist-marginalia"], itemIds: ["salt-gloves"], unlockLocationIds: ["river-rowhouses"], npc: [{ npcId: "yan-luo", state: "helpful" }] } },
        { id: "salt-tenancy", title: "展开租住总账", intent: "让未登记住户重新获得姓名。", risk: "exposed", requirementHint: "需要盐档手套或家属钥匙串。", requires: { anyClueIds: ["blank-compensation", "doorplate-rubbings"] }, scene: "盐页一接触钥匙，便沿旧磨痕显出住户签名。", result: "总账记录四十三户与夜校，最后一页的撕痕指向水务委员会。", effects: { clueIds: ["tenancy-ledger"], corruption: 1 } },
        { id: "salt-bargain", title: "答应把街名画回去", intent: "换取阎珞保留的原始工程索引。", risk: "quiet", requirementHint: "需要先证明你已看见门牌。", requires: { allClueIds: ["salt-nameplates"] }, scene: "阎珞让你在一张空白地图上写下河下区。", result: "承诺落笔后，盐架吐出通往低潮记录室的索引签。", effects: { unlockLocationIds: ["low-tide-records"], npc: [{ npcId: "yan-luo", state: "helpful" }] } },
      ],
    },
    {
      id: "clock-shed", order: 5, name: "停钟棚", archiveName: "地点 05", subtitle: "警报只差最后一分钟就能响起。", atmosphere: "所有表盘停在零点四十三分，蜡筒机仍在无声转动。", coordinates: { x: 48, y: 48 },
      actions: [
        { id: "clock-cylinder", title: "播放未播警报", intent: "听清事故前已经知道哪些街名。", risk: "exposed", scene: "上弦后，扩音喇叭先吐出一口四十一年前的潮气。", result: "警报逐条念出七条巷名，并反复强调下面还有人。", reducedResult: "警报逐条念出撤离范围，证明事故前已有完整居民信息。", effects: { clueIds: ["warning-cylinder"], handoutIds: ["alarm-transcript"], itemIds: ["clock-winding-key"], threat: 1 } },
        { id: "clock-core", title: "拆检封蜡卡榫", intent: "确认停钟是故障还是人为。", risk: "quiet", scene: "齿轮中夹着一小块带委员会纹章的硬蜡。", result: "钟芯被人在警报前一分钟锁死，故障说法无法成立。", effects: { clueIds: ["stopped-clock-core"], unlockLocationIds: ["water-committee"] } },
        { id: "clock-ring", title: "让迟到的钟响完", intent: "把撤离信号送进仍停在事故夜的街区。", risk: "dangerous", requirementHint: "需要上弦匙与完整警报内容。", requires: { allItemIds: ["clock-winding-key"], allClueIds: ["warning-cylinder"] }, scene: "钟声越过四十一年，在每一扇淹没的窗里同时回响。", result: "受困居民第一次听见撤离令，屋顶红线开始在街区上方显现。", effects: { clueIds: ["child-route-map"], corruption: 1, unlockLocationIds: ["river-rowhouses"], npc: [{ npcId: "a-jiu", state: "helpful" }] } },
      ],
    },
    {
      id: "river-rowhouses", order: 6, name: "淹没排屋", archiveName: "地点 06", subtitle: "四十三户人家仍把灯留给后来者。", atmosphere: "水线停在二楼窗沿，厨房里却有温热汤气，屋顶之间拉着褪色红线。", coordinates: { x: 34, y: 76 },
      actions: [
        { id: "rowhouses-rubbings", title: "逐户拓下门牌", intent: "让每条巷拥有可核对的地址证据。", risk: "quiet", scene: "家属钥匙能打开不同年份叠在一起的同一扇门。", result: "拓片证明七条巷的空间被潮层折叠，而非从未存在。", effects: { clueIds: ["doorplate-rubbings"], handoutIds: ["evacuation-note"], unlockLocationIds: ["salt-archive", "night-ferry-pier"] } },
        { id: "rowhouses-testimony", title: "听完住户的那一夜", intent: "记录开闸、停钟与删图的连续经过。", risk: "exposed", scene: "梅哨让每户只说一件亲眼所见的事，直到证词彼此扣合。", result: "住户证词把泄洪、迟到的警报和第二天的地图删改连成同一条因果链。", effects: { clueIds: ["resident-testimony"], corruption: 1, npc: [{ npcId: "mei-shao", state: "helpful" }] } },
        { id: "rowhouses-route", title: "跟随夜校红线", intent: "验证屋顶路线能否抵达渡船。", risk: "dangerous", requirementHint: "需要夜校路线图或低潮灯。", requires: { anyClueIds: ["child-route-map"] }, scene: "红粉线跨过几个并不属于同一年的屋顶。", result: "路线在每次退潮都保持连通，足以分批送居民抵达夜渡船。", effects: { clueIds: ["child-route-map"], itemIds: ["red-chalk-spool"], npc: [{ npcId: "a-jiu", state: "helpful" }] } },
        { id: "rowhouses-evacuate", title: "逐户送人上夜渡船", intent: "先把人带回现在，再决定如何结案。", risk: "dangerous", requirementHint: "需要返程票、住户证词与屋顶路线。", requires: { allClueIds: ["return-tickets", "resident-testimony", "child-route-map"] }, scene: "每上一位乘客，一张票就真正打出返程孔。", result: "夜渡船分七趟把居民送过潮界；无人因睡眠时长或调查顺序被留作代价。", effects: { threat: 2, npc: [{ npcId: "mei-shao", state: "rescued" }, { npcId: "a-jiu", state: "rescued" }, { npcId: "su-yin", state: "helpful" }] } },
      ],
    },
    {
      id: "low-tide-records", assetId: "sandbox.tide.location.low-tide-records", order: 7, name: "低潮记录室", archiveName: "地点 07", subtitle: "母图背面藏着城市不肯拥有的一层。", atmosphere: "房间位于河床下方，书架随潮汐在四个年份之间缓慢错位。", coordinates: { x: 72, y: 72 },
      actions: [
        { id: "records-ledger", title: "取回原始工程总账", intent: "锁定谁把街区写成可牺牲的缓冲层。", risk: "dangerous", requirementHint: "需要紧急闸门日志或盐档索引。", requires: { anyClueIds: ["emergency-gate-log", "salt-nameplates"] }, scene: "顾山从错位书架后走出，把一直没敢公开的总账交给你。", result: "预算、签章与开闸顺序证明委员会明知居民未撤离。", effects: { clueIds: ["original-engineering-ledger"], npc: [{ npcId: "gu-shan", state: "helpful" }], corruption: 1 } },
        { id: "records-names", title: "念出完整住户名单", intent: "让无名住户进入同一份记录。", risk: "exposed", requirementHint: "需要租住总账与夜渡名册。", requires: { allClueIds: ["tenancy-ledger", "night-ferry-roster"] }, scene: "每念出一个名字，母图背面就多亮起一扇窗。", result: "四十三户、夜校师生与最后一班渡船合并成无法再被拆散的完整名单。", effects: { clueIds: ["complete-casualty-list"], npc: [{ npcId: "mu-lan", state: "helpful" }] } },
        { id: "records-redraw", title: "把河下区画回城市母图", intent: "让道路、住户和责任重新进入现在。", risk: "terminal", requirementHint: "需要街名、完整名单、工程责任和屋顶路线。", requires: { allClueIds: ["salt-nameplates", "complete-casualty-list", "original-engineering-ledger", "child-route-map"] }, scene: "红线落下时，雾灯城所有地图同时多出一片潮湿的街区。", result: "河下区重新接入城市道路与档案系统，受困居民获得合法地址，委员会的责任也无法再被删去。", effects: { clueIds: ["redrawn-master-map"], threat: 2, npc: [{ npcId: "mu-lan", state: "rescued" }] } },
      ],
    },
  ],
  endings: [
    { id: "public-ledger", title: "把名单钉回市政厅", archiveLabel: "公开归档", theme: "一座城先承认名字，才有资格谈修复。", requires: { allClueIds: ["original-engineering-ledger", "complete-casualty-list"], allActionIds: ["records-ledger"] }, result: "晨钟前，名单与总账被钉在市政厅正门。贺彰无法再把事故缩成文书错误，河下区家属得到公开听证。", coda: "雨停以后，纸页仍是湿的；这一次，没有一个名字被水带走。" },
    { id: "ferry-home", title: "让夜渡船先送人回家", archiveLabel: "居民返程", theme: "证据可以等下一班，人不能永远等在同一场退潮里。", requires: { allActionIds: ["rowhouses-evacuate"], allClueIds: ["return-tickets", "resident-testimony"] }, result: "夜渡船完成拖欠四十一年的返程。城市尚未准备好承认河下区，但四十三户先在当下获得了门可以敲。", coda: "乔河剪掉最后一张票，第一次把空船停在岸上过夜。" },
    { id: "seal-gate", title: "封死第七码头", archiveLabel: "潮患封存", theme: "阻止灾难继续扩张，也承认封存不是正义的同义词。", requires: { allActionIds: ["floodgate-seal"], allClueIds: ["original-engineering-ledger"] }, result: "第七闸被锁死，河下区不再向邻近街道蔓延。未完成的撤离与公开责任被装进另一份必须继续追查的卷宗。", coda: "新锁每到零点四十三分仍会轻响一次，提醒看守：下面还有人。" },
    { id: "restore-district", title: "让河下区重回地图", archiveLabel: "城市复名", theme: "最完整的归还不是纪念，而是让道路重新通向生活。", requires: { allActionIds: ["records-redraw"], allClueIds: ["redrawn-master-map", "complete-casualty-list"] }, result: "河下区重新出现在母图、路牌与住户登记中。失踪者走出潮层，水务委员会的责任与修复义务也一并回到城市表面。", coda: "第二天清晨，邮差抱怨多了七条巷要走，却没有问它们从哪里来。" },
  ],
  presentation: {
    caseNumber: "001 · 支线",
    caseTypeLabel: "MAIN CASE STORYLINE",
    loadingTitle: "正在等待河下区退潮",
    entryEyebrow: "雾灯历 41 年 · 第七码头",
    entryCta: "以此身份进入低潮",
    navigationLabel: "零点四十三分的末班车河下区支线导航",
    mapTitle: "河下区低潮图",
    mapDescription: "七个地点可以非线性调查；同一关键事实至少有两条接近路径。",
    mapAriaLabel: "河下区七地点调查地图",
    mapCaption: "LOWER-RIVER WARD · LOW-TIDE SURVEY",
    conditionLabel: "回潮",
    conditionAdvanceHint: "进入更深潮层、触碰错位档案或让旧机械重新运转会推进回潮。",
    threatLabel: "城市警觉",
    handoffModeLabel: "河下区夜班模式",
    sleepEthic: "睡眠质量只改变晨报的叙事层次，不改变线索、人物存亡、回潮阶段或可达结局。",
    nightTitle: "河下区夜班进行中",
    nightClosingLine: "潮水仍在退；晨报会把确定的事实完整带回来。",
    morningTitle: "河下区晨报",
    noNewEvidence: "没有新增卷宗，但这次行动已经改变城市警觉与人物立场。",
    noEndingTitle: "还没有足够完整的收场",
    noEndingDescription: "继续核对名单、工程责任、返程路线或第七闸；关键事实可以从不同地点抵达。",
    resetTitle: "重新开始河下区支线？",
    resetDescription: "这会清除河下区的入口、地点、证物、回潮与结局进度；第一案五夜主线与其他样板不受影响。",
    endingEyebrow: "THE TIDE REFUSED TO BE FILED",
    handoutKicker: "LOWER-RIVER WARD",
    handoutFooter: "雾灯城主案支线档案 · 所有姓名、地点与文本均为原创",
    briefingHeading: "案件与原创边界",
    creditsHeading: "Night Shift 原创主案支线",
    heroAssetId: "sandbox.tide.hero",
    npcStateLabels: { unknown: "尚未接触", wary: "有所保留", helpful: "愿意作证", hostile: "阻止调查", rescued: "已返当下", lost: "失于潮层", transformed: "与潮层重叠" },
  },
  credits: {
    attribution: "Night Shift 原创主案支线 · 《潮汐不肯归档》",
    adaptation: "借鉴经典调查沙盒的双入口、地点网络、冗余证据与多结局结构，不使用任何既有作品的人物、地点、情节或美术。",
    usage: "仓库原创内容，依项目许可使用。",
    notice: "向以社区秘密、调查者主动性与后果收束见长的桌面调查传统致意。",
  },
});
