import type { GameAsset } from "./assets";

export const chihayaNoaAssets = {
  handoff: {
    id: "case.chihaya-noa.header.handoff",
    src: "/art/cases/chihaya-noa/headers/shift-handoff-v1.webp",
    alt: "千早诺亚在夜班事务所交接桌前留下十三张日期互斥的旧车票",
    category: "header",
    status: "complete",
  },
  night: {
    id: "case.chihaya-noa.header.night",
    src: "/art/cases/chihaya-noa/headers/night-expedition-v1.webp",
    alt: "林渡沿雾灯城雨夜铁路调查并行的车票、纸结与返照镜线路",
    category: "header",
    status: "complete",
  },
  morning: {
    id: "case.chihaya-noa.header.morning",
    src: "/art/cases/chihaya-noa/headers/morning-report-v1.webp",
    alt: "林渡在清晨把十三份独立证词与返照镜调查报告带回事务所",
    category: "header",
    status: "complete",
  },
  ending: {
    id: "case.chihaya-noa.ending.tableau",
    src: "/art/cases/chihaya-noa/headers/ending-tableau-v1.webp",
    alt: "十三张签名车票围住熄灭的返照镜与一把不替任何人排序的零号钥匙",
    category: "ending",
    status: "complete",
  },
  futureTicket: {
    id: "collectible.chihaya-noa.future-ticket",
    src: "/art/cases/chihaya-noa/collectibles/future-ticket-v1.webp",
    alt: "日期比现在晚一天却已经磨旧的第十三号列车票",
    category: "collectible",
    status: "complete",
  },
  harborStamp: {
    id: "collectible.chihaya-noa.harbor-stamp",
    src: "/art/cases/chihaya-noa/collectibles/harbor-stamp-v1.webp",
    alt: "柄部被十二种握法磨亮的雾港黄铜入境章",
    category: "collectible",
    status: "complete",
  },
  paperKnotSpool: {
    id: "collectible.chihaya-noa.paper-knot-spool",
    src: "/art/cases/chihaya-noa/collectibles/paper-knot-spool-v1.webp",
    alt: "缠着窄纸带与旧酒红细线、保存十二种折法的纸结线轴",
    category: "collectible",
    status: "complete",
  },
  bloodlessCutter: {
    id: "collectible.chihaya-noa.bloodless-cutter",
    src: "/art/cases/chihaya-noa/collectibles/bloodless-cutter-v1.webp",
    alt: "刀尖沾着未成线红泥却找不到伤者记录的裁纸刀",
    category: "collectible",
    status: "complete",
  },
  mirrorShard: {
    id: "collectible.chihaya-noa.mirror-shard",
    src: "/art/cases/chihaya-noa/collectibles/returning-mirror-shard-v1.webp",
    alt: "不映面孔、只保存一段完整生活房间的返照镜碎片",
    category: "collectible",
    status: "complete",
  },
  mislabelledPlaque: {
    id: "collectible.chihaya-noa.mislabelled-plaque",
    src: "/art/cases/chihaya-noa/collectibles/mislabelled-plaque-v1.webp",
    alt: "多次刮改、背面仍留着器物原名的错译黄铜展签",
    category: "collectible",
    status: "complete",
  },
  zeroKey: {
    id: "collectible.chihaya-noa.zero-key",
    src: "/art/cases/chihaya-noa/collectibles/zero-key-v1.webp",
    alt: "拥有十三处平等齿位、只开门而不挑选通过者的零号钥匙",
    category: "collectible",
    status: "complete",
  },
  ticketClasp: {
    id: "collectible.chihaya-noa.ticket-clasp",
    src: "/art/cases/chihaya-noa/collectibles/thirteen-ticket-clasp-v1.webp",
    alt: "可以展开为十三格并分别保存签名与沉默边界的黄铜票夹",
    category: "collectible",
    status: "complete",
  },
  seal01: {
    id: "case.chihaya-noa.night-seal.01",
    src: "/art/cases/chihaya-noa/night-seals/night-01-v1.webp",
    alt: "十二枚入境章环绕一张明日车票组成的第一夜夜印",
    category: "night-seal",
    status: "complete",
  },
  seal02: {
    id: "case.chihaya-noa.night-seal.02",
    src: "/art/cases/chihaya-noa/night-seals/night-02-v1.webp",
    alt: "两条纸结路线在折返街图上并行的第二夜夜印",
    category: "night-seal",
    status: "complete",
  },
  seal03: {
    id: "case.chihaya-noa.night-seal.03",
    src: "/art/cases/chihaya-noa/night-seals/night-03-v1.webp",
    alt: "错译展签与返照镜碎片组成的第三夜夜印",
    category: "night-seal",
    status: "complete",
  },
  seal04: {
    id: "case.chihaya-noa.night-seal.04",
    src: "/art/cases/chihaya-noa/night-seals/night-04-v1.webp",
    alt: "十二扇门、观察者席与零号钥匙组成的第四夜夜印",
    category: "night-seal",
    status: "complete",
  },
  seal05: {
    id: "case.chihaya-noa.night-seal.05",
    src: "/art/cases/chihaya-noa/night-seals/night-05-v1.webp",
    alt: "十三张独立签名车票围绕熄灭镜面的第五夜夜印",
    category: "night-seal",
    status: "complete",
  },
  postcard01: {
    id: "case.chihaya-noa.postcard.01",
    src: "/art/cases/chihaya-noa/postcards/night-01-mist-harbor-v1.webp",
    alt: "雾港入境厅、停用站台与尚未发售的第十三号车票",
    category: "postcard",
    status: "complete",
  },
  postcard02: {
    id: "case.chihaya-noa.postcard.02",
    src: "/art/cases/chihaya-noa/postcards/night-02-switchback-alley-v1.webp",
    alt: "折返巷里两条互不覆盖的纸结路线穿过被改写的街图",
    category: "postcard",
    status: "complete",
  },
  postcard03: {
    id: "case.chihaya-noa.postcard.03",
    src: "/art/cases/chihaya-noa/postcards/night-03-archlight-vault-v1.webp",
    alt: "拱灯学会无编号镜片库与被抹去来路的收藏目录",
    category: "postcard",
    status: "complete",
  },
  postcard04: {
    id: "case.chihaya-noa.postcard.04",
    src: "/art/cases/chihaya-noa/postcards/night-04-unmade-addresses-v1.webp",
    alt: "未成线十二户折返公寓、门牌与生活账簿",
    category: "postcard",
    status: "complete",
  },
  postcard05: {
    id: "case.chihaya-noa.postcard.05",
    src: "/art/cases/chihaya-noa/postcards/night-05-thirteen-doors-v1.webp",
    alt: "黎明前十三扇门为十三张签名车票分别保留出口",
    category: "postcard",
    status: "complete",
  },
  botanical01: {
    id: "case.chihaya-noa.botanical.01",
    src: "/art/cases/chihaya-noa/botany/night-01-multiple-arrival-herb-v1.webp",
    alt: "十二片入境章状叶片托住一枚未来花苞的复抵草标本",
    category: "botanical",
    status: "complete",
  },
  botanical02: {
    id: "case.chihaya-noa.botanical.02",
    src: "/art/cases/chihaya-noa/botany/night-02-paper-knot-vine-v1.webp",
    alt: "两条纸带藤蔓沿不同折痕生长却共享根系的纸结藤标本",
    category: "botanical",
    status: "complete",
  },
  botanical03: {
    id: "case.chihaya-noa.botanical.03",
    src: "/art/cases/chihaya-noa/botany/night-03-copper-mirror-orchid-v1.webp",
    alt: "铜绿花萼托住不映面孔镜片的返照镜兰标本",
    category: "botanical",
    status: "complete",
  },
  botanical04: {
    id: "case.chihaya-noa.botanical.04",
    src: "/art/cases/chihaya-noa/botany/night-04-unmade-address-fern-v1.webp",
    alt: "十二片门牌状叶片保存各自生活刻痕的未成住址蕨标本",
    category: "botanical",
    status: "complete",
  },
  botanical05: {
    id: "case.chihaya-noa.botanical.05",
    src: "/art/cases/chihaya-noa/botany/night-05-thirteen-name-flower-v1.webp",
    alt: "十三枚独立花瓣围绕开放花心的十三名晨花标本",
    category: "botanical",
    status: "complete",
  },
  noa: {
    id: "case.chihaya-noa.character.noa",
    src: "/art/cases/chihaya-noa/characters/chihaya-noa-portrait-v1.webp",
    alt: "手持未来车票与纸结、平静直视档案镜头的千早诺亚",
    category: "character-portrait",
    status: "complete",
  },
  irisBell: {
    id: "case.chihaya-noa.character.iris-bell",
    src: "/art/cases/chihaya-noa/characters/iris-bell-portrait-v1.webp",
    alt: "夹着被刮改编目卡、对学会收藏制度保持警惕的艾瑞丝·贝尔",
    category: "character-portrait",
    status: "complete",
  },
  arthurVale: {
    id: "case.chihaya-noa.character.arthur-vale",
    src: "/art/cases/chihaya-noa/characters/arthur-vale-portrait-v1.webp",
    alt: "手持观察者席记录册、试图把裁决伪装成规律的亚瑟·韦尔",
    category: "character-portrait",
    status: "complete",
  },
  sixthNoa: {
    id: "case.chihaya-noa.character.sixth-noa",
    src: "/art/cases/chihaya-noa/characters/sixth-route-noa-portrait-v1.webp",
    alt: "衣着和伤痕与来访者不同、保留独立生活记忆的第六路诺亚",
    category: "character-portrait",
    status: "complete",
  },
  mistHarbor: {
    id: "case.chihaya-noa.district.mist-harbor",
    src: "/art/cases/chihaya-noa/districts/mist-harbor-v1.webp",
    alt: "雾港区层叠入境厅、雨棚铁路与十三号停用站台",
    category: "district-illustration",
    status: "complete",
  },
  archlightRow: {
    id: "case.chihaya-noa.district.archlight-row",
    src: "/art/cases/chihaya-noa/districts/archlight-society-row-v1.webp",
    alt: "拱灯学会街的收藏馆、黄铜拱门与地下镜片库入口",
    category: "district-illustration",
    status: "complete",
  },
  unmadeLine: {
    id: "case.chihaya-noa.district.unmade-line",
    src: "/art/cases/chihaya-noa/districts/unmade-line-v1.webp",
    alt: "未成线地下街区的十二户折返公寓、零号门与不完整轨道",
    category: "district-illustration",
    status: "complete",
  },
} as const satisfies Record<string, GameAsset>;
