import type { GameAsset } from "./assets";

export const fogWithoutWolvesAssets = {
  handoff: {
    id: "case.fog-without-wolves.header.handoff",
    src: "/art/cases/fog-without-wolves/headers/shift-handoff-v1.webp",
    alt: "拉普拉斯与特蕾莎隔着染血银铃在夜班事务所完成案件交接",
    category: "header",
    status: "complete",
  },
  night: {
    id: "case.fog-without-wolves.header.night",
    src: "/art/cases/fog-without-wolves/headers/night-expedition-v1.webp",
    alt: "林渡穿过雨夜剧院、货运机械与无舌铜钟追查两段回声",
    category: "header",
    status: "complete",
  },
  morning: {
    id: "case.fog-without-wolves.header.morning",
    src: "/art/cases/fog-without-wolves/headers/morning-report-v1.webp",
    alt: "林渡在清晨带回两只蜡筒、缺刻怀表和未签报告",
    category: "header",
    status: "complete",
  },
  ending: {
    id: "case.fog-without-wolves.ending.tableau",
    src: "/art/cases/fog-without-wolves/headers/ending-tableau-v1.webp",
    alt: "无舌巨钟下放着不成对手套与没有唯一结论的最终报告",
    category: "ending",
    status: "complete",
  },
  bloodiedBell: {
    id: "collectible.fog-without-wolves.bloodied-bell",
    src: "/art/cases/fog-without-wolves/collectibles/bloodied-silver-bell-v1.webp",
    alt: "沾着暗红污迹且失去铃舌的旧银铃",
    category: "collectible",
    status: "complete",
  },
  whiteChalk: {
    id: "collectible.fog-without-wolves.white-chalk",
    src: "/art/cases/fog-without-wolves/collectibles/white-chalk-shard-v1.webp",
    alt: "在档案纸上留下一圈粉尘的白粉笔残段",
    category: "collectible",
    status: "complete",
  },
  twinWillFolder: {
    id: "collectible.fog-without-wolves.twin-will-folder",
    src: "/art/cases/fog-without-wolves/collectibles/twin-will-folder-v1.webp",
    alt: "以旧酒红细绳和黄铜扣束起的双份遗书档案夹",
    category: "collectible",
    status: "complete",
  },
  tonguelessBell: {
    id: "collectible.fog-without-wolves.tongueless-bell",
    src: "/art/cases/fog-without-wolves/collectibles/tongueless-bell-v1.webp",
    alt: "内部空缺、表面留有细裂纹的剧院实验铜钟",
    category: "collectible",
    status: "complete",
  },
  pairedCylinders: {
    id: "collectible.fog-without-wolves.paired-cylinders",
    src: "/art/cases/fog-without-wolves/collectibles/paired-cylinders-v1.webp",
    alt: "并排躺在深蓝绒盘中且声纹不同的两只蜡筒",
    category: "collectible",
    status: "complete",
  },
  mismatchedGloves: {
    id: "collectible.fog-without-wolves.mismatched-gloves",
    src: "/art/cases/fog-without-wolves/collectibles/mismatched-glove-clasp-v1.webp",
    alt: "一深一浅、左右不成对却被谨慎放在一起的旧手套",
    category: "collectible",
    status: "complete",
  },
  splitMinuteWatch: {
    id: "collectible.fog-without-wolves.split-minute-watch",
    src: "/art/cases/fog-without-wolves/collectibles/split-minute-watch-v1.webp",
    alt: "钟面缺失一段分钟刻度并露出细密齿轮的银怀表",
    category: "collectible",
    status: "complete",
  },
  unsignedReport: {
    id: "collectible.fog-without-wolves.unsigned-report",
    src: "/art/cases/fog-without-wolves/collectibles/unsigned-final-report-v1.webp",
    alt: "被黄铜夹和无字封蜡固定、签名处仍然空白的最终报告",
    category: "collectible",
    status: "complete",
  },
  seal01: {
    id: "case.fog-without-wolves.night-seal.01",
    src: "/art/cases/fog-without-wolves/night-seals/night-01-v1.webp",
    alt: "银铃与两道错位粉笔圆组成的第一夜夜印",
    category: "night-seal",
    status: "complete",
  },
  seal02: {
    id: "case.fog-without-wolves.night-seal.02",
    src: "/art/cases/fog-without-wolves/night-seals/night-02-v1.webp",
    alt: "剧院帷幕、无舌铜钟与交叉猎手杖组成的第二夜夜印",
    category: "night-seal",
    status: "complete",
  },
  seal03: {
    id: "case.fog-without-wolves.night-seal.03",
    src: "/art/cases/fog-without-wolves/night-seals/night-03-v1.webp",
    alt: "两只蜡筒以一段声纹相连组成的第三夜夜印",
    category: "night-seal",
    status: "complete",
  },
  seal04: {
    id: "case.fog-without-wolves.night-seal.04",
    src: "/art/cases/fog-without-wolves/night-seals/night-04-v1.webp",
    alt: "缺失一段刻度的怀表与相反阴影组成的第四夜夜印",
    category: "night-seal",
    status: "complete",
  },
  seal05: {
    id: "case.fog-without-wolves.night-seal.05",
    src: "/art/cases/fog-without-wolves/night-seals/night-05-v1.webp",
    alt: "两只不成对手套围住钟形空白组成的第五夜夜印",
    category: "night-seal",
    status: "complete",
  },
  postcard01: {
    id: "case.fog-without-wolves.postcard.01",
    src: "/art/cases/fog-without-wolves/postcards/night-01-white-bell-house-v1.webp",
    alt: "停摆时钟与两道人影笼罩的白钟区雨夜住宅",
    category: "postcard",
    status: "complete",
  },
  postcard02: {
    id: "case.fog-without-wolves.postcard.02",
    src: "/art/cases/fog-without-wolves/postcards/night-02-saint-vesper-theatre-v1.webp",
    alt: "无舌铜钟与两只器材箱留在圣维斯帕剧院空舞台",
    category: "postcard",
    status: "complete",
  },
  postcard03: {
    id: "case.fog-without-wolves.postcard.03",
    src: "/art/cases/fog-without-wolves/postcards/night-03-cylinder-vault-v1.webp",
    alt: "两只蜡筒与黄铜听音号角保存在秘密声学档案室",
    category: "postcard",
    status: "complete",
  },
  postcard04: {
    id: "case.fog-without-wolves.postcard.04",
    src: "/art/cases/fog-without-wolves/postcards/night-04-missing-minute-archive-v1.webp",
    alt: "成排停摆怀表与缺刻钟面散落在市政计时档案室",
    category: "postcard",
    status: "complete",
  },
  postcard05: {
    id: "case.fog-without-wolves.postcard.05",
    src: "/art/cases/fog-without-wolves/postcards/night-05-thirteenth-bell-v1.webp",
    alt: "黎明照进暮钟工场，无舌巨钟悬在不成对手套上方",
    category: "postcard",
    status: "complete",
  },
  botanical01: {
    id: "case.fog-without-wolves.botanical.01",
    src: "/art/cases/fog-without-wolves/botany/night-01-double-shadow-fern-v1.webp",
    alt: "卷叶与根系间垂着微小钟花并覆有白尘的钟尘蕨标本",
    category: "botanical",
    status: "complete",
  },
  botanical02: {
    id: "case.fog-without-wolves.botanical.02",
    src: "/art/cases/fog-without-wolves/botany/night-02-tongueless-bellflower-v1.webp",
    alt: "深色藤蔓缠成两根猎手杖并开出旧酒红花的帷刺藤标本",
    category: "botanical",
    status: "complete",
  },
  botanical03: {
    id: "case.fog-without-wolves.botanical.03",
    src: "/art/cases/fog-without-wolves/botany/night-03-cylinder-reed-v1.webp",
    alt: "两枚带细密纵纹的深色种荚并生于同一茎上的双录芦标本",
    category: "botanical",
    status: "complete",
  },
  botanical04: {
    id: "case.fog-without-wolves.botanical.04",
    src: "/art/cases/fog-without-wolves/botany/night-04-missing-minute-moss-v1.webp",
    alt: "浅色放射花冠缺失一段花瓣的失分钟花标本",
    category: "botanical",
    status: "complete",
  },
  botanical05: {
    id: "case.fog-without-wolves.botanical.05",
    src: "/art/cases/fog-without-wolves/botany/night-05-nameless-echo-bloom-v1.webp",
    alt: "深浅两片花冠围住钟形开放空白的见证钟兰标本",
    category: "botanical",
    status: "complete",
  },
  laplace: {
    id: "case.fog-without-wolves.character.laplace",
    src: "/art/cases/fog-without-wolves/characters/laplace-portrait-v1.webp",
    alt: "佩戴黄铜听音器、警觉望向画外回声的拉普拉斯",
    category: "character-portrait",
    status: "complete",
  },
  theresa: {
    id: "case.fog-without-wolves.character.theresa",
    src: "/art/cases/fog-without-wolves/characters/theresa-vale-portrait-v1.webp",
    alt: "穿夜运制服、戴浅色工作手套并克制直视的特蕾莎·维尔",
    category: "character-portrait",
    status: "complete",
  },
  ada: {
    id: "case.fog-without-wolves.character.ada",
    src: "/art/cases/fog-without-wolves/characters/ada-morne-portrait-v1.webp",
    alt: "把护目镜推上额头并佩着音叉的老声学技师艾达·莫恩",
    category: "character-portrait",
    status: "complete",
  },
  felix: {
    id: "case.fog-without-wolves.character.felix",
    src: "/art/cases/fog-without-wolves/characters/felix-rowe-portrait-v1.webp",
    alt: "衣襟留有白粉笔灰且神情冷静固执的费利克斯·罗",
    category: "character-portrait",
    status: "complete",
  },
  whiteBell: {
    id: "case.fog-without-wolves.district.white-bell",
    src: "/art/cases/fog-without-wolves/districts/white-bell-quarter-v1.webp",
    alt: "层叠旧住宅、货运高架与停摆公共钟组成的白钟区",
    category: "district-illustration",
    status: "complete",
  },
  saintVesper: {
    id: "case.fog-without-wolves.district.saint-vesper",
    src: "/art/cases/fog-without-wolves/districts/saint-vesper-theatre-row-v1.webp",
    alt: "圣维斯帕剧院、声学管路与湿轨相接的雨夜街区",
    category: "district-illustration",
    status: "complete",
  },
  unlistedBellworks: {
    id: "case.fog-without-wolves.district.unlisted-bellworks",
    src: "/art/cases/fog-without-wolves/districts/unlisted-bellworks-v1.webp",
    alt: "空钟轮廓悬在雾灯城工业边缘高架中的地图外钟工场",
    category: "district-illustration",
    status: "complete",
  },
} as const satisfies Record<string, GameAsset>;
