import type { GameAsset } from "./assets";

export const thirteenthLoafAssets = {
  handoff: {
    id: "case.thirteenth-loaf.header.handoff",
    src: "/art/cases/thirteenth-loaf/headers/shift-handoff-v1.webp",
    alt: "林渡站在夜班事务所门边，桌上篮中放着无主面包与一排黄铜持份环",
    category: "header",
    status: "complete",
  },
  night: {
    id: "case.thirteenth-loaf.header.night",
    src: "/art/cases/thirteenth-loaf/headers/night-expedition-v1.webp",
    alt: "林渡抱着面包沿市政蒸汽管与面包柜组成的雨夜长廊调查",
    category: "header",
    status: "complete",
  },
  morning: {
    id: "case.thirteenth-loaf.header.morning",
    src: "/art/cases/thirteenth-loaf/headers/morning-report-v1.webp",
    alt: "林渡在黎明带着面包和封存报告走进十二张空工作台围绕的合作面包房",
    category: "header",
    status: "complete",
  },
  ending: {
    id: "case.thirteenth-loaf.ending.tableau",
    src: "/art/cases/thirteenth-loaf/headers/ending-tableau-v1.webp",
    alt: "十二枚黄铜持份环围着一只无主面包，旁边放着烧焦房契、熔断器与酵母罐",
    category: "ending",
    status: "complete",
  },
  tallyRing: {
    id: "collectible.thirteenth-loaf.tally-ring",
    src: "/art/cases/thirteenth-loaf/collectibles/tally-ring-v1.webp",
    alt: "内槽留着面粉的厚黄铜合作社持份环",
    category: "collectible",
    status: "complete",
  },
  cabinetHook: {
    id: "collectible.thirteenth-loaf.cabinet-hook",
    src: "/art/cases/thirteenth-loaf/collectibles/cabinet-hook-v1.webp",
    alt: "系着旧酒红线的铜绿面包保温柜挂钩",
    category: "collectible",
    status: "complete",
  },
  blankGuestToken: {
    id: "collectible.thirteenth-loaf.blank-guest-token",
    src: "/art/cases/thirteenth-loaf/collectibles/blank-guest-token-v1.webp",
    alt: "没有姓名、标记或编号的黄铜边椭圆访客牌",
    category: "collectible",
    status: "complete",
  },
  flourRouteSpool: {
    id: "collectible.thirteenth-loaf.flour-route-spool",
    src: "/art/cases/thirteenth-loaf/collectibles/flour-route-spool-v1.webp",
    alt: "缠着铜线与面粉色细绳的夜间送面包路线线轴",
    category: "collectible",
    status: "complete",
  },
  heatMainFuse: {
    id: "collectible.thirteenth-loaf.heat-main-fuse",
    src: "/art/cases/thirteenth-loaf/collectibles/heat-main-fuse-v1.webp",
    alt: "一端熔成扇形焦痕、市政侧先受热的陶瓷黄铜熔断器",
    category: "collectible",
    status: "complete",
  },
  inspectorSeal: {
    id: "collectible.thirteenth-loaf.inspector-seal",
    src: "/art/cases/thirteenth-loaf/collectibles/scorched-inspector-seal-v1.webp",
    alt: "边缘烧焦并系着断裂封线的热力检察圆章",
    category: "collectible",
    status: "complete",
  },
  starterLid: {
    id: "collectible.thirteenth-loaf.starter-lid",
    src: "/art/cases/thirteenth-loaf/collectibles/shared-starter-lid-v1.webp",
    alt: "带发酵观察窗、旧布与酒红系绳的深蓝酵母罐盖",
    category: "collectible",
    status: "complete",
  },
  deedClasp: {
    id: "collectible.thirteenth-loaf.deed-clasp",
    src: "/art/cases/thirteenth-loaf/collectibles/commons-deed-clasp-v1.webp",
    alt: "两只铜绿手掌托住无主面包的烧焦房契扣",
    category: "collectible",
    status: "complete",
  },
  seal01: {
    id: "case.thirteenth-loaf.night-seal.01",
    src: "/art/cases/thirteenth-loaf/night-seals/night-01-v1.webp",
    alt: "保温柜、面包与空挂钩组成的第一夜夜印",
    category: "night-seal",
    status: "complete",
  },
  seal02: {
    id: "case.thirteenth-loaf.night-seal.02",
    src: "/art/cases/thirteenth-loaf/night-seals/night-02-v1.webp",
    alt: "持份环围绕空白访客牌组成的第二夜夜印",
    category: "night-seal",
    status: "complete",
  },
  seal03: {
    id: "case.thirteenth-loaf.night-seal.03",
    src: "/art/cases/thirteenth-loaf/night-seals/night-03-v1.webp",
    alt: "市政热力管向完整面包炉留下焦痕的第三夜夜印",
    category: "night-seal",
    status: "complete",
  },
  seal04: {
    id: "case.thirteenth-loaf.night-seal.04",
    src: "/art/cases/thirteenth-loaf/night-seals/night-04-v1.webp",
    alt: "酵母罐沿铜线连接街区窗户的第四夜夜印",
    category: "night-seal",
    status: "complete",
  },
  seal05: {
    id: "case.thirteenth-loaf.night-seal.05",
    src: "/art/cases/thirteenth-loaf/night-seals/night-05-v1.webp",
    alt: "双手托住公共面包并保留开放入口的第五夜夜印",
    category: "night-seal",
    status: "complete",
  },
  postcard01: {
    id: "case.thirteenth-loaf.postcard.01",
    src: "/art/cases/thirteenth-loaf/postcards/night-01-warming-cabinet-v1.webp",
    alt: "煤钟街雨夜里半开的面包保温柜与通向合作社的面粉脚印",
    category: "postcard",
    status: "complete",
  },
  postcard02: {
    id: "case.thirteenth-loaf.postcard.02",
    src: "/art/cases/thirteenth-loaf/postcards/night-02-twelve-aprons-v1.webp",
    alt: "合作社空工作台、整排围裙与中央桌上的无主面包",
    category: "postcard",
    status: "complete",
  },
  postcard03: {
    id: "case.thirteenth-loaf.postcard.03",
    src: "/art/cases/thirteenth-loaf/postcards/night-03-heat-main-v1.webp",
    alt: "炉桥下市政热力管破口把焦痕指向仍完整的面包炉",
    category: "postcard",
    status: "complete",
  },
  postcard04: {
    id: "case.thirteenth-loaf.postcard.04",
    src: "/art/cases/thirteenth-loaf/postcards/night-04-starter-courtyard-v1.webp",
    alt: "多户窗台的酵母罐沿夜间路线连向地下公共面包炉",
    category: "postcard",
    status: "complete",
  },
  postcard05: {
    id: "case.thirteenth-loaf.postcard.05",
    src: "/art/cases/thirteenth-loaf/postcards/night-05-guest-share-v1.webp",
    alt: "黎明开放的合作面包房把一只无主面包留在街边柜中",
    category: "postcard",
    status: "complete",
  },
  botanical01: {
    id: "case.thirteenth-loaf.botanical.01",
    src: "/art/cases/thirteenth-loaf/botany/night-01-warming-wheat-v1.webp",
    alt: "深蓝叶片托住面包状种荚、根部带面粉孢尘的暖柜麦标本",
    category: "botanical",
    status: "complete",
  },
  botanical02: {
    id: "case.thirteenth-loaf.botanical.02",
    src: "/art/cases/thirteenth-loaf/botany/night-02-twelve-finger-rye-v1.webp",
    alt: "持份环状花萼围住一枚无主暖色花苞的十二指黑麦标本",
    category: "botanical",
    status: "complete",
  },
  botanical03: {
    id: "case.thirteenth-loaf.botanical.03",
    src: "/art/cases/thirteenth-loaf/botany/night-03-heat-main-sedge-v1.webp",
    alt: "横向铜管根茎一侧留着扇形焦叶的热力管莎草标本",
    category: "botanical",
    status: "complete",
  },
  botanical04: {
    id: "case.thirteenth-loaf.botanical.04",
    src: "/art/cases/thirteenth-loaf/botany/night-04-shared-starter-vine-v1.webp",
    alt: "从酵母罐根冠分出许多暖色种荚路线的共酵藤标本",
    category: "botanical",
    status: "complete",
  },
  botanical05: {
    id: "case.thirteenth-loaf.botanical.05",
    src: "/art/cases/thirteenth-loaf/botany/night-05-guest-share-dawnflower-v1.webp",
    alt: "深蓝外叶围住暖色面包花芯、根系向外开放的客份晨花标本",
    category: "botanical",
    status: "complete",
  },
  songCen: {
    id: "case.thirteenth-loaf.character.song-cen",
    src: "/art/cases/thirteenth-loaf/characters/song-cen-portrait-v1.webp",
    alt: "一手持黄铜持份环、一手持空白访客牌的合作社账房宋岑",
    category: "character-portrait",
    status: "complete",
  },
  feiCheng: {
    id: "case.thirteenth-loaf.character.fei-cheng",
    src: "/art/cases/thirteenth-loaf/characters/fei-cheng-portrait-v1.webp",
    alt: "怀抱压力表与陶瓷熔断器的退役热力检察员费澄",
    category: "character-portrait",
    status: "complete",
  },
  keYao: {
    id: "case.thirteenth-loaf.character.ke-yao",
    src: "/art/cases/thirteenth-loaf/characters/ke-yao-portrait-v1.webp",
    alt: "抱着纸包面包、手持黄铜自行车灯的夜间送货员柯遥",
    category: "character-portrait",
    status: "complete",
  },
  heLi: {
    id: "case.thirteenth-loaf.character.he-li",
    src: "/art/cases/thirteenth-loaf/characters/he-li-portrait-v1.webp",
    alt: "抱着烧焦房契并手持修复折刀的档案修复师何砾",
    category: "character-portrait",
    status: "complete",
  },
  coalclockRow: {
    id: "case.thirteenth-loaf.district.coalclock-row",
    src: "/art/cases/thirteenth-loaf/districts/coalclock-row-v1.webp",
    alt: "煤钟街空白钟塔、蒸汽管、面包柜和夜间烘焙坡道",
    category: "district-illustration",
    status: "complete",
  },
  ovenbridge: {
    id: "case.thirteenth-loaf.district.ovenbridge",
    src: "/art/cases/thirteenth-loaf/districts/ovenbridge-arcades-v1.webp",
    alt: "炉桥廊层叠石拱、市政热力管、阀门房与雨湿检修台阶",
    category: "district-illustration",
    status: "complete",
  },
  dawnGranary: {
    id: "case.thirteenth-loaf.district.dawn-granary",
    src: "/art/cases/thirteenth-loaf/districts/dawn-granary-v1.webp",
    alt: "黎明粮仓的河岸拱廊、运粮车、自行车坡道与公共庭院",
    category: "district-illustration",
    status: "complete",
  },
} as const satisfies Record<string, GameAsset>;
